### ISSUE TITLE
Saved file, compress more than just the layer data

### ISSUE THREAD

**Issue by voidburn** [mapeditor/tiled#1191]
A map with tons of animations and objects in object groups can still produce a very large file, how hard would it be to extend the data compression to as many properties as possible, other than simply the layer data?

**Comment by bjorn** [comment]
At that point, it would make more sense to compress the entire file. That will however make it impossible to see what is changing in version control software (I realize this is already the case for compressed layer data, but in that case the diff wasn't much use already anyway).

If you really need a compressed file also in version control, then support for .tmx.gz files could be added for example. In fact, the old Tiled Java version already supported this.

**Comment by voidburn** [comment]
As long as the editor detects the gz format and deflates the file on load, yeah, it could make sense as a completely different save option rather than internal format. Usually the only times I need to open the TMX in a text editor is when it ends up using absolute paths to external assets (images) instead of relative ones (tbh it should never use absolute paths, there's no deployment scenario in which it makes sense). Without that issue I hardly ever had to check the source, and even if so, I can switch the format on the fly to inspect the xml.

**Comment by bjorn** [comment]
Yeah, the idea is to support a `.tmx.gz` format transparently for saving and loading.

**Comment by bjorn** [comment]
> (tbh it should never use absolute paths, there's no deployment scenario in which it makes sense)

I agree they never make sense, but if the user chooses files that are on different drives then Tiled has no other way to refer to them. Of course, in addition to falling back to absolute paths, it could also warn the user when he tries to add references to such files.

Unfortunately, choosing files is not the only way to mess up the references. Another way is to save your map to a different drive than where you assets are. Of course, a similar warning message could be added there.

Btw, since Tiled 0.15 there is no real need anymore to use a text editor to correct such references. You can now do it from the Tiled UI.

**Comment by voidburn** [comment]
Indeed the paths issue is a thorny argument, but editing directly in the UI is very welcome feature! 

A solution could be specifying working paths where TileD can search for the assets (the user can be prompted the first time he tries to import something), and then just reference the assets by unique name. Pretty much like packing sprites inside an atlas works, minus the hassle of having to keep track of their coordinates. It would keep the references in the XML clean, and move the path dependency/resolution on its own tag.

**Comment by bjorn** [comment]
Yeah, that last suggestion is something I should consider once Tiled has support for projects. Until then there is not really a good place to store such a working path.
