### ISSUE TITLE
Ignore transparent pixels when selecting objects

### ISSUE THREAD

**Issue by X-Ray-Jin** [mapeditor/tiled#1477]
I think it would be nice and more intuitive, if the object selection tool ignores transparent pixels. It allows for more easy selection of objects that are behind others but are still at least partly visible. A setting or hotkey to switch to deactivate it generally or temporarily might be a good thing though.

**Comment by UliAbo** [comment]
Oh I didn't know this already existed here for 5 years. So I fully support this feature and think it's not only a big convenience bonus. It also makes projects possible, which formerly were kind of forced to rely on Object Collections instead of pure Tile Sets like described here: https://github.com/mapeditor/tiled/issues/3330

**Comment by bjorn** [comment]
I've added this new option to the preferences for now:

![image](https://user-images.githubusercontent.com/531764/166235126-d0afa3ee-87ba-4ae0-a333-385e18223546.png)

Given that the new behavior is likely more useful, it is enabled by default.
