### ISSUE TITLE
automap behaviour is counter intuitive when some tiles are empty on input_layer

### ISSUE THREAD

**Issue by axboureau** [mapeditor/tiled#1520]
I find the rules for counting matches counter intuitive when there are some empty tiles. I think it is related to issue #1276.

Not sure which ones should be considered bugs:

- inputnot_layera  always fails when layera is not present

It is probably not a big deal, as there would be little reason to define an inputnot_layer in this case, and a blank input layer would be enough, but the result is unexpected, so I think inputnot_layer should return a match if the layer is absent.

- The match fails if there is a tile defined in the region, for which there is no matching tiles in any of the
input layers. 
![tiled_automap_issue1](https://cloud.githubusercontent.com/assets/3704031/24555174/76e0dd5a-1630-11e7-8367-5cda7d57032b.png)
Here, the region is 2 tiles. Only one is checked on input_structure, but if there is nothing on the structure layer at the position of the second, it does not count as a match.
Having anything there on this structure layer counts as a match. 

- Sometimes, having an empty tile in the rule file makes the match fails.

![tiled_automap_issue2](https://cloud.githubusercontent.com/assets/3704031/24555184/7e106992-1630-11e7-80b1-e8fa30eeb3dc.png)

This one is puzzling too: 
This time, there are 2 floor tiles on the wallbases layer, but only one is required according to the input_wallbases layer. This result in a missmatch. But if we add another floor tile on the input_structure layer, it becomes a match, even though we added a condition, and didn't change the structure layer itself.

**Comment by bjorn** [comment]
> It is probably not a big deal, as there would be little reason to define an inputnot_layer in this case, and a blank input layer would be enough, but the result is unexpected, so I think inputnot_layer should return a match if the layer is absent.

I agree.

In general, I hope @stefanbeller could weigh in on the other parts, since they are a bit beyond me and I don't know the details about why the system works like it does.

**Comment by bjorn** [comment]
Related forum threads:

* http://discourse.mapeditor.org/t/automap-rules-input-multiple-layers/438/10
* http://discourse.mapeditor.org/t/trying-to-understand-solve-an-issue-with-automapping-hope-someone-can-help/2228

**Comment by bjorn** [comment]
This behavior will stay counter-intuitive for compatibility reasons, but a more intuitive solution has been implemented as part of #1918 and #3100. The relevant improvements are two-fold:

* When you don't explicitly define the input regions (so no "regions" or "regions_input" layers are present), these regions are derived from the tiles placed on the input layers. In this case, empty tiles are by default ignored (with the only remaining exception, that setting `StrictEmpty` (or its new alias, `AutoEmpty`), will mean empty tiles where other input layers do have content will match with empty tiles).\
\
Using explicitly defined regions will be effectively deprecated in Tiled 1.9.

* And with #3100, if you do explicitly want to allow or disallow empty tiles, you can use any tile where you set a custom property `MatchType` to `Empty` or `NonEmpty` respectively. And if you want to explicitly trigger the previously counter intuitive behavior, you can set `MatchType` to `Other`.\
\
The plan is to ship a suitable tileset along with or inside Tiled, but you can also set up your own using these tile properties.

I'm closing this issue since it's effectively been superseded by #1918 and #3100.
