### ISSUE TITLE
Suggestion: Don't require save on map creation

### ISSUE THREAD

**Issue by Koopa1018** [mapeditor/tiled#1902]
As it stands, Tiled forces you to save a map to a file the moment you create it.

The way I see it, this is suboptimal for a number of reasons:
1. No other program that I know of does this. In Libre Office, in GIMP, in Blender, you create a new file, and there it is, ready to edit right away, even though it doesn't exist on disk yet. Consistency between programs isn't strictly a necessity, I'd say, but it sure is more convenient. But more importantly...
2. The inconvenience of it breaks artistic flow. When I create a new map, I don't want to worry about file organization, I just want to start mapping. I've gotten pretty good at "suspending" the flow so I can set the workspace up for it, but from what I hear, that's not a common skill.
3. What if you don't want to save it? What if you just want to tool around for a bit, and only save it if it turns out good? Saving the file (at least for me) lends an air of finality, as if to say "yes, this map is worth saving," and that isn't always what you want.

As I recall, Tiled didn't used to do this. Was there a good reason for this change? And is there a good reason to keep it like this?

**Comment by bjorn** [comment]
> As I recall, Tiled didn't used to do this. Was there a good reason for this change? And is there a good reason to keep it like this?

Yes, actually this changed in Tiled 1.0. It changed because since then, external tilesets are fully supported and can be created and opened separately from map files. It is actually the tilesets which need to be saved somewhere, before they can be used by a map. Problems would happen when you create a new tileset, then create a new map, and then saved the new map before saving the tileset, since the map would have no tileset file to refer to. I solved this problem by requiring tilesets to be saved upon creation, and did the same for map files for consistency.

I agree that it is a little annoying, and indeed I personally create "throw away" maps quite often. Though I'd probably rather solve this by taking the file management out of the user's responsibility and automating this as much as possible.

**Comment by Koopa1018** [comment]
Taking the file management out of the user's responsibility...that's an
interesting idea. Seems like that would be most convenient to manage with
the projects system in place (imagining the user creating a project,
choosing where to put the project's directory, and then letting Tiled
handle saving the associated maps...please correct me if that's not what
you mean!).

**Comment by bjorn** [comment]
@Koopa1018 That's exactly what I meant. It would indeed go hand-in-hand with project support (#1665). It's no longer going to happen for the next feature release, but it's one of the things I'd like to do for Tiled 1.3.

**Comment by santiontanon** [comment]
Any news on this? I also find it quite disturbing to have to think about where to save before starting to edit. I use Tiled a lot just to test how my tiles are looking, without actually wanting to save anything. I keep trying new versions of Tiled every once in a while to see if this is fixed, but I keep uninstalling and going back to a pre-1.0 version just because of this.

**Comment by bjorn** [comment]
@santiontanon Thanks for reminding me about this and letting us know that this problem can be quite severe. I've been working on the support for projects for the upcoming Tiled 1.4 and I'll be sure to look into a solution for this as part of that release.

But, using projects to alleviate the need for saving upon creation means to automate the saving as much as possible, whereas you don't want to save at all. Maybe it's worth reconsidering the argument of consistency and just allow maps to be created without saving.

**Comment by santiontanon** [comment]
No problem, thanks for considering it! :)

**Comment by santiontanon** [comment]
Just a friendly ping to check if this is still under consideration (I know you have 100s of open issues here, so, I don't mean to rush, since I know making every one happy can be overwhelming haha). But I thought I'd just bring this back to attention in case we get lucky and you have some bandwidth haha. In any case, again, no pressure, the project is already awesome as it is :)

**Comment by eishiya** [comment]
I create a lot of maps just for testing things and I do not want them to be saved at all, so just automating saving would *not* be a good fix for me, as the main problem for me isn't saving, but having to delete these unneeded maps afterwards. I'd like the ability to create and mess with maps without saving them.

On Discord, bjorn and I also discussed allowing the creation of Tilesets without saving.
Perhaps documents that haven't been saved to file should have reddened tabs, or a red icon next to them. On hover, they would show a tooltip that informs the user that "(Map|Tileset) must be saved before it can be used in other documents." Unsaved Tilesets could not show up in the Tilesets view at all, but I think this may lead to confusion as users might wonder why the tileset they created isn't available. Instead, I think it might be better to have them show up with the same red tab and hover message, and if selected in the tilesets panel, a message like "Tileset must be saved to a file before it can be used in maps." could be displayed instead of letting the user select tiles from it.

And a related concern: scripts can create TileMaps, but have no way to present them to the user except (maybe?) through forcing a save to some predetermined location in a predetermined format and then opening them from that file, which isn't great. If Tiled gains the ability to have unsaved maps as documents in the editor, then scripts should have the ability to make created TileMaps (and maybe Tilesets?) visible in the UI.
The most intuitive way (at least for me as a script writer) would be to allow assigning any Asset to `tiled.activeAsset`.
