### ISSUE TITLE
Menu bar not showing on Ubuntu 14.04 [FIX]

### ISSUE THREAD

**Issue by AriDeve** [mapeditor/tiled#1903]
So i had this issue where the menu bar of tiled just does not show. I read a lot of posts about this issue, but a lot of them were hard to understand.
The fix is simple: you have to remove `appmenu-qt5`
You can do that by following this guide how to remove `appmenu-qt5`

(You have to type or copy this in to terminal)
Uninstall just `appmenu-qt5`

    sudo apt-get remove appmenu-qt5
(This will remove just the `appmenu-qt5` package itself)

Uninstall `appmenu-qt5` and its dependencies

    sudo apt-get remove --auto-remove appmenu-qt5
(This will remove the `appmenu-qt5` package and any other dependant packages which are no longer needed.)
Now the `appmenu-qt5` should be removed and the menu bar should be showing.

**Comment by bjorn** [comment]
Thanks for opening this issue, maybe it helps others who are searching for a solution to this problem. Unfortunately, I think there is nothing I can do to fix this problem on the Tiled side.

The problem should only happen, when you somehow have `appmenu-qt5` installed but you are not using Unity, right? This should be a rare case, because it would mean you have installed Ubuntu and then switched to a different desktop environment.

Also, maybe you can tell me which version of Tiled you're using? Does this problem occur if you use the latest version available at itch.io (currently 1.1.3, or one of the snapshots)?

**Comment by rrmTV** [comment]
Hello.
Sorry for not responding for few days. The appmenu-qt5 was installed on my
ubuntu, but i do not have unity. I am using the newest version of tiled
from itch.io. I fixed this issue by removing appmenu-qt5, but im thinking
of maybe starting learning unity. Is there any way to use tiled with
appmenu-qt5 installed?
2018. gada 13. marts 11:43, "Thorbjørn Lindeijer" <notifications@github.com>
rakstīja:

**Comment by rrmTV** [comment]
Im sorry for responding in email.
I meant to post that on github
2018. gada 20. marts 18:36, "Macяø〖ƝƁƘ〗" <ralfs.muca@gmail.com> rakstīja:

**Comment by rrmTV** [comment]
Sorry for not responding for few days. The appmenu-qt5 was installed on my
ubuntu, but i do not have unity. I am using the newest version of tiled
from itch.io. I fixed this issue by removing appmenu-qt5, but im thinking
of maybe starting learning unity. Is there any way to use tiled with
appmenu-qt5 installed?

**Comment by bjorn** [comment]
> Sorry for not responding for few days. The `appmenu-qt5` was installed on my ubuntu, but i do not have Unity. I am using the newest version of Tiled from itch.io. I fixed this issue by removing `appmenu-qt5`, but im thinking of maybe starting learning Unity.

I wasn't talking about the Unity game development framework, but the Unity desktop environment that was the default environment for Ubuntu up until version 17.04. In Ubuntu 17.10, they switched the desktop environment back to GNOME.

As far as I know there is no way to use the Unity game development framework on Linux. It is only possible to deploy games to Linux.

> Is there any way to use Tiled with `appmenu-qt5` installed?

If you're not using the Unity desktop environment, then there is no reason to have `appmenu-qt5` installed.

Btw, since you're on Ubuntu, could you test something for me? I've recently built a snap package of Tiled and I am wondering whether it is affected by the menu bar issue. You can test it by installing Tiled using:
```
snap install tiled
```
(this will currently install Tiled 1.0.3 in `/snap/bin/tiled`)

Or you can install the bleeding edge version of Tiled using:
```
snap install tiled --edge
```
(this will install the latest Tiled compiled from the `master` branch)

**Comment by rrmTV** [comment]
Oh yeah im not using Unity desktop.

I will test them out now, but should i test them out with appmenu-qt5 or without?
Ill test both

**Comment by rrmTV** [comment]
It installed with snap, but the same problem happens. 
By the way is there any to make a 900 * 900px image to 900 * 900 tile map?(1 tile is 64 * 64px)

**Comment by bjorn** [comment]
> It installed with snap, but the same problem happens.

Regardless of whether `appmenu-qt5` is installed, or does it also happen with that package removed?

> By the way is there any to make a 900 * 900px image to 900 * 900 tile map?(1 tile is 64 * 64px)

That would mean you need to export at a 1.5625 % zoom level (1/64*100), and I think there is no way to reach that in the UI. However, you can instruct the `tmxrasterizer` tool that ships with Tiled to do this in two ways:
```
tmxrasterizer --size 900 map.tmx image.png
tmxrasterizer --tilesize 1 map.tmx image.png
```
If you're using the snap, it's available as `tiled.tmxrasterizer`.

**Comment by rrmTV** [comment]
Recently my RAM broke so I had to buy a new one, but yes even if it installs with snap the appmenu-qt5 still causes an issue. About the image size I needed the image to scale up because I am learning to program and I am making a game in python and I got the idea for this game from a different 3D game, but the map is huge.

**Comment by rmgr** [comment]
Just wanted to report that I'm getting this issue on Debian Bullseye with the KDE Plasma DE and I do not have the appmenu-qt5 package on my system.

**Comment by bjorn** [comment]
@rmgr Maybe it's called simply `appmenu-qt`? Or have a look at whether you have any other [`appmenu` packages](https://packages.debian.org/search?keywords=appmenu&searchon=names&suite=testing&section=all) installed. Apart from this appmenu thing I wouldn't know what else could cause the menu bar to be hidden.

**Comment by rmgr** [comment]
I don't have any appmenu packages. I just tried building from source and had the following warnings during the build process. I can run the result but still no menu. 
[build.txt](https://github.com/mapeditor/tiled/files/6999209/build.txt)

Previously I've tried using the appimage from the github releases and the flatpak.

**Comment by bjorn** [comment]
@rmgr Puh, that's really strange. The build warnings seem unrelated and not actually a problem.

I still think Qt is probably trying to show the menu through a D-BUS interface, so if you're building Tiled yourself you might try to disable linking to QtDbus. You can do this by passing `projects.Tiled.dbus:false` on the build command:

```
qbs resolve projects.Tiled.dbus:false
qbs
qbs run -p tiled
```

**Comment by rmgr** [comment]
The plot thickens. Building with linking to QtDbus doesn't resolve the issue. 

I noticed the following when running my compiled version.
```
Starting target. Full command line: /home/jake/tiled/default/install-root/usr/local/bin/tiled

QObject::connect: Cannot queue arguments of type 'Tiled::Issue'

(Make sure 'Tiled::Issue' is registered using qRegisterMetaType().)   

Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject*   

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1786, resource id: 14680246, major code: 40 (TranslateCoords), minor code: 0   

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1798, resource id: 14680241, major code: 40 (TranslateCoords), minor code: 0   
```

Through a bit of googling I found a github issue for [owncloud/client](https://github.com/owncloud/client/issues/4842) and I misread the solution so I ran Tiled as root and I have a menu bar. I then tried running the AppImage as root and that has a menu bar as well. So I'm guessing there's a dependency my user account doesn't have access to..?

**Comment by bjorn** [comment]
@rmgr Well, there is some mechanism by which Qt determines whether your desktop environment is using a global menu bar (like macOS, but I believe KDE also has such an option and Unity DE had as well). When this is the case, it will hide the menu bar and use some API to tell the desktop environment about the menu items.

This is what happened with the above `appmenu-qt5` package, which likely provided a Qt plugin that made it communicate with Unity so that it could show the menu bar. The problem of not seeing a menu at all happened because some people who were not using Unity (usually because they'd have switched to a different desktop environment) still had `appmenu-qt5` installed, so Qt was anyway trying to rely on the global menu bar.

There appears to be something in your settings or something running as part of your environment that makes Qt think it should rely on a global menu bar, which is not available when running as root. I expect when you'd create a new account you might also no longer have the problem. The tricky part would be in figuring out which setting or service should be disabled.

**Comment by rmgr** [comment]
So I just wanted to let you know I've figured out my case. I noticed other applications didn't seem to have a menu bar either.

In KDE there's a widget called "Global Menu" which takes the menu from your active window. Apparently I had that widget somewhere off-screen in my desktop setup. I removed all references to "org.kde.plasma.appmenu" from ~/.config/plasma-org.kde.plasma.desktop-appletsrc and rebooted and everything's working now!
