### ISSUE TITLE
Polygons Height/Width

### ISSUE THREAD

**Issue by Fredolx** [mapeditor/tiled#2131]
Is it possible to have a polygon's width and height? They are both 0,0 in the exported json.

**Comment by bjorn** [comment]
What would you use it for?

I could save the size of the bounding rect of the polygon as the `width` and `height` properties, but the polygon does not necessarily have a bounding rectangle that has its origin at the object's origin. It could have either a negative or a positive offset. In this case knowing the width/height of the polygon doesn't generally help you much, since you'd also need to know the offset.

Also since it's rather to determine the bounding rect of the polygon, I don't see much value of storing it in the map file.
