### ISSUE TITLE
Automapping: NoOverlap option does not work correctly when having different layers

### ISSUE THREAD

**Issue by stefanbeller** [mapeditor/tiled#250]
In AutoMapper::applyRule in section
// check if there are no overlaps within this rule.
the actual check should be done on the output layers not the input layers, as we want no overlaps in the output,
probably even both layer groups should be taken into account.

**Comment by eishiya** [comment]
IME overlapping based on the input region is most useful. If I'm adding details to chunks of wall or floor that go outside of that input area, that doesn't mean I want to skip the nearby chunks of wall or floor just because I've already placed details near them.

However, having this be configurable would be pretty cool, as I can also imagine scenarios where it's the total region of the rule (input+output) that matters.

I can't think of many scenarios where only the output region mattering is a good idea though, especially with output regions being automatically determined and therefore typically smaller than in the old way.

**Comment by bjorn** [comment]
@eishiya Hmm, this is actually an old issue and I just wanted to verify that it was done. As far as I could see, the `NoOverlappingRules` option applies to the output, and to each target layer individually at that (so, it also isn't affected by the output region, only by actually placed tiles).

Of course if you think some kind of `NoOverlappingInputRegion` is useful I can consider adding it, but you should open a new issue about that then. I don't think anybody else ever brought that up, though...

**Comment by eishiya** [comment]
Oh, so it works differently from how I thought o: I haven't used `NoOverlappingRules` all that much, so I guess my mistaken reasoning about it never actually mattered. I think it might be worth including more details about what counts as an overlap in the documentation, as it was the docs and the wall example there that made me think it was based on the input.

**Comment by bjorn** [comment]
It seems to me that the `NoOverlappingRules` option has worked per-layer output regions since its introduction in dc42b41e2cdba4021666ddc7e217316f3ced910e, so I'm closing this issue.
