### ISSUE TITLE
Simple background layers

### ISSUE THREAD

**Issue by Asmageddon** [mapeditor/tiled#266]
Most of the time after adding the maps into the game, you add a background. It would be nice if you could add simple image/gradient background layers, with optional parallax to more closely preview how they will look.

As an added bonus it will allow an easier and more intuitive way to embed background data into map files.

**Comment by ketanhwr** [comment]
@bjorn what exactly is the meaning of parallax feature? Something which displays all the layers like below?

![Parallax](http://opengameart.org/sites/default/files/styles/watermarked/public/Parallax.jpg "Parallax")

**Comment by bjorn** [comment]
@ketanhwr Visualizing the layers like that is not part of this feature. The feature would be that you could associate a depth or scroll speed factor with each layer, so that you can preview the parallax effect (see [this example on Wikipedia](https://en.wikipedia.org/wiki/Parallax_scrolling#Example)).

Note that @Zax37 recently [posted on the forum](http://discourse.mapeditor.org/t/layer-zoom-and-move-speed-repeated-layers/1336/2) that he was working on such a feature.

**Comment by ketanhwr** [comment]
Alright, thanks :-)

**Comment by bjorn** [comment]
Thanks to the work by @krukai, the image layers can now also be repeated!
