### ISSUE TITLE
Object flipped horizontally bug

### ISSUE THREAD

**Issue by yyman001** [mapeditor/tiled#2660]
version: 1.2.3
os: windows 10
when i flipped horizontally by one object in toolbar 
![image](https://user-images.githubusercontent.com/5688485/68466401-4c0fd780-024f-11ea-8dfc-054f109b21e7.png)

before:
![image](https://user-images.githubusercontent.com/5688485/68466495-7d88a300-024f-11ea-8799-712930eff4c9.png)
after:
![image](https://user-images.githubusercontent.com/5688485/68466596-aad55100-024f-11ea-9201-a572d66ad20e.png)
----------
when i flipped horizontally by attr... That's what I want
![image](https://user-images.githubusercontent.com/5688485/68466718-ef60ec80-024f-11ea-9834-bb48cc43f26e.png)

Is this a bug? thank!

**Comment by bjorn** [comment]
Well, the displacement is a bug. The change in angle not necessarily since along with flipping vertically the result is the same, but it is definitely unexpected.

This is the result of a change that fixed the flipping of rotated objects. Previously that would just flip the flag, but when an object is rotated then flipping it horizontally can be expected to change its rotation as well. But maybe for non-rotated objects, it should still just flip the flag. Besides that, we need to fix the position change. That's working fine on orthogonal maps, so in changing the position the isometric projection is not taken into account like it should.

Thanks for opening an issue about this!

**Comment by yyman001** [comment]
Waiting for your repair,  thanks!

**Comment by bjorn** [comment]
Please don't close the issue until the problem has been resolved. :-)

**Comment by rekcah1986** [comment]
I also met for this problem. We hope to solve the solution as soon as possible.
