### ISSUE TITLE
Scripting API extended menus are not shared throughout the editor

### ISSUE THREAD

**Issue by jacobcoughenour** [mapeditor/tiled#2680]
When using tiled.extendMenu(), only the main menus are changed.  Similar menus should share the same options as the main menus.

Example:

using some code from the docs:
```
var action = tiled.registerAction("CustomAction", function(action) {
	tiled.log(action.text + " was " + (action.checked ? "checked" : "unchecked"));
});

action.text = "My Custom Action";
action.checkable = true;
action.shortcut = "Ctrl+K";

tiled.extendMenu("NewLayer", [{ action: "CustomAction" }, { separator: true }]);
```

The custom action showing in the main menu.
![image](https://user-images.githubusercontent.com/5546400/69549506-6b08ac00-0f67-11ea-95ff-76a5ccb7bb27.png)

The custom action **not** in the Layers view right-click menu.
![image](https://user-images.githubusercontent.com/5546400/69549538-78be3180-0f67-11ea-91a9-dd0a5ee74394.png)
"My Custom Action" should also be in this menu.

**Comment by bjorn** [comment]
Hmm, right, the problem here occurs because these are not the same menu. They're different menus that are constructed with the same actions. And one of those menus is not registered (because currently this isn't supported for non-persistent menus), so it can't be extended.

But of course I agree that the actions are expected to be used by both menus. For this, we'll need to provide some mechanism by which dynamic menus can get extended (we need this anyway). It's almost possible, since the registered menu extensions are kept in `QVector<MenuExtension> mMenuExtensions` in the `ScriptModule`, so after a dynamic menu is created we can call some function that goes through the extensions for that menu and adds the additional actions.

The tricky thing here is mostly to implement this without calling into the `ScriptModule` from everywhere. But we're already registering menus with the `ActionManager`, so it may be reasonable to emit a signal from there each time this happens, which the `ScriptModule` can connect to in order to apply any extensions.

The `ActionManager` would also need to be changed to allow registering different `QMenu` instances with the same ID, because in the case of the "NewLayer" menu, we can't use the persistent menu instance in the context menu. Or we could just emit `menuRegistered(Id id, QMenu *menu)` for context menus directly, since we'd anyway have to immediately unregister them.

**Comment by bjorn** [comment]
Some context menus will be extensible in Tiled 1.5. I had missed the "New Layer" menu though, but that was easy to fix. :-)
