### ISSUE TITLE
Offset Tool should not be auto-selected

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#2807]
(Please let me know if I can improve my ticket description style, feedback welcome)

**Current behavior:**
When selecting a group layer, the Offset Tool is auto-selected. When then selecting a tile or object layer, the tool is still selected and causes trouble when clicking accidentally and then messing up the map by shifting it.

**Suggested new behavior:**
Remember the last active tool for each layer type, so that when you select a tile layer again, it also switches away from that Offset Tool back to what you last used on a tile layer. 

**Comment:**
The suggested new behavior was Bjorn's idea. Please see below and the replies afterwards. 

**Bjorn's original comments in Discord on May 26, 2020 at 10:46 PM:** 
(please delete when unnecessary, thought it could be helpful):
> I'm sorry to read about your frustration with the Offset Tool. Indeed, something needs to be done about that. The problem is that it is the only enabled tool when you select a group layer. This causes it to become the currently selected tool, since Tiled tries to be helpful (and it was helpful, when Tiled had only tile and object layers...). But now, it often leads to frustration.
> I think there could be a few potential solutions:
> 1. Don't automatically select another tool when the current one gets disabled, just have "no tool" active.
> 2. Remember the last active tool for each layer type, so that when you select a tile layer again, it also switches away from that Offset Tool back to what you last used on a tile layer.
> 3. When you have a group layer selected, enable tools based on all child layers. Tile layer tools would work on all nested tile layers and object layer tools on all object layers (mostly affects "Select All" behavior).
> Any other ideas welcome. I'll try to improve this for Tiled 1.4.

**Comment by bjorn** [comment]
I realize it was my first suggestion, but to have no active tool will I think get annoying really fast when switching between tile layers and object layers. Because in that case, you would have to manually re-select the relevant tool each time.

Why did you pick my first suggestion? Do you have any concerns with the other two?

**Comment by UliAbo** [comment]
Ah you're right! I mis-read your second one: "Remember the last active tool for each layer type, so that when you select a tile layer again, it also switches away from that Offset Tool back to what you last used on a tile layer." 
I think this one is better. I thought you meaned to remember the active tool for each layer (!), not layer type.
I will change my initial post.

**Comment by UliAbo** [comment]
Oh today in the morning I had again a major flaw in my map design because I didn't notice that I obviously selected a LayerFolder by accident... And then I clicked somewhere with the d*** auto-selected (which was noticed by myself) "Offset Layers" Tool, which shifted some parts of the Map I noticed later. Aand I wasted quite some time to find those little shiftings and undo. Sorry, this is really so annoying (and I don't understand where this is anyway helpful for someone). I wish I could disable this behavior somewhere. 

Sorry for my rant. More constructive: Obviously when switching between an Object and a Tile Layer, the last used Tool for each Layer type is saved, which is nice. So with implementing your suggestion from last year, this hopefully could be at least mitigated? 

**--> "Remember the last active tool for each layer type, so that when you select a tile layer again, it also switches away from that Offset Tool back to what you last used on a tile layer."**

This already works! It would just need this little tweak that it ignores the Offset Tool only when previously the Offset Tool was auto (!) selected by selecting a Layer Group.

**Comment by bjorn** [comment]
Please see the commit message at f9e2527d0af0e70188e46f71cc71730fa674f7b5 for details of the change I ended up making. Since it is a bit of a risky change so short before release, I'd appreciate if it could be given some testing. Builds with this change will be available at https://github.com/mapeditor/tiled/actions/runs/1779165830.

**Comment by UliAbo** [comment]
@bjorn Thanks again for the fix. Today I made some tests with your mentioned version and it works fine for me! I switched through the different tools and layer types and it always switched back to the previous tool, that's an improvement. For having selected a group layer I would still prefer to have selected "no" tool, but I understand the UX logic you are following here. Keep up the great work!

**Comment by eishiya** [comment]
I don't think the new behaviour is working correctly. It works as expected if you're constantly switching layer types, but not if you're switching between layers of the same type. For example:

If have Stamp Brush selected, select a Tile Layer, select Eraser, and then select another Tile Layer, it'll go back to Stamp Brush instead of keeping Eraser selected.

If I select Eraser again and then select an Object Layer, and then go back to a Tile Layer, it'll remember that I had Eraser selected last time I was on a Tile Layer.

If I then select Stamp Brush and select another Tile Layer, it'll switch to Eraser, because that's what it memorised when I switched layer types, even though it should have kept Stamp Brush selected this time.

**Comment by bjorn** [comment]
@eishiya Thanks for saving the 1.8 release! Fixed pushed in 2e7b6901ca535bf84a4d49d248f3fbaa1572f2df.

**Comment by UliAbo** [comment]
Thanks @eishiya for the more solid tests you have done!
