### ISSUE TITLE
Custom properties on the project

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#2903]
It should probably be possible to set custom properties on the project, mostly for extension purposes.

Split off from #1665.

**Comment by elmm** [comment]
It would be nice to have some custom properties that are either not visible or not editable for a user. For example, in my case, I have my custom map format exporter/importer and I need to store some format-specific data for the loaded map to be able to save it properly. Now I'm using properties for this purpose but if it changed by a user it will break an export process. Also, it looks not nice when you have some staff that you shouldn't suppose to touch.

(It also can be some properties naming convention as well - e.g. properties starting with "__" not shown in the property tab).

PS: I tried to add custom fields to the TileMap object in JavaScript but it looks like the JavaScript wrapper around C++ Map object is not persistent and lives only while read/write is executed so that fields don't survive between calls.

**Comment by bjorn** [comment]
> It would be nice to have some custom properties that are either not visible or not editable for a user.

While project properties have now been implemented, this use-case isn't covered yet. However, in the meantime we have issue #3245 for tracking that feature.
