### ISSUE TITLE
Title not displayed for dialog boxes under MacOS

### ISSUE THREAD

**Issue by elmm** [mapeditor/tiled#2910]
tiled.alert, confirm don't show title under MacOS.

Platform: macOS Catalina 10.15.7
Editor: Version 1.4.2-50-g76796ffb (was the same behaviour with previous version, based on QT 5.12)

**Comment by bjorn** [comment]
This turned out to be pretty much a Qt feature, which [hides the message box titles on macOS](https://stackoverflow.com/questions/21904910/qmessageboxcritical-do-not-show-title-text) for conformance to Apple's HIG. However, in this case I think could be more helpful to show the title, so I'm applying the workaround.
