### ISSUE TITLE
export custom properties problem

### ISSUE THREAD

**Issue by lang233** [mapeditor/tiled#2938]
why export like this before:
 "properties":
                    {
                     "animated":true,
                     "sprite":"portal",
                    },

but now is this format:
"properties":[
                        {
                         "name":"animated",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"sprite",
                         "type":"string",
                         "value":"portal"
                        },]

how can i use tiled 1.4 export prevenient format

**Comment by bjorn** [comment]
You can use the previous format by disabling the `json` plugin and enabling the `json1` plugin.

The format changed because the new format is easier to parse, especially when using type annotations to automate JSON parsing as it possible in C# for example. It also allowed bringing in the `type` attribute, which previously had to be kind of awkwardly stored alongside the `properties` as the `propertytypes` member.

I understand the previous approach makes it easier to look up properties directly from the JSON structure, but I would recommend writing a small converting function based on the new format if necessary, rather than using the old format.
