### ISSUE TITLE
World Tool: Adding Map often end up offsetted

### ISSUE THREAD

**Issue by meniku** [mapeditor/tiled#2970]
On a map that isn't part of a loaded world: When using the World Tool to add it to an opened world, it might end up in slightly offset positions, so it doesn't properly fit into the grid ( see screenshot below )

![offset](https://user-images.githubusercontent.com/785551/103095912-862e6b00-4602-11eb-9753-e18f258875f6.jpg)

I did not encounter that issue when using the "Add another map" action. So it's not a big deal, but maybe the other action should be disabled or fixed

**Comment by bjorn** [comment]
Hmm, the various actions work differently as follows:

* The "Add another map to the current world" tool bar action positions the map such that its origin is in the center of the map view.
* The "Add a Map to World ..." context menu action positions the map with its origin at the clicked location.
* The "Add <current map> to <world>" tool bar and context menu actions position the map with its origin in the top-right of the last map added to the world.

It appears the last action is not working for you as expected. Could you provide some more details, or possibly upload some files so I could reproduce this problem? Asking because it's working fine in my tests.

**Comment by meniku** [comment]
[sample.zip](https://github.com/mapeditor/tiled/files/5808790/sample.zip)

**Comment by bjorn** [comment]
Turns out this was an off-by-one on the X axis since `QRect::topRight` is, for historical reasons, not exactly where you'd expect:

![image](https://user-images.githubusercontent.com/531764/104470034-84304a00-55b9-11eb-940b-575eb62519cf.png)

I just hadn't noticed is while testing.

Another issue stems from the fact that all move operations on the map appear to be rounding the _offset_ to whole tiles, but if the original position of a map is not aligned to the grid, this makes it essentially impossible to put it at an aligned position. I think I should change it to snap the target position instead.

**Comment by bjorn** [comment]
Thanks for bringing this up! The fix will be available in the next development snapshot and the Tiled 1.5 release.

To work around the issue in Tiled 1.4, move your maps with the arrow keys to ensure they are each aligned to the grid.
