### ISSUE TITLE
Crash when selecting object and switching between opened maps

### ISSUE THREAD

**Issue by ZxMapleLiu** [mapeditor/tiled#2978]
When opened maps have object layers and objects with same name, switching between opened maps after editing one of the objects without deselect the object can cause the app crash.

**Comment by bjorn** [comment]
Hmm, I'm having trouble reproducing this issue. Does this crash reproduce consistently for you? Can you provide more detailed instructions to reproduce the problem?

What I tried:

* On Linux, I opened a map, and used "Save As" to save a copy of it, so that it would have object layers and objects with the same name.
* Reopened the file with the original file name.
* Selected one of the objects, resized and moved it, and did not deselect it.
* Switched between the maps by either clicking the tabs or using Alt+Left/Right shortcuts.

**Comment by bjorn** [comment]
Closing this since I'd need more info to be able to find out what needs fixing.
