### ISSUE TITLE
Allow Tiled to open ".tiled-project" files

### ISSUE THREAD

**Issue by RichardJECooke** [mapeditor/tiled#3000]
Bug in version 2021.02.15.

To reproduce:
- Open Tiled
- Save project as `v.tiled-project`
- Close Tiled and reopen it
- File - Open -  `v.tiled-project`

Expected result: Project opens

Actual result: "Unrecognised file format"

**Comment by bjorn** [comment]
The expected action to open a project is _Project > Open Project_, so it's not really a bug, but I guess it would be a good idea to consider switching to the project in this case as well.

**Comment by RichardJECooke** [comment]
Oh lol, I'm a new user. Figured out maps and layers, but I didn't expect File options to be there. Thanks.

**Comment by UliAbo** [comment]
> Bug in version 2021.02.15.
> 
> To reproduce:
> 
> * Open Tiled
> * Save project as `v.tiled-project`
> * Close Tiled and reopen it
> * File - Open -  `v.tiled-project`
> 
> Expected result: Project opens
> 
> Actual result: "Unrecognised file format"

I would also love to see this implemented!

**Comment by bjorn** [comment]
> I'm quite a newbie to GitHub. Is there a function how to express my "thumbs up" for such a feature, so that Bjorn knows which features are most wanted by us Users? :-)

The comment works because it gives me a notification, but as a downside it also sends a notification to everybody else, who would rather only get notified when the issue is resolved. So, I'd recommend to use the smiley button at the top of the original request to give a "thumbs up" and to additionally ping me on Discord to notify me about your interest.
