### ISSUE TITLE
Tiled shows a warning when copying to clipboard outside of Tiled

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3010]
Whenever I copy something to the clipboard outside of Tiled (text in my browser and on Discord, pixel data in my art programs...), Tiled shows a warning in the console and issues panel: `qt.qpa.mime: Retrying to obtain clipboard.`

~~This seems to only happen when *multiple instances* of Tiled are open, I have not seen it happen when only one instance is open. The warning seems to show up in the instance that I interacted with most recently.~~ It happens when a single instance is open too.

![image](https://user-images.githubusercontent.com/70545646/112194791-a0ff8400-8bdf-11eb-9209-e4d7b4bbb7b6.png)

I noticed this first on Tiled 1.5.0 Win x64 version, but it's possible this is an older issue that I simply didn't run into because I don't often have multiple instances of Tiled open.

**Comment by bjorn** [comment]
Seems like a harmless warning that might indeed happen as a result of two applications simultaneously trying to access the clipboard. The problem to address is mostly that it is visible.

**Comment by Jchinjm** [comment]
Hello, @OsamahAnsari and I would like to implement a fix for this bug.

**Comment by bjorn** [comment]
@Jchinjm You're welcome to look into it! Let us know if you have any questions regarding the necessary development setup. The best place to ask for help is likely the [Tiled Discord server](https://discord.gg/39wbTv7).

**Comment by bjorn** [comment]
Note that this warning is the result of the fix for [QTBUG-27097](https://bugreports.qt.io/browse/QTBUG-27097). Potentially it was simply a bad idea to redirect all Qt messages to the Console (implemented in 4d1f3eb23b4759383d3b35e9df86ef33f4ac1881). It was primarily done to make "script errors that happen while calling functions connected to signals" visible, since I didn't find any other way to capture them.
