### ISSUE TITLE
Composite tilesets don't automatically reload

### ISSUE THREAD

**Issue by Xeyler** [mapeditor/tiled#3019]
Composite tilesets (tilesets of tilemaps; or metatiles) were introduced via PR https://github.com/mapeditor/tiled/pull/2708.

Because of this PR, `.tmx` tilemap files can now act as source images for `.tsx` tileset files. Typically, tilesets will automatically reload when their source file changes. This automatic reloading is facilitated by QFileSystemWatcher [here](https://github.com/mapeditor/tiled/blob/master/src/libtiled/filesystemwatcher.cpp).

However, when a tileset is automatically reloaded, Tiled doesn't actually modify the `.tsx` file or any other `.tmx` file which depends on it(and really, it probably shouldn't). Therefore, QFileSystemWatcher is watching for a file which contains a reference to another file to change when it's actually just the referenced source file that's changing.

Hopefully what I've tried to explain makes sense. Otherwise, I'd be happy to try to explain it another way and/or record a screencap of the behavior.

As an aside, Tiled is a really cool piece of software.

**Comment by bjorn** [comment]
Thanks @Xeyler, I'm happy to hear Tiled suits your needs and that you've found the feature of using maps as tilesets useful!

Indeed I should look into making the reloading work somehow also when a map file is kind of hiding the reference to potentially multiple image files. I'll close this issue since we already had #2743 open about that.
