### ISSUE TITLE
Resizing a map in a world does not update the size stored in the world immediately

### ISSUE THREAD

**Issue by m-r-hunt** [mapeditor/tiled#3020]
Simple enough to reproduce: Resize a map that's part of a world using Map>Resize Map. The world file will not be updated straight away, and cannot be saved manually. You have to do something else like moving a map to resave the world and get the updated size. 

This was a problem for me as I am reading the map sizes from the world file in my game to determine which map the player is in (without actually loading up the maps to check their size that way).

**Comment by bjorn** [comment]
I've decided to address this for the upcoming Tiled 1.8.3, but it was rather more involved than I had expected. The main problem is that a change of map size is not at all a change to the world, in terms of undo commands. And whether a world needs saving was solely based on whether any changes were made directly to the world.

It's essentially duplicate information of course, but since I can see it being useful I've implemented a workaround that marks a world as "modified" when a map size is changed (either due to resizing it, or by changing its tile size). This will then allow the world to be saved, and triggers a prompt when you try to close Tiled without saving the world.

Other implementation difficulties came about due to another bug (cda4fcbc4391870a5338e126147e178f05957c86) and due to `WorldDocument` instances getting created on-demand (I've decided to not make them on-demand anymore).

The whole approach to worlds should probably get a redesign at some point, but for now I just hope I didn't introduce any new issues. :-)
