### ISSUE TITLE
Tiled Commands: add %tileid substitute variables

### ISSUE THREAD

**Issue by pouwelsjochem** [mapeditor/tiled#3026]
It would be great if Tiled would be able to pass along the selected tile(s) as a substitute variable when editing a tileset.
Since you can select multiple tiles, this variable could then contain a comma/space separated list of tileids. The name of the tileset is already included in the `%mapfile` variable.

As an example of possible use case: I would use this `%tileid` variable to add commands which echo which maps have referenced to this tile, or even remove references to these tiles from all maps in the project.

**Comment by bjorn** [comment]
While this sounds easy enough to add and I have no problem adding it, note that the functionality you're after can already be achieved by writing a JavaScript extension. The JavaScript API has access to the selected tiles (at least, in the Tilesets view when having a map open... currently not in the Tileset editor) and can [launch external processes](https://doc.mapeditor.org/en/latest/reference/scripting/#process).

To be able to entirely perform this action in a JavaScript extension, the following is still missing:

- [ ] Access selected tiles in the tileset editor
- [ ] Get list of maps in project or list of files in a directory

**Comment by bjorn** [comment]
Btw, variable substitution is done here:

https://github.com/mapeditor/tiled/blob/123c324332250eebeca921ff644c99737cb1b69f/src/tiled/command.cpp#L67-L100

Maybe you're interested in trying to patch this in? You'd need to add a special case for `qobject_cast<TilesetDocument*>(document)` to access the `TilesetDocument::selectedTiles`.

**Comment by pouwelsjochem** [comment]
I would definitely prefer the Tiled Command approach since I use it for a bunch of other utilities (I connected it to my own Java application which is able to modify every Map/Tileset in my project). So all I would need is the name of the Tileset (already available) and the `%tileid`

Patching it does sound simple enough, I'd just have to make some time to set up the project properly and make it running locally in the near future.

**Comment by bjorn** [comment]
@pouwelsjochem Alright, for now I've saved you the trouble of setting up a Tiled development environment and added the `%tileid` variable. I could really recommend setting up this environment for when you need any other tweaks though! :-)

Also, it turned out you can actually access the selected tiles in JavaScript using `tiled.activeAsset.selectedTiles`, so in fact this action is already possible by using that to build up the comma-separated list of tile IDs and then using `Process` to launch your tool. You may want to look into this because it's in the end more powerful than the custom commands system.
