### ISSUE TITLE
Object selection preview is hard to see, especially with name labels

### ISSUE THREAD

**Issue by rgrams** [mapeditor/tiled#3036]
Tiled 1.6.0, Linux Mint 20.1

**Problem:**
The new selection preview is often hard to see.

**Solution?:**
1. I think the preview outline should draw _above_ object name labels, like the normal selection outline. 
2. I think the contrast should be increased, so it's easier to see on top of Rectangle objects, or light-colored, rectangular Tile objects. I think it could have the same black & white contrast as the real selection outline (the difference being the preview version would not be moving).

A somewhat extreme example:
![tiled_selection_preview_outline](https://user-images.githubusercontent.com/11370192/115969368-9d2a8e80-a50a-11eb-9e71-bb7faa54136e.gif)
_Note: I did try it with the normal light theme as well but it was pretty much the same to me._

**Comment by bjorn** [comment]
Thanks for the feedback! I've put the outlines above the labels now, and increased their opacity from 50% to 60%, because I'd still like to keep them more distinct from the active selection outlines than having the animation as the only difference.

The hover outline, along with the transparent version of the hovered object, are now also above the labels.

**Comment by rgrams** [comment]
Sounds good, thanks a lot!
