### ISSUE TITLE
Feature focus layer

### ISSUE THREAD

**Issue by jonnytest1** [mapeditor/tiled#3052]
on double cliking a layer the editor should jump to the first tile in the layer

**Comment by bjorn** [comment]
Hmm, that doesn't seem like a generally useful action to me. Also, double-clicking current triggers layer rename, so it could trip some people up that are trying to rename their layer if it jumps somewhere.

Of course, I understand this behavior would be helpful in your project. Unfortunately at the moment it's not possible to customize the double-click behavior without changing the code and compiling your own version of Tiled (which is of course still an option). However, I made Tiled scriptable precisely because of such specific needs. So you could for example write a [scripted action](https://doc.mapeditor.org/en/stable/reference/scripting/#script-registeraction) that finds the first tile in the current layer (`tiled.activeAsset.currentLayer`) and centers it in the view, and then you could set a shortcut on this action.
