### ISSUE TITLE
New feature: add tile as a object template

### ISSUE THREAD

**Issue by 564398053** [mapeditor/tiled#3062]
For a tiled map，if we have 100 or more objects witch has the same type.  We have to assign property/name/type again and again. If an object have 10 properties, we have to do it 1000 times!
10 vs 1000 is a huge difference.
 
Need a feature like add tile as a Object template, and we can give the properties to `template`. 
When put a template object to map, the added object has a property like `tID` to refer the template object.

It's more convenient to use templates to create object with plenty of properties (such as hp/attack/defense/gold/exp/description etc.)

I hope you can consider it as a new feature if other people also need it. : D
 
![image](https://user-images.githubusercontent.com/11308289/118196386-829b6380-b47f-11eb-83b7-b8e207340a48.png)

**Comment by 564398053** [comment]
If it's a stupid idea,  just close this issue. :D

**Comment by 564398053** [comment]
So far, I use another json file to record these properties. it's still fine without this feature.
![image](https://user-images.githubusercontent.com/11308289/118199376-8d58f700-b485-11eb-8ac8-4cd1abb69494.png)

**Comment by bjorn** [comment]
I'm not sure I fully understand the request, because I think Tiled already has some features that could help you:

* You can set properties [on the tiles in a tileset](https://doc.mapeditor.org/en/stable/manual/custom-properties/#tile-property-inheritance). This way, when you place those tiles as objects on a map, they will show those properties in the Properties view (in gray, indicating they're inherited).
* If it's always the same set of properties, you can additionally define properties on a predefined in the [Object Types Editor](https://doc.mapeditor.org/en/stable/manual/custom-properties/#predefining-properties). These types can then be associated with your tiles, so the properties are also readily available there.
* Finally, there are also [object templates](https://doc.mapeditor.org/en/stable/manual/using-templates/), which can also be templates for tile objects. If you use templates it is currently a bit harder to select the right one, since it is done in the Project view and there is only a preview of the currently selected template, so no gallery like the Tileset view. But on the upside the templates can be named and you can easily change the graphic it uses later and it would apply to all instances.

I hope that helps, let me know if you looked into these features and whether there is still something missing for your use-case.

**Comment by 564398053** [comment]
Thansk!

I've found the feature exactly I wan't. 
By set the `type` property to a tile. While I put a tile to map, the property is automatically added in map . 

![image](https://user-images.githubusercontent.com/11308289/118372947-ab8a3880-b5e6-11eb-83aa-2e474d76ee8b.png)
