### ISSUE TITLE
Tileset background colour should affect Tile Collision Editor

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3070]
The Tile Collision Editor currently always uses the theme's default panel background colour, even if the Tileset has a background colour set. One of the main uses for the Tileset background colour is to make tiles more visible regardless of theme colour, and it's a shame to be missing that in the Tile Collision Editor, where readability and precision are often very important.

I think the background colour of the Tile Collision Editor should be the Tileset background colour, and it should display the theme's default colour only when no background colour is set.

**Comment by Lyqst** [comment]
Hi! I would like to work on this.

**Comment by bjorn** [comment]
@Lyqst You're welcome to write a patch for this. The background color in the Tile Collision Editor should be based on the `Map` instance that is created in `TileCollisionDock::setTile`, in the line:
```
auto map = std::make_unique<Map>(mapParameters);
```
Since we have the `Tile*`, we can set the background color of this map based on the background color of the tileset.

For bonus points, you can connect to `tilesetChanged` in `TileCollisionDock::setTilesetDocument`, adding a function that would update the map's background color when needed and afterwards call:
```
emit mDummyMapDocument->changed(MapChangeEvent(Map::BackgroundColorProperty));
```
To get the background color of the map view in the Tile Collision Editor to update.

**Comment by bjorn** [comment]
@Lyqst As far as I can see that should have worked. Can you open a pull request with your change, so that I can see the full code and easily try it out?
