### ISSUE TITLE
No option for Lua Export

### ISSUE THREAD

**Issue by CMDR-Piboy314** [mapeditor/tiled#3084]
### No option for .lua export

I'm working on a game with Lua & Love2D and decided to try out tiled map editor for my levels. I'm on a Raspberry Pi 4B and am running Raspberry Pi OS (Formerly Raspbian) When I try to export my map there are only two options:

1. All Files (*)
2. Tiled map files (*.tmx, *.xml)

I'm trying to follow [this](https://youtu.be/XfIDHUyLpQ0) tutorial.

Any help would be appreciated

NOTE: I am running version 1.2.1

Screenshot of tiled (in case it matters):
![image](https://user-images.githubusercontent.com/83137373/122648309-af820c80-d0f6-11eb-82f7-e222eb2e4615.png)

**Comment by bjorn** [comment]
Sounds like a duplicate of #2973, see also the discussion at https://github.com/mapeditor/tiled/issues/2973#issuecomment-758901771. This packaging issue seems to be already fixed in newer versions, including the 1.4.2 version shipping in Ubuntu 20.10. If upgrading is not an option you can try the same workaround as mentioned there (adding appropriate symlink).

**Comment by CMDR-Piboy314** [comment]
Thanks! I updated to the snap version and it works like a charm.
