### ISSUE TITLE
Tiled should not override firstgids when saving maps that cannot find tilesets

### ISSUE THREAD

**Issue by jestarray** [mapeditor/tiled#3106]
So if you save a tilemap that cannot locate the tileset files it will reset all the gids of the ones it couldn't find to 1. It should just keep all the firstgids the same instead because otherwise its surprising and erases userdata unexpectedly

```
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/tsd\/deco_gore.json"
        }, 
        {
         "firstgid":1,
         "source":"..\/tsd\/deco_trash.json"
        }, ]
        ```

**Comment by eishiya** [comment]
OP implied this, but to make it explicit: Not only are the tileset `firstgid`s lost, the `gid`s of all the Tiles are also lost. Essentially, *all* tile data is lost.

There is plenty of valid work (setting properties, dealing with objects, etc) that can be done on a map without having the tilesets, so the ability to preserve tile data like this would be very helpful for people working in teams. ~~And for helping people on the forum/Discord who don't send all their data.~~

Perhaps Tiled could forbid the adding of tilesets to maps that have broken tileset references (since the `firstgid` for those cannot be calculated), or perhaps new tilesets should be forced to the front of the list (since the `firstgid`s can then be old `firstgid` + known tile counts).

Tiled may not have complete data for missing tilesets, but it certainly has enough to preserve it. It would require implementing some plaecholder tilesets for dealing with missing tilesets, so that the missing tiles aren't just set to `null` (which is probably what causes them to be written out as all empty when the file is saved).

**Comment by bjorn** [comment]
Hmm, thanks for bringing up this issue! I wonder if this was always broken or whether it was a regression at some point... Opening and saving a map with broken tileset references should definitely not cause all the tile data to get lost, so I'll have a look at what can be done about this.

Indeed that core of the issue is that the dummy tileset object that is created in place of the missing one, doesn't have any tiles. So when its firstgid is calculated, it's the same as the previous tileset. We could probably derive the implied tile count from the firstgids in the loaded map, and use that when calculating the firstgids on saving.

**Comment by bjorn** [comment]
I think I found a nice and small fix to this issue. A typical "one-liner" with huge commit message. :-)
