### ISSUE TITLE
Snapshots after the v1.5 release not available on main site

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [mapeditor/tiled#3108]
I use snapshots to run the program due to it not requiring an installer (I sometimes run this program on library computers via PortableApps, and updating the app this way, and not downloading another .paf.exe (which are at least 120MB; insane considering this app uses less than 70MB of space when installed) and uninstalling and reinstalling the PortableApp, is more efficient). As a result, I have been on v1.5 for quite a while (I keep versions the same on PC and flash drive), and the program gives me update nags in the bottom right corner, but I cannot download the versions, as they are not in snapshot form, and thus there is no .7z file of the newest releases. Can this be fixed? I would very much like to use the newest features if at all possible (bugfixes as well), so either start providing snapshots again, or make standalone .7z versions of the app available when doing releases.

**Comment by M1CR0H4CK3R** [comment]
Found your AppVeyor for builds, so I now have the latest build: https://ci.appveyor.com/project/bjorn/tiled/builds/39935945/job/e3mqtqr041v2jc6u/artifacts
But you should include this file within the Releases section.

**Comment by M1CR0H4CK3R** [comment]
![image](https://user-images.githubusercontent.com/1993598/126239693-7e856bbc-98b9-4bb2-afe4-a61439c41ac4.png)
No more update nags!

**Comment by bjorn** [comment]
Apart from AppVeyor there are builds available for each commit and pull request based on the ["Build Packages" workflow](https://github.com/mapeditor/tiled/actions/workflows/packages.yml) on GitHub. If you're logged in, you can find build artifacts for each build there, including zip files for Windows. 

But this is obviously too hidden and also inaccessible due to requiring GitHub login, so adding a portable (7-)zip package to the Releases section is definitely be a good idea. This is covered by issue #366.

> and the program gives me update nags in the bottom right corner

Note that you can disable the "update nags" in the Preferences, though I wouldn't recommend it of course. :-)
