### ISSUE TITLE
Feature request: find out all layers on a tile

### ISSUE THREAD

**Issue by blindpirate** [mapeditor/tiled#3120]
### Context

I have a complex map with hundreds of layers. I often want to find out which layers are on a tile so I can select the layer and edit it. Right now I have to click "visible" button on all possible layers to confirm they're on the target tile. Is there a better way? If not, I really would like to have such feature: when you click a tile with "find layers" mode, all related layers are highlighted in Layers window so I can know which layers forms this tile.

Thanks!

**Comment by bjorn** [comment]
At the moment, the only quick action available is "Select Layer of Top-Most Tile Under Cursor", which is Ctrl + Right Click.

You can use Ctrl + Shift + Right Click to add the layer to the selected layers rather than only selecting that layer, but there is currently no way to select all layers with content below the mouse. I wonder if we should add another modifier for this (potentially Alt is available), or whether it would make sense to change the behavior of Shift as such.

**Comment by blindpirate** [comment]
This is very useful. You save my life.

**Comment by bjorn** [comment]
Ah great, so your use-case is covered? I'd still value your opinion about changing the Shift modifier or about adding a "Select All Layers Used at Position" action in general.

**Comment by blindpirate** [comment]
Yes, "Ctrl + Shift + Right Click" totally covers my usecase. The only opinion is to add this one into documentation (or it's already there? https://doc.mapeditor.org/en/stable/manual/keyboard-shortcuts/ )

**Comment by bjorn** [comment]
> P.S. Can we this one into documentation? https://doc.mapeditor.org/en/stable/manual/keyboard-shortcuts/ I was trying to create a PR but the `manual.po` seems too complex...

Right, that's the wrong file (it is only related to translating the manual). I've just made a number of corrections and additions in 2e9e70e001303e50eaf5426c682b5942224d4f8b, including documenting this shortcut.
