### ISSUE TITLE
 Tiled 1.7.2. Mac / Tilesets Properties using right mouse

### ISSUE THREAD

**Issue by stanleyseow** [mapeditor/tiled#3137]
In Tiled 1.7.2 , in the tilesets properties, I can only use right mouse click to select the tile and the **Show Grid** also shows up ..

Tried this in Windows version, this is normal with left mouse button, right mouse will display the "Show Grid" menu

**Comment by bjorn** [comment]
Sounds like a macOS specific issue. So you mean, regular left click on macOS is not working for you to select a tile? I'm not entirely sure what you mean with "tilesets properties".

**Comment by stanleyseow** [comment]
Hi, 

When check on Edit tileset, I cannot use the left mouse to select the tile ( only works on right mouse ) and also the "Show Grid" came out ( when right mouse is click )

Usually need to select a tile (left mouse) to Add Property to that tile... 

Mac OS 10.14.6
Tiled 1.7.2

**Comment by bjorn** [comment]
Oh, I think this is not a bug but more like a usability issue. Could it be that you have the "Terrain Sets" mode enabled? Because in that case, left click is for assigning terrains to the tiles rather than selecting the tiles. You could close the "Terrain Sets" view or toggle off the respective button on the tool bar to exit that mode, in which case left click will select tiles as usual.

**Comment by stanleyseow** [comment]
Ah, yes. I hv the Terrain Set enabled..
Closing it fixed this...
