### ISSUE TITLE
Add some way to find out the Tiled extensions folder from a script.js

### ISSUE THREAD

**Issue by sdsnatcher** [mapeditor/tiled#3139]
The Tiled extensions folder varies from system to system (Win, Lin, Mac etc). Please add some way to allow a plugin script to know where this folder is located, to load resources from there.

I'm working on a script to load/save a specific binary format for a 8bit game. It can be easily adapted for most 8bit user-level binary formats.

Since the tileSet used for such games is hardcoded and won't be changed, the best place for the user to install it (tsx+png files) will be together with the .js file, inside the Tiled extension folder. 

When a stage is loaded, the script get the path to the Tiled extension folder concatenate with the filename.tsx and feed it to the tiled.open() method, like this:

` 
dirName = tiled.getExtensionsFolder();
var tileset =  tiled.open( dirName+"that8bitGameTiles.tsx" );
var fileLevel = new BinaryFile(fileName, BinaryFile.ReadOnly);

...Proceed to load the tile map data...
`

**Comment by bjorn** [comment]
I think there are two existing features that should help you:

* You can try using the `ext:` prefix to refer to your tileset, for example `ext:that8bitGameTiles.tsx`. This should work, because the `ext:` magic prefix makes it look for files in all extension folders (and in the folder of each installed extension, if they're in a subdirectory).

* Alternatively, a bit less magic, there's the [`__filename`](https://doc.mapeditor.org/en/stable/reference/scripting/#api-reference) variable, which is set to the file name of each script when it is evaluated. You could use [`FileInfo.path`](https://www.mapeditor.org/docs/scripting/interfaces/fileinfo.html#path) to extract the path from there.

That said, I also see little against exposing the global extensions folder as a property of the `tiled` module. But you may still want to prefer using one of the above methods, since there is also the project-specific extension folder, which is preferred over the global folder when the script is specific to a certain project.

**Comment by sdsnatcher** [comment]
Thank you so much for the tips!

The "ext:" prefix worked like a charm, FileInfo.path will be very helpful too, since I was trying to use path.dirname and it didn't work.
