### ISSUE TITLE
[Bug]`removeObjectAt` & `removeObject` can't work correctly

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3149]
when I want to remove all objects of a layer , the two ways both work 
```
    for (let i = 0; i < layer.objects.length; i++) {
        layer.removeObjectAt(i)
    }

    for (let i = 0; i < layer.objects.length; i++){
        const obj = layer.objects[i]
        layer.removeObject(obj)
    }

```
There always still leave some objects in the layer. (just remove some of all)

**Comment by bjorn** [comment]
I guess you closed this because you found a solution? Indeed neither of those loops is going to work correctly, because the `removeObject` and `removeObjectAt` functions are going to modify the `layer.objects` array you're iterating. One solution would be to iterate it backwards. Another solutoin is to make a copy of the array first.

I could add a `Map.removeObjects` function to make removal of multiple objects easier and more efficient.

**Comment by bjorn** [comment]
I've added `Map.removeObjects` to make it easier to remove multiple objects at once.
