### ISSUE TITLE
Bug: alert twice about "replace file"

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3152]
When I save a file (use TextFile. write) , there are 2 alert dialog-windows. (on macOS 11)

![image](https://user-images.githubusercontent.com/288367/136141765-43707f26-bd59-46c4-baea-f2ebfffc90d5.png)
![image](https://user-images.githubusercontent.com/288367/136141779-8b3d7df5-7dc2-4f3c-aa95-b655e1080869.png)

**Comment by bjorn** [comment]
> It looks like an issue with Qt on macOS 11

Alright, this is [QTBUG-39791](https://bugreports.qt.io/browse/QTBUG-39791), which is not going to be fixed due to limitations in the API provided by macOS:

> "It looks like this is unfortunately a WontFix: The native class we are using (NSSavePanel) does not have an option which corresponds to DontConfirmOverwrite. Qt contains a workaround for this, which no longer works on recent macOS versions.
> 
> A possible replacement is to use Qt's file dialog (set the DontUseNativeDialog flag)"

I think we can resolve this issue by not using the `QFileDialog::DontConfirmOverwrite` flag and possibly only checking any additional files (which is pretty rare) for overwrite after the dialog, and possibly only when the chosen file doesn't exist since if the user confirmed to overwrite that one, they likely also want to overwrite the other files. This change probably doesn't even need to be platform-specific.
