### ISSUE TITLE
Support compression and decompression in JavaScript API

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#3153]
Something like `tiled.compress` and `tiled.decompress`, to make it easier to support zlib, gzip or zstd compression in JS extensions.

See https://github.com/mapeditor/tiled-extensions/issues/11.

**Comment by eishiya** [comment]
Bumping for interest.

I recently wrote a custom map format that lets me define "sprites" made out of multiple tiles that my game can then use similarly to regular sprites, and it stores the layer data similarly to Tiled's map JSON format. It would be nice to support the same compression options without including bulky libraries in the script. For now, I can only conveniently support "csv" (native JSON array) and uncompressed base64 encoding.

**Comment by eishiya** [comment]
After spending some quality time with Qt's base64 methods, `Qt.btoa()` and `Qt.atob()`, I've realised they're either broken or their approach is fundamentally broken: they appear to work on UTF-8 strings that cannot accurately represent binary data: https://bugreports.qt.io/browse/QTBUG-71511

Because of this, I think Tiled should provide its own base64 encode/decode methods that can work with binary data (using e.g. ArrayBuffer), and Tiled's compress/decompress should probably also not use strings, to avoid encoding issues with JavaScript strings.

**Comment by bjorn** [comment]
> After spending some quality time with Qt's base64 encoder `Qt.btoa()`, I've realised it's either bugged or their approach is fundamentally broken: it works on UTF-8 strings that cannot accurately represent binary data: https://bugreports.qt.io/browse/QTBUG-71511

That's rather surprising and quite unfortunate. Hopefully the new `tiled.toBase64` and `tiled.fromBase64` added by #3593 will work better.
