### ISSUE TITLE
Unset Color property should not be `#000000`

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3154]
I think should be "" or null  ,  Otherwise it's hard to tell user : it's `"Unset"` or set `"#000000"`  .

**Comment by bjorn** [comment]
Since Tiled 1.11, you can compare with the return value of `tiled.color("invalid")`, for example:
```js
if (tiled.activeAsset.backgroundColor == tiled.color("invalid"))
    // no background color is set
    ;
```
I've tested this and the comparison is `true` for unset colors and `false` when the color is set to black.

I think that provides a good enough solution for now, but I will keep this issue open as a reminder to document this [here](https://www.mapeditor.org/docs/scripting/interfaces/color.html).
