### ISSUE TITLE
'Show Tile Animations' option should reset animations when un-checked

### ISSUE THREAD

**Issue by rgrams** [mapeditor/tiled#3178]
_Using Tiled 1.7.2, Linux_

(This is the same request as #1288 but for a different reason.)

When you disable playing tile animations, the animated tiles should reset to their original tile, instead of just pausing the animation.

 * Probably this should be a configurable option, as I can imagine people wanting to only pause the animations to test them.
 * And/Or there should be a hotkey-able action for resetting animations.
    * Maybe just doing this would be best. Instead of "Show Tile Animations", have two actions: "Pause/Resume Tile Animations", & "Play/Stop Tile Animations".

#### Problems with the Current Behavior:
 * In the Map view or the Tile Collision Editor, you will generally see a random frame instead of the original tile.
 * The _only_ way to see the original one is to carefully play the animation and pause it on just the right frame, which is a real hassle.
 * I use the Tile Collision Editor as a zoomed-in preview of the animation, while zooming the Tileset viewport so I can select all the frames. Like this, if the animation is paused on a frame other than the first one, it is impossible to see the original tile in the Tile Collision Editor, since if you select the original one (that has the animation), it shows the current animated frame instead of the original one.
 * This would particularly be a problem with animations that will be non-looping in game. Let's say you have a one-off fire or light or water splash effect object that you want to place on a map based on how it looks. Presumably you don't want to place it based on some random frame near the end when it's almost gone. So you have to carefully pause-resume to get back to the beginning.

---
Side Note: If the state of tile animations could be controlled with the scripting API, then this could be solved by a user extension. I didn't see anything in the API docs, but it's quite possible that I missed something.

**Comment by bjorn** [comment]
> When you disable playing tile animations, the animated tiles should reset to their original tile, instead of just pausing the animation.

This has already been implemented on `master` (e0a9b977c188ffdfb63bf0041372664b5e061ef8), so it will do that in Tiled 1.8 once released, or if you need it now you can download a development build [here](https://github.com/mapeditor/tiled/actions/workflows/packages.yml?query=branch%3Amaster). I've also changed the "Export as Image" functionality to always use the first frame, instead of essentially a random one when animation playback is enabled.

> Side Note: If the state of tile animations could be controlled with the scripting API, then this could be solved by a user extension. I didn't see anything in the API docs, but it's quite possible that I missed something.

The scripting API can trigger the action to pause/unpause animation playback and can change the list of frames for a given tile, but it otherwise has no control over the playback. Let me know whether the changes I've made don't already cover your needs!

**Comment by rgrams** [comment]
Ah! Perfect! That should cover it, thanks!
