### ISSUE TITLE
Out of date translation files can be removed?

### ISSUE THREAD

**Issue by idbrii** [mapeditor/tiled#3180]
I just updated from 0.9.0 to 1.7.2 and noticed that three translation files were unchanged. My guess is that these are no longer valid:

- translations/tiled_lv.qm (Latvian)
- translations/tiled_pt_BR.qm (Brazilian Portuguese)
- translations/tiled_zh.qm (Chinese, but not sure if Traditional or Simplified)

There were updated files for similar languages, so maybe the translation effort moved there:

- translations/qt_zh_CN.qm
- translations/qt_zh_TW.qm
- translations/tiled_pt.qm

Not really a problem for me, but I thought you might want to know. Feel free to close if you'd rather keep these files around.

**Comment by bjorn** [comment]
> I just updated from 0.9.0 to 1.7.2

That's quite a jump!

> * translations/tiled_pt_BR.qm (Brazilian Portuguese)
> * translations/tiled_zh.qm (Chinese, but not sure if Traditional or Simplified)

If you check https://github.com/mapeditor/tiled/tree/master/translations, you'll see that `tiled_pt_BR` and `tiled_zh` no longer exist, which is why those `qm` files did not get updated. Files from previous builds are not automatically cleaned up though, you'll need to do that locally.

> * translations/tiled_lv.qm (Latvian)

And whereas `tiled_lv` is still represented, it is currently [disabled explicitly](https://github.com/mapeditor/tiled/blob/2b1f3c6b1d906380b02cdb3f5e68aa6a16ddc302/translations/translations.qbs#L11) because it is so incomplete that it would not be useful to ship it.
