### ISSUE TITLE
JS scripting: Signal connect/disconnect mechanism doesn't allow extra arguments

### ISSUE THREAD

**Issue by user72356** [mapeditor/tiled#3187]
I've been experimenting with the upcoming regionEdited signal that you've been working on, and it's a game changer for Tiled extensions. However, I've discovered a weakness in the way that callbacks are connected/disconnected, and it's becoming a blocking issue. 

In order to connect a callback to a function, one must provide the function object to .connect(), and then the exact same object to .disconnect(). The problem is when I try to pass an extra argument to the callback method, the only way is to do it is via either an anonymous function ```.connect(function () { mycallback(myarg) })``` or an arrow function ```.connect(() => mycallback(myarg))```.

This works fine to connect the callback, but then the disconnect function can never find the method since it has no signature (anonymous). 

This is problematic, as the only way to share variables with callbacks is to resort to ugly globals, with an extra mechanism to prevent concurrency issues if other maps are opened by the user. This gets ugly fast. I would like to propose a mechanism to connect/disconnect the callbacks, that would rely on an arbitrary index instead. ```.connect(42, () => mycallback(myarg))``` and then ```.disconnect(42)```. Alternatively, the .connect function could take care of generating the id and returning the generated id, so it can be disconnected later.

Thank you for your attention and help!

**Comment by bjorn** [comment]
I think I understand the issue, but I could use a more concrete use-case and possibly some example code for what you're trying to achieve. In particular, on which occasion do you want to disconnect from the signal?

It will be problematic to change the actual `connect` and `disconnect` functions, since [this is a feature provided by Qt](https://doc.qt.io/qt-5/qtqml-syntax-signals.html#connecting-signals-to-methods-and-signals).

> Alternatively, the .connect function could take care of generating the id and returning the generated id, so it can be disconnected later.

When it would work for you if the `connect` function would return an ID that can be passed to `disconnect` later, then I'm not sure I understand the problem. Why would you then not, instead of storing that ID, store the function you passed into `connect`, so you can later use it to disconnect from the signal? Like this for example:
```js
function connectToRegionEdited(asset) {
    if (!asset.isTileMap)
        return;

    tiled.log("connecting to regionEdited and regionChanged for asset " + asset.fileName);

    let onEdited = (region, layer) => {
        tiled.log("regionEdited(" + region + ", " + layer + ") for asset " + asset.fileName);
        asset.regionEdited.disconnect(onEdited);
    }

    asset.regionEdited.connect(onEdited);
}

// Connect on asset opened and to already open assets
tiled.assetOpened.connect(connectToRegionEdited);
tiled.openAssets.forEach(connectToRegionEdited);
```
(of course the question still is, when would you like to disconnect, because at that point you'll need to have the `onEdited` function around)

**Comment by user72356** [comment]
Thank you for your answer. I'm writing a fairly complex extension that activates/deactivates a "special mode" that facilitates drawing walls in an isometric map. When the user activates the action (toggled ON via menu or shortcut), edits on the map are monitored and the walls are moved/grouped to different layers in real time, based on their position, etc. When the user is done drawing walls and deactivates the extension (toggled OFF via menu or shortcut), the extension performs some final actions and shuts off, until the next time it's triggered.

I distilled the important bits in the script below. What happens is the regionEdited signal gets turned on, but never shuts off, because it doesn't appear to recognize that I'm passing it the same object. 

Currently I've solved the issue by never shutting off the signal, and by saving the status of whether the extension is ON or OFF in a global variable. When the variable if false, I simply don't do anything if a region is edited.

```js
function HandleRegionEdited(region, layer, myVars)
{
    tiled.log("Detected a change in the region.");

    tiled.log("myVars.testVar: " + myVars.testVar);
}

function HandleActionTriggered()
{
    tiled.log("Action triggered...");

    let map = tiled.activeAsset;
    if (map == null || !map.isTileMap)
    {
        return;
    }

    // Initialize a bunch of stuff, do some work and produce an object containing properties that
    // will be needed later in the HandleRegionEdited callback.
    let myVars = { testVar: "Hello World!" };

    // Saving the callback in a variable so that connect and disconnect both receive the same
    // object. It doesn't work, disconnect doesn't really disconnect the signal.
    let handleRegionEdited = (region, layer) => HandleRegionEdited(region, layer, myVars);

    if (action.checked)
    {
        tiled.log("...Activating special editor mode.");
        map.regionEdited.connect(handleRegionEdited);
    }
    else
    {
        tiled.log("...Deactivating special editor mode.");
        map.regionEdited.disconnect(handleRegionEdited);
    }
}

let action = tiled.registerAction("TestAction", HandleActionTriggered);
action.text = "Test Action";
action.checkable = true;

tiled.extendMenu("Map",
    [
        { action: "TestAction", before: "MapProperties" },
        { separator: true }
    ]);
```

**Comment by bjorn** [comment]
Right, you are creating a different callback each time `HandleActionTriggered` is called, so that disconnect call will never work, whereas in my example where I did `disconnect(onEdited)`, it was the same function object that was used in the connect call. I think you could fix it by just moving the `handleRegionEdited` variable to the global scope, and only assign to it within the `if (action.checked)` condition.

> It works except when the user drags and drop the stamp tool across the map. It only produces 1 undo state, but several regionEdited signals.

Hmm, yeah that's quite a hack you did there with triggering the undo action, and it is the result of the undo commands getting merged together. Unfortunately, I don't think it's easy to delay the `regionEdited` signal until the last change, since it is new undo commands that are getting merged into the first one and at the time of emitting `regionEdited` we simply don't know if it is the last one for this sequence of edits. Changing this would affect each tool, which will then need to trigger a kind of "done" signal, generally when the user releases the mouse.

A potential workaround for your issue would be to use the `Asset.macro` function to _always_ create an undo command, after you went through the undo/redo process to find out what changed, since adding anything on the undo stack will prevent further edits from merging into the same undo command. It's not nice, but it could do the trick right now.

It would be nice if we could find a way to not need the whole undo/redo things at all, though. I'm thinking that there could be a signal that is emitted right before an edit is made, such that the scripts could make changes to the edit before it is applied.

**Comment by bjorn** [comment]
> Yep! My mistake for recreating a new callback variable every time. My code had changed so much since then that I didn't watch this closely enough before posting this issue. So that solves it for me.

That's great!

> About the new signal, that would be awesome. Let me know if you would like me to create a new issue to track that one.

Sure, please create a new issue, I'll close this one then!
