### ISSUE TITLE
Re-change return value of flagsAt

### ISSUE THREAD

**Issue by tumatanquang** [mapeditor/tiled#3188]
Hi, I'm a Java game developer, I just changed to Tiled recently.
I am using the `flagsAt` function to get the direction transform value of the layers on the map.
After comparing the return value of `flagsAt` with [Java's Sprite](https://docs.oracle.com/javame/config/cldc/ref-impl/midp2.0/jsr118/javax/microedition/lcdui/game/Sprite.html#TRANS_NONE) directional value constant, I noticed a problem. Here is a table comparing the `flagsAt` value with the Java Sprite constant value:
![Transform](https://user-images.githubusercontent.com/20223064/143696539-3c809687-b6b5-461c-b223-f48a1f17c03b.png)
As can be seen, the values of `TRANS_MIRROR_ROT180` and `TRANS_MIRROR` from `flagsAt` are swapping places.
So is it possible to fix the value of these two constants in the next version?
Thanks.

**Comment by eishiya** [comment]
The actual values used by Tiled should be irrelevant, they're just an implementation detail. You could be explicitly outputting the values that you need in your script as needed. If the values happen to correspond in some instances, that's great, but you should not be relying on this. Output the values you need explicitly.

Also, consider that Tiled outputs the logical OR of its flags rather than arbitrary values. If it changes the values of the horizontal and vertical flags like you're suggesting, that will change some of the other values in your chart.

The Java system seems to be incompatible with Tiled's and just happens to line up, because the Java system works with rotations, while Tiled works with flips. I think it would be very strange and would break a lot of things to change the two to match.

**Comment by bjorn** [comment]
Right, those values are meant to be used with the constants like `Tile.FlippedHorizontally`, etc. (see https://www.mapeditor.org/docs/scripting/classes/tile.html#flippedantidiagonally) to check which flags are set, and can then be mapped onto the right Java constant. I think @eishiya is correct in that if I would make those initial values for the flipped states match, you would see a mismatch in some of the other values instead.
