### ISSUE TITLE
Prompt saves only when necessary

### ISSUE THREAD

**Issue by jestarray** [mapeditor/tiled#3194]
At the moment if I use the selection tools, e. Select Same Tile, Magic Wand selection or Rectangle selection, etc just to highlight a selection of tiles and don't do anything with it, it registers as a file change despite not doing anything to change any contents of the map.

**Comment by eishiya** [comment]
The reason for this is that anything that goes on the Undo stack also marks the document as modified.

I'd also like to see a distinction between actions that modify the map data, and those that do not. It might not be very important, but it can be confusing when a map is marked as changed when you don't remember making any changes.

**Comment by bjorn** [comment]
I've made a PR with a change that should fix this. Inspecting the `QUndoStack` was a little more involved that I had expected... I hope I got the indexes right now. I'd appreciate if somebody could give the resulting autobuilds some testing when they're done. :-)

**Comment by eishiya** [comment]
Gave it a look, tried every kind of selection tool and mode I could think of and none of them marked the document as dirty. Tried the wand in every selection mode, the rectangular select in every selection mode, select all, select none, invert selection, select same tile.

Tried many other map tools to check that they still mark as dirty. This was of course not an exhaustive test, but I haven't found issues so far. I'll keep using this build and report back if I notice anything weird.

I did have a crash when undoing some non-selection changes, but I suspect this is the same crashing I occasionally get that's probably related to scripts and stale references to nonexistent layers rather than directly related to this change.

**Comment by bjorn** [comment]
> I did have a crash when undoing some non-selection changes, but I suspect this is the same crashing I occasionally get that's probably related to scripts and stale references to nonexistent layers rather than directly related to this change.

Alright, well that's still a little worrying of course. Thanks for the test drive!
