### ISSUE TITLE
Tiled Object not inheriting Type from Tileset type

### ISSUE THREAD

**Issue by jestarray** [mapeditor/tiled#3198]
![image](https://user-images.githubusercontent.com/34615798/144700072-88931136-e4e1-4d5d-8ee0-918d3cf28e7d.png)

When setting the `Type` in the `Tileset` and placing it down in an `Object Layer` using `Insert Tile`, it shows that the object created is of the greyed out type as show in the picture above, however this is not written in the output file:

```
"objects":[ {
                         "gid":4332,
                         "height":32,
                         "id":3,
                         "name":"",
                         "rotation":0,
                         "type":"", //Type field is not set despite showing in the UI it  is of said type
                         "visible":true,
                         "width":32,
                         "x":0,
                         "y":0
                        }],
```
It makes sense to save writing unnecessary data for custom properties if they haven't changed from the defaults since there can be many of them, but the type property from the tileset should be merged into that of the instantiated object. When I was parsing my games map files, it was surprising it wasn't there, so to work around this I would have to then take the .gid field of this object, search the tileset data, and then get the type from there

**Comment by eishiya** [comment]
Copying my thoughts from Discord here:

Tile types and object types are *entirely independent* and in many cases one *does not* want them to match. For example, a Tile might only be there as a cosmetic aid with its type only relevant when it's in a Tile Layer, or an object of a given type might get *additional* properties or values from its tile (best done by pulling them from the tileset when parsing the map, to avoid redundant data).

Your specific use case is probably better handled by either pulling the data from the tileset at parse-time, or making a script to copy the data in Tiled. Sadly there's no good way to automate the latter yet, the Tiled scripting API doesn't have signals for the creation or modification of objects.

**Comment by rgrams** [comment]
If the exporter is always going to write the type field even if it's empty, then it makes sense that it would output the inherited value. Writing an empty string for an object that has a Type seems pretty misleading. I think the inherited value should be exported. Even if this is a special case just for the "Type" property.

From my viewpoint, the Type property seems specifically designed as the "first contact point" for custom game code to interpret the object or tile in a certain way, and so you would generally use it as an inherited property from the tileset and rarely override it. But that's just me.

**Comment by eishiya** [comment]
Your concept of types makes sense, but I don't think it should be enforced, as there are other ways to look at it too, as I mentioned. Typeless objects can still have properties and there's nothing stopping someone from using "no type" as a sort of generic object type, a plain data holder, and it's not uncommon to use Tile Objects to disambiguate similar objects, with those tiles still having their own types and different meanings when in Tile Layers. In your case, tile and object types can be conflated, but that doesn't mean they should be conflated for everyone. Let people use Tiled in the weird ways they want, it's designed with this sort of flexibility in mind.

However, it would be a good editor option to automatically set the Tile Object's type to the Tile's type when the object is created or when its tile is changed, since I imagine this is a fairly common use case for tile and object types. This can't even be effectively scripted currently since there aren't signals for object creation and changes.

**Comment by rgrams** [comment]
Your idea simply enforces people doing it the other way around. *shrug\* It's not any "better" or more flexible the current way, just different. The current way, you are _forced_ to check the tileset to get the inherited value (the value you see in the editor), if you flip it then you are only forced to check the tileset to know whether or not it's _different_ from the value it inherits. Tomatoes, tomatoes.

At any rate I don't see this changing, if only because of backwards compatibility. Maybe at some point there could be options for exporters, so they could support small changes like this without you having to rewrite the whole exporter for one tiny change.

You could use the `assetAboutToBeSaved` signal to copy the type from the tile to the object, right?

**Comment by eishiya** [comment]
I don't think it enforces it, since it still allows you to set those types. The only problem is that Tiled doesn't currently make it easy to do so, which is where scripting or a built-in option would help.

You are correct that `assetAboutToBeSaved` could be used, as could some other signals, but that's not very timely, and belated changes can be confusing.

**Comment by rgrams** [comment]
OK I tried using a script connected to [assetAboutToBeSaved](https://www.mapeditor.org/docs/scripting/modules/tiled.html#assetabouttobesaved) to directly set the inherited types so they export. On the surface it did work, but of course once you set the value on the object, from then on it doesn't inherit any updates if you change the type on the tile.

What _did_ work is this: 1) Set the inherited type on all objects, 2) trigger Export, and 3) reset any modified objects.
You'd probably want to hook this up to an action so you can trigger it manually instead of automatically doing it every time you save, but here's the code:
> Note: It's a bit primitive and doesn't handle layer groups, etc.

```javascript
let exportWithInheritedTypes = function(asset) {
	if (asset.isTileMap) {
		let objectsToReset = []

		// Copy inherited types from tiles to objects without type overrides set:
		for (let li = 0; li < asset.layerCount; li++) {
			let layer = asset.layerAt(li)
			if (layer.isObjectLayer) {
				for (const object of layer.objects) {
					if (!object.type && object.tile && object.tile.type) {
						console.log(object)
						objectsToReset.push(object)
						object.type = object.tile.type
					}
				}
			}
		}

		// Export:
		tiled.trigger("Export")

		// Reset types on any objects that were modified:
		for (object of objectsToReset) {
			object.type = null
		}
	}
}

tiled.assetAboutToBeSaved.connect(exportWithInheritedTypes)
```

**Comment by bjorn** [comment]
@jestarray @rgrams Hmm, this exactly what the "Resolve types and properties" export option is for:

![image](https://user-images.githubusercontent.com/531764/144824680-5838d720-1923-40a6-b12b-11c4947a2266.png)

> If the exporter is always going to write the Type field even if it's empty, then it makes sense that it would output the inherited value. Writing an empty string for an object that has a Type seems pretty misleading. I think the inherited value should be exported. Even if this is a special case just for the "Type" property.

Normally I would agree, but if we're writing out the inherited value, it will count as being overridden, so it will no longer change when the type of the tile is changed later on. An empty string is written out for backwards-compatibility reasons, since this was already done before the Type field for tiles was introduced. In general the JSON format has more such redundancy (including of values even if they're the default) than the TMX format, which I think wasn't such a good idea. Maybe we can get rid of this eventually.

**Comment by jestarray** [comment]
Oh I see, sorry I missed it.
