### ISSUE TITLE
"Select object on map" does not work in non-object layer properties

### ISSUE THREAD

**Issue by Yanrishatum** [mapeditor/tiled#3207]
Right now it's impossible to use "Select object on map" on layer properties that are not object layers. Confirmed on tile, group and image layers.

Reproduction:
1. Create an object
2. Create object reference property on the tile layer
3. Click "Select object on map"
4. Attempt to select an object

What happens: Currently active tool is activated
What is expected: Current tool is deactivated and user can select an object.

Tiled: 1.7.2, Win10.

**Comment by eishiya** [comment]
I wonder if this is related to how you can't select and use the Select Objects tool when you're not on an Object Layer, despite its functionality being something that should by all rights work from any layer, since it'll take you to the correct layer anyway. Tiled is a little *too* context-sensitive.

**Comment by bjorn** [comment]
Yeah, this behavior was inherited from `AbstractObjectTool`, but there is no reason to disable the `ObjectReferenceTool` when the current layer is not an object layer. Thanks for reporting the issue!
