### ISSUE TITLE
Minimap viewport is calculated wrong when a layer has an offset

### ISSUE THREAD

**Issue by krukai** [mapeditor/tiled#3211]
1. Create a map with a width of ~600 tiles /9000 pixels (16x16tiles)
2. Add an image layer using an HD wallpaper to make things easy.
3. Add another image using an HD wallpaper with an x offset of around 8000 pixels
4. Try to bring either image layer into view using the minimap. 

You will notice that the wallpaper with the offset will be displayed close to the center of the minimap. To actually bring it into view however, you have to click the right far end of the minimap.

This seems to be related to the actual layer size, which equals the map size regardless of the image layer's image dimensions. By adding an offset, the whole canvas is effectively extended by that offset.

While I think this is the expected behavior for tile layers, image layers should actually be the size of the image they display. Regardless, for calculating the viewport position, the actual layer size has to be taken into account, rather than its bounding box.

**Comment by eishiya** [comment]
I think the sizing of image layers is a separate and unrelated issue to this, since this happens even when all the layers involved are tile layers. That image layers should perhaps always have the size of the image they contain could probably be its own issue, but I'm sure even with that changed, *this* issue would still occur.

Some examples of this issue in action:
View centered on a non-offset wallpaper, but with another offset wallpaper present. Notice how in the minimap, it's not centered or even scaled right.
![image](https://user-images.githubusercontent.com/70545646/146391058-5c97adfe-d15c-4bd7-a4f8-d9ceec9cd214.png)

View centered on the offset wallpaper, it's just way off:
![image](https://user-images.githubusercontent.com/70545646/146391249-7590688c-b03d-4721-9123-be47ceb47009.png)

View centered on the wallpaper without any offset layers, looks as I'd have expected the first image to look:
![image](https://user-images.githubusercontent.com/70545646/146391335-73c1f967-2682-4718-87bb-f3bf20f07acf.png)
