### ISSUE TITLE
Embed maps and map updates.

### ISSUE THREAD

**Issue by willianholtz** [mapeditor/tiled#3225]
When we create a map, in a .json format, and want to embed some tileset in it, the tileset is always duplicated, often confusing the user which would be correct to use.

I use this function myself to transfer my maps to Gdevelop. And I also have a .tmx, with all collisions working. I often need to edit my base .txm to change some things. And whenever it is re-embedded in .json it duplicates the Tileset.

https://user-images.githubusercontent.com/23488207/147412628-d89329b7-f558-472c-9d2b-cf296bcfb983.mp4

The problem is: When we embed a tileset in a map, that tileset becomes unique for that map, making that if we have to change any collision or object type, we have to do it in all maps already created.

https://user-images.githubusercontent.com/23488207/147412930-3bdd97d0-5abf-4dc3-b353-60dd32110a8f.mp4

It would be interesting if Tiled could have this tileset built in, but at the same time it has a shortcut pointed to the main base, so user could just edit his base .tmx, and all maps used in that tileset would be updated.

**Comment by eishiya** [comment]
Tiled just displays all tilesets that are currently open or which are used by open maps. Just because you see a tileset in the Tilesets panel doesn't mean it's part of your map. Tiled could definitely do a better job disambiguating which tilesets are which though.

It sounds like you should be using external tilesets, since you want changes to propagate. If you *have* to use embedded tilesets, consider using external tilesets for your main map files, but exporting copies with embedded tilesets. This can be automated in the export settings in Edit > Preferences, you can set tilesets to be embedded, and you can even set Tiled to automatically export the maps whenever you save them.

**Comment by willianholtz** [comment]
I think you did not understand me. But I will try to explain.

If I have a pattern already started in some tileset, like collisions, animations, object types, etc., when I embed it in a map, that tileset belongs to that map, correct?

But if there are several maps with the same tileset built in, and I need to change something on the maps like collisions, animations etc, I am forced to edit each tileset embedded in the maps one by one or redo all maps with the new tileset coordinates

When we embed a tileset in a map, that tileset becomes unique for that map. In other words, it's no use having a tileset all ready with collisions, animations and types of objects if from the moment I embed it in the map, future updates must be done one by one.

**Comment by eishiya** [comment]
I think I understand you, and again, it sounds like you should not be using embedded tilesets.

**Comment by bjorn** [comment]
> When we create a map, in a .json format, and want to embed some tileset in it, the tileset is always duplicated, often confusing the user which would be correct to use.
> 
> I use this function myself to transfer my maps to Gdevelop. And I also have a .tmx, with all collisions working. I often need to edit my base .tmx to change some things. And whenever it is re-embedded in .json it duplicates the Tileset.

So, GDevelop needs the tileset to be embedded in the JSON file? In this case, the recommendation is like @eishiya pointed out, to use external tilesets in your .tmx files (so, they refer to .tsx files), and then enable the "Embed tilesets" export option, which will make the tilesets embedded only in the JSON files you export for GDevelop.

This way, any change to your tilesets immediately apply to all your maps. Of course, if you want to see the changes in all the exported JSON maps, each map that references the changed tileset will need to be re-exported. But you can automate this step, for example by using a script that invokes Tiled like this for each of your maps:
```
tiled --export-map --embed-tilesets map.tmx map.json
```
This could be automated using a `Makefile`, for example like:
```makefile
maps: \
	map_1.json \
	map_2.json

%.json : %.tmx
	tiled --export-map --embed-tilesets $< $@
```
(since the dependencies on the .tsx files are not encoded here, `make` should be invoked like `make --always-make`)
