### ISSUE TITLE
Can't select object

### ISSUE THREAD

**Issue by blindpirate** [mapeditor/tiled#3234]
Hi, thanks for the awesome tool. Today I found I can't select some objects in Tiled after I made some changes. You can see in the recording that some objects are selectable, some are not.

I'm using Tiled 1.7.2 on macOS 11.3.1

https://user-images.githubusercontent.com/12689835/149255423-67e2c092-c167-4bd9-a12f-d75c5339b12c.mp4

Steps to reproduce:

- `git clone https://github.com/ByteLegend/ByteLegend`
- `cd ByteLegend`
- `git checkout animation`
- Open `resources/raw/maps/JavaIsland/JavaIsland.json` in Tiled
- Try to select objects in `Missions` layer.

If you try the same file on `master` branch, everything works fine.

Note: I made some changes to `JavaIsland.json` with automation tool, i.e. modify the JSON outside of Tiled. I'm not sure that matters.

**Comment by eishiya** [comment]
Cloning your entire repo isn't required to replicate this bug. Just downloading and opening the one JSON file from the "animation" branch works fine.
https://raw.githubusercontent.com/ByteLegend/ByteLegend/animation/resources/raw/maps/JavaIsland/JavaIsland.json

I think the problem might've been your automation tools. These objects have `"polygon":[]` in them, which shouldn't normally happen. Rectangle objects don't have a `polygon` element at all. Deleting these empty `polygon` properties in the JSON causes the objects to become selectable normally. I'm guessing Tiled can't select them because it sees they're polygons (because they have a `polygon`) and tries to select based on cursor intersection with that polygon, but there's nothing to intersect with.

**Comment by bjorn** [comment]
> It _is_ weird that Tiled doesn't raise a warning or anything about this, and just draws a rectangle as normal. Seems like a mismatch between selection logic and display logic.

Thank you for taking a look at this, @eishiya! You're completely right, the presence of a `gid` property and a `polygon` property creates an ambiguity that isn't being resolved by the loader. It just creates an object with its shape set to "Polygon" but still having the tile reference.

Normally tile objects use "Rectangle" as their shape, but because of special handling compared to actual rectangle objects, some of the code just checks if there's a tile set on the object. Introducing a separate "shape" value for tile objects would be one way of making sure the behavior is consistent.

**Comment by blindpirate** [comment]
Thanks @eishiya you saved my day. Much appreciated!
