### ISSUE TITLE
Auto-adjusting tile references when a tileset has grown doesn't update tile types and properties

### ISSUE THREAD

**Issue by albertvaka** [mapeditor/tiled#3236]
### Bug description

When Tiled detects that a tileset image has changed size, it offers the option to update all the references to it to reflect the new tile IDs.

However, if tiles in the spritesheet had types and/or properties defined, they remain assigned to the old tile IDs they were assigned to previously, which after the re-enumeration is now incorrect.

### Steps to reproduce:
1. Create a small tileset with 2x2 tiles:
![spritesheet](https://user-images.githubusercontent.com/980842/149601884-1426f96c-799f-47df-b99a-d38d553d781a.png)
 
2. Add a type to the first tile of the second row (id=2).
![Screenshot 2022-01-15 01 43 36](https://user-images.githubusercontent.com/980842/149602129-bf1a303b-0965-4d5e-a733-8a28545f3150.png)

3. Resize the tileset image to be 4x2 tiles:
![spritesheet](https://user-images.githubusercontent.com/980842/149602135-1597555d-7230-4c87-abe2-684110e85830.png)

4. When prompted in Tiled, accept to auto-update the tile references.
![image](https://user-images.githubusercontent.com/980842/149602158-2b007067-84e6-4a9c-b2cd-55ec6f6b0f96.png)

5. Check that the tile you previously given the property is now tile id=4, but the type is still assigned to tile id=2.
![image](https://user-images.githubusercontent.com/980842/149602197-b3c781a0-c2fb-4ed5-8a09-d3a8dcc40b90.png)

**Comment by eishiya** [comment]
Nitpick: The wording of the prompt is correct, it fixes *references*. Properties assigned to tiles are not references xP

I think this should probably have its own prompt that would show up if any tiles had properties or types set, since it's a separate thing from updating maps, and since sometimes it's more desirable to delete the existing properties and clear the types, such as when the number of columns changes because the tile size is changed, rather than because the image changed, or when the image is replaced entirely.

Two prompts in a row would be annoying, but I remember there being talk of removing the tile reference prompt in favour of a menu item to reassign map IDs based on old/new tileset sizes, so that users can run it at their convenience and rather than being given one chance, potentially messing up any maps that weren't open at the time. There's also been talk of making a new spritesheet-like tileset type as the default, which would maintain tile IDs even when the image is resized, which would make these reference fixes unnecessary.

**Comment by albertvaka** [comment]
Hi! Thanks for reviewing this 😄 Two prompts might be annoying indeed, but we could reword the current one and add checkboxes for the different updates that can be performed at once. That seems way less work than the editor to assign arbitrary IDs, so even if that's going to happen long-term we might want to start with the prompt changes. Wdyt?

**Comment by bjorn** [comment]
> However, if tiles in the spritesheet had types and/or properties defined, they remain assigned to the old tile IDs they were assigned to previously, which after the re-enumeration is now incorrect.

Hmm, I see I forgot the type, but the properties should get adjusted. The related code is at https://github.com/mapeditor/tiled/blob/master/src/tiled/adjusttileindexes.cpp#L176.

And yeah, actually it adjusts references and tileset data, but the whole approach is not ideal.

**Comment by albertvaka** [comment]
You are totally right: properties, probabilities and the other tile fields are already updated. That means most of the code needed is already there. I will try to open a PR that adds the missing type update.
