### ISSUE TITLE
Request: Support .mjs scripts

### ISSUE THREAD

**Issue by user72356** [mapeditor/tiled#3261]
According to the Qt docs at https://doc.qt.io/qt-5/qtqml-javascript-imports.html, Qt supports importing .js and .mjs Javascript files. In the Qt world, .mjs files are basically the same as .js, but they can import/export modules, which .js files can't. I maintain an extension that is almost 2,000 lines and looking to break things down in several files/modules. The only way (other than using a JS bundler) is to save the modules in .mjs files. Unfortunately it seems like Tiled only looks for .js files and not .mjs files in the extension folder. I think this would be an easy change and would allow publishing modular extensions without messing with antiquated bundlers. Thank you for considering it!

**Comment by bjorn** [comment]
I had tried loading modules as well in the past, and I hadn't gotten it to work. But now carefully reading this documentation again, I noticed that it says that importing modules only works _from .mjs files_. And since I was evaluating JavaScript using `QJSEngine::evaluate`, Qt would never have been aware that the script came from a module.

So, I've made a patch that uses the `QJSEngine::importModule` function, added in Qt 5.12, when encountering .mjs files. And indeed loading modules from there appears to work!

So, starting with Tiled 1.8, it will be possible to write and distribute extensions as .mjs files, and then you can also use the import and export mechanism to write modular code. :-)

**Comment by user72356** [comment]
Thank you, it really helped my life.

**Comment by bjorn** [comment]
@user72356 Yeah, I think it'll help many people!

Also be aware that I had to make [some additional changes](https://github.com/mapeditor/tiled/commit/8ebab81ec61ccf39ff9b7f817d2cb6b48306397f), mainly to get loading error reporting to work also for modules.
