### ISSUE TITLE
Unintuitive project creation workflow

### ISSUE THREAD

**Issue by Sygmei** [mapeditor/tiled#3279]
Tiled Project creation workflow is confusing and goes against the usual workflow we can see in other softwares.
Usually, here are the actions possible for a project on other softwares : 
- Create an empty project
- Open an existing project
- Save a project

The absence of a "Create project" button makes things confusing.
Also, when you are already working on a Project, the "Close project" is hidden in the "Project" menu instead of the "File" one where you can find the "Open project" button (making things even more confusing).
Usually, when a user wants to work on another project, it will create another project, the software will close the previous one with a save confirmation popup and re-open the newly created project.
On Tiled however, you have to close your current project, it will fallback on the default project where you can save it as a new project.

Would it be possible to have this "Create project" button that will make things much less confusing for newcomers ?

**Comment by bjorn** [comment]
Thanks for creating an issue about this! Indeed, I will try to change things such that there isn't a default project, and you can just do "New Project" to get started on a new one with an empty session.

**Comment by bjorn** [comment]
Alright, I've made the following changes:

* "Save Project As" has been replaced by "New Project"
* "Open Project" has been removed (since there was already "Open File or Project"
* "New Project", "Recent Projects" and "Close Project" are now moved to the "File" menu

![image](https://user-images.githubusercontent.com/531764/169081917-7dd1e132-2c51-4986-839c-a7eca0ba1166.png)

That should be a lot more intuitive. In addition though, I should avoid certain things that are only saved in the project from being modified when no project is loaded, like the Project Properties, Project Folders and Property Types.
