### ISSUE TITLE
Deleting a selection causes the selection itself to go away

### ISSUE THREAD

**Issue by Macksaur** [mapeditor/tiled#3281]
### Problem

I am trying to delete a complex shape from a map and refill it with a different brush. However when I press delete to remove the underlying tiles the selection itself is also lost and I have to duplicate the work of selecting the complex shape.

### Goal

To be able to fill a selection after it has been deleted.

**Comment by bjorn** [comment]
Hmm, maybe the selection should only be removed when you Cut, and not when you Delete? I think the logic behind removing it on Cut was to make for a more comfortable Cut + Paste workflow to move things around, where you otherwise would have to manually get rid of the selection.

**Comment by bjorn** [comment]
Note that to fill a selection, you generally do not have to delete it first. When using the Bucket Fill tool, you can hold Shift to fill it, regardless of its contents.

**Comment by eishiya** [comment]
I think the current behaviour is best, as most of the time that's what's needed. It just happens to be very annoying in those few scenarios where it's not. It's also consistent with other editors.

Since Tiled supports Shift+Fill and deleting from multiple layers at once, there is even less need to keep the selection after deleting than there is in many other programs.

I can think of one scenario where it's still useful: when you want to clear a selection and then paint in part of it, while obeying the selection edges. I think being able to use a larger eraser or being able to Paint/Fill with the empty tile would be a better fix for this than changing the Delete behaviour.

**Comment by bjorn** [comment]
> It's also consistent with other editors.

Which ones did you try? I thought the same, but when I tried pressing Delete in GIMP 2.10, I noticed it actually does not remove the selection.
