### ISSUE TITLE
When an object is rotated it changes sorting order

### ISSUE THREAD

**Issue by Macksaur** [mapeditor/tiled#3286]
### Problem

When I rotate an object that is beneath another object, it jumps in front making the higher object unclickable (or rather difficult; you have to use the objects window and guess etc). I believe this is because sorting is done on the rotated "top left" corner of the object.

### Goal

Be able to rotate objects without them changing their sorting behaviours. Something like sorting around the untranslated top left coordinates?

**Comment by bjorn** [comment]
Yes, this happens because the default origin is not the center, but the object selection tool does rotate around the center, so the rotation affects the position, which affects the sorting order (by default, but not when you switch the Object Layer to manual ordering of objects).

> Be able to rotate objects without them changing their sorting behaviours. Something like sorting around the untranslated top left coordinates?

If this is about _tile objects_, then you can change their alignment to be their Center, in which case rotation should no longer affects their position. This is controlled through the Object Alignment setting on the _Tileset_.

Changing the alignment does change the position of already placed objects, so this may not be an option if you have a lot of maps already made. Though, in such a case the positions could be adjusted using a script to do the math.

**Comment by Macksaur** [comment]
> If this is about tile objects, then you can change their alignment to be their Center

Aha, I will experiment with this. Yes, I am using tile objects. Sorting on the transformed positions has left me in confusion.

**Comment by Macksaur** [comment]
Actually just changed this, and it still sorts on the transformed "top left" of the original tile.

**Comment by bjorn** [comment]
Another thing which I forgot to mention, is that you can set the "Drawing Order" property of the group layer to "Manual". That way the objects are not sorted and the order can only be changed manually, which also prevents rotation from changing their order.

I hope either changing the tile object alignment or disabling the automatic sorting will suit your needs.
