### ISSUE TITLE
Feature request: Have arrows in the "show more tilesets" view

### ISSUE THREAD

**Issue by Miepee** [mapeditor/tiled#3289]
**Is your feature request related to a problem?**
When having a smaller monitor and so many tilesets that they don't fit all on the screen, the "show more tilesets" view becomes less useful as you can only see the first few tilesets and have to navigate to the rest via the arrows in the general tileset view.
![image](https://user-images.githubusercontent.com/38186597/156888492-8e8f8321-a59b-49f0-9021-03a5085a5efb.png)

**Describe the solution you'd like**
Have arrows at the sides of the "show more tilesets" view, so you can navigate between those.

**Specs and version**
Windows 10, Tiled 1.8.2

**Comment by bjorn** [comment]
With this amount of tilesets, I think it would be preferable to have a selection menu similar to Ctrl+P (open file in project):

![image](https://user-images.githubusercontent.com/531764/156994653-6f962862-fd6a-472f-9879-6abf76271b25.png)


In any case, since the base issue is the same as #3173, I'll close this as a duplicate.
