### ISSUE TITLE
Various improvements and requests

### ISSUE THREAD

**Issue by willianholtz** [mapeditor/tiled#3317]
Hello, as we discussed on Discord. Here are some improvements and requests I've commented on.

**IDE improvements:**

- Save All: Currently we can access "Save All" only with a keyboard shortcut Ctrl+Shift+S, it would be interesting to have a button in the interface where the user can just click. The same goes for ".World" files

- ".World" files: This would be a big step for Tiled. When we create a ".World" file, instead of having to always add a map to it, it would be interesting and more dynamic to create a map already inside the ".World". 
And also always call all Tileset that are already being worked on. It doesn't make sense to do all the steps again as we are working on a single project. 

For example:

_We create a .world, add a map, add a tileset. This is the default when starting. Now if I want to add more maps inside the World project, I have to make a new map, save it first and only then can I add it to the project. The idea would be, if the user is already working on a ".World" file, automatically make this new map already integrated into the project._

**Saving files** 

In Tiled preferences we have "export options". In this session, it would be interesting to be able to choose what type of file Tiled would save by default: (.json, .TMX, .tmj, etc...)

This would be ideal for new maps as the default is .TMX. This helps to better integrate into the Engine that the user uses, as it will always save in that format.

**Tile collisions:**

Well, first I'm going to apologize if I'm talking nonsense, because I don't know the way that all engines work with the issue of collisions involving Tiled.

When we place collisions in our tilesets, we always have to do it one by one, placing the collision and defining its name (and type if used). But this is a lot of work depending on the size of the Tileset.

Ah first of all, I'm talking about the "Detect Bound Box", ok?

When using the "Bounding Box" it would be nice to be able to select all the Tiles that we want to insert the Collision into and be able to name them all at once. I know that with "Type" this can be done, but not with collisions!

![Bounding](https://user-images.githubusercontent.com/23488207/160828135-59bcc484-421e-4707-b2ec-666a1158e9e0.png)

That's all for now. But I wanted to highlight the .World issue more.
An improvement for this type of project would be most welcome!

**Comment by eishiya** [comment]
**Save All** is already available in the File menu along with the other save options, so the shortcut is not the only option. It sounds like you meant you want to also add it to the main toolbar?

**Worlds**: Auto-adding new maps to the loaded world, and creating maps at a particular location in the right (maybe with right-click -> "Create Map here"?) sounds like a nice feature.

**Saving**: Tiled already saves the last format used in the session. Setting a specific default instead of remembering the last chosen option, especially as a project option so it's shared by the whole team, seems pretty convenient though.
Just to note though: Export and Saving are separate things and are not intended to be interchangeable. Saving is for work files, Exporting is for production files. Unless your work files are also your production files (which doesn't seem to be the case, since you mentioned the Export options), the format of the work files usually doesn't matter, only the format of the exported production files matters. So, I think an option alongside "Repeat last export on save" to set a specific format would probably be better than a default save format option. So, a "Export on save" checkbox, and a drop-down next to it for the format, with "Last used" as one of the options.

**Tile collision**: You can already assign collision to many tiles at once. Select a bunch of tiles, draw/generate the collision on the one that's visible in the collision editor, then right-click it and you can copy it to selected tiles from there. This isn't a great UI and needs improvement, but the feature does exist. There is already an issue open to improve this: #1322

FWIW on GitHub, the norm is to have a separate issue for each separate feature request and only group very closely related ones together, so that the issues can be tracked closed independently. Lumping a whole bunch of stuff together like this makes it harder for developers to actually address your requests xP

**Comment by willianholtz** [comment]
> Save All is already available in the File menu along with the other save options, so the shortcut is not the only option. It sounds like you meant you want to also add it to the main toolbar?

Yes! 

> Worlds: Auto-adding new maps to the loaded world, and creating maps at a particular location in the right (maybe with right-click -> "Create Map here"?) sounds like a nice feature. 

Yes, too! 


> Saving: Tiled already saves the last format used in the session. Setting a specific default instead of remembering the last chosen option, especially as a project option so it's shared by the whole team, seems pretty convenient though.
Just to note though: Export and Saving are separate things and are not intended to be interchangeable. Saving is for work files, Exporting is for production files. Unless your work files are also your production files (which doesn't seem to be the case, since you mentioned the Export options), the format of the work files usually doesn't matter, only the format of the exported production files matters. So, I think an option alongside "Repeat last export on save" to set a specific format would probably be better than a default save format option. So, a "Export on save" checkbox, and a drop-down next to it for the format, with "Last used" as one of the options.

Yea! Saving and exporting are different, maybe I was wrong in the conditions, but currently every map that is created is saved in tmx default, if I just use json, it should have an option that I could set this extension as default

> Tile collision: You can already assign collision to many tiles at once. Select a bunch of tiles, draw/generate the collision on the one that's visible in the collision editor, then right-click it and you can copy it to selected tiles from there. This isn't a great UI and needs improvement, but the feature does exist. There is already an issue open to improve this: https://github.com/mapeditor/tiled/issues/1322

What I wanted to say is this! I didn't find the option you mentioned! Excuse!

https://user-images.githubusercontent.com/23488207/160912273-bd8ebf4f-2a4a-4f0b-bee1-a5d6e2544a1a.mp4


> FWIW on GitHub, the norm is to have a separate issue for each separate feature request and only group very closely related ones together, so that the issues can be tracked closed independently. Lumping a whole bunch of stuff together like this makes it harder for developers to actually address your requests xP

Well, that's why I decided to ask before on Discord about where to post to make requests. I understand that everything needed to be separated, but I didn't want to create several "issues" and maybe generate spam with it

**Comment by eishiya** [comment]
> Yea! Saving and exporting are different, maybe I was wrong in the conditions, but currently every map that is created is saved in tmx default, if I just use json, it should have an option that I could set this extension as default

Tiled already saves the last extension you used in the session, as I mentioned. So if you save a map as TMJ/JSON, the next time you go to save a map, it'll have that as the format selected by default.

**Comment by willianholtz** [comment]
It doesn't happen to me to keep the last type of extension saved!

Even a bug happens


https://user-images.githubusercontent.com/23488207/160915446-50b1b51e-2923-4a9c-ab19-b7cae454a265.mp4

**Comment by eishiya** [comment]
In your video, Tiled has correctly remembered the format (TMJ/JSON), just not the extension. As of Tiled 1.8 (I think?), TMJ is the name used for the Tiled JSON map format, as it's less ambiguous than the generic JSON.
