### ISSUE TITLE
Dutch language translation

### ISSUE THREAD

**Issue by lonely-unicorn** [mapeditor/tiled#3322]
Hi

Thanks for this fantastic tool!
I'm trying to translate the remaining strings of the Dutch language, but since this is my first time doing this, I'm having some problems.

I'm using windows and installed QT Linquist.
I'm using following version. Please confirm this version is up to date.

![afbeelding](https://user-images.githubusercontent.com/101529915/162070527-bce606c4-3b33-4a90-9cae-322a96bd77b8.png)

I downloaded the file tiled_nl.ts and opened it in Linquist.

Now I have a question, see screenshot.

![afbeelding](https://user-images.githubusercontent.com/101529915/162071175-39d9d0b2-afb3-4c7f-bb06-2bed616bf0ae.png)

Is it correct I only need to translate the "!" and "?" indicated strings? All green checkmarks are already correct?

Thx

**Comment by lonely-unicorn** [comment]
See screenshot please

![afbeelding](https://user-images.githubusercontent.com/101529915/162073249-151110fd-3d67-421f-a75a-7e591e444a3d.png)


- Another problem. What does the warning at the bottom mean? Because original string doesn't have those characters.
- what is the singular/plural thing there? This was present in the original translation file from github
- I can't make this string a green checkmark (I think because of the warning)

**Comment by bjorn** [comment]
Thank you so much for working on updating the Dutch translation! I used to update this translation myself, but I've often found it hard to find the right words because I don't generally use software in Dutch. I could have made a better effort to keep it updated though...

> I'm using following version. Please confirm this version is up to date.

The version doesn't matter much, but Qt Linguist 6.2.4 is the latest stable release, so it's perfect.

> Is it correct I only need to translate the "!" and "?" indicated strings? All green checkmarks are already correct?

Yes, a green checkmark means the string has not changed since its translation has been marked as "Done", so it will generally still be correct. You're of course free to see if you can improve on the translations, anyway.

> Another problem. What does the warning at the bottom mean? Because original string doesn't have those characters.

This is a string with plural forms, which are generally expected to include the number that the plural is based on somewhere in the string (like "Raise 3 Layers" or "Raise 1 Layer"). However, in many languages it is not necessary to include this number and still be grammatically correct, and personally I have sometimes preferred to leave the number out for simplicity (like "Drag Layer" and "Drag Layers"), since the exact amount is not very relevant.

It seems to me that the warning in Linguist is really a kind of false-positive, which in my opinion shouldn't trigger when the source string also left out the %n marker.

> * what is the singular/plural thing there? This was present in the original translation file from github

Since Dutch has two plural forms (one for single items, and another for 0 or multiple), there are two possible translations. One of them will be chosen, depending on the amount of items that are referenced.

> * I can't make this string a green checkmark (I think because of the warning)

In this case it is fine to ignore the warning and content with a yellow checkmark. :-)
