### ISSUE TITLE
Map selection rectangle in world is offset from map being selected

### ISSUE THREAD

**Issue by Arlorean** [mapeditor/tiled#3340]
When trying to select and move maps around the world, the selection rectangle for a map appears to be randomly offset from the actual map, making it very hard to place it when dragging.

Test files to reproduce bug with Tiled 1.8.4 on Windows:
[TiledMapWorldSelectionRectangleOffsetBug.zip](https://github.com/mapeditor/tiled/files/8556176/TiledMapWorldSelectionRectangleOffsetBug.zip)

**To Reproduce**
1. Download and unzip the test files.
2. Open the 'RobotsAndZombies.world' file in Tiled.
3. Hover over the first level on the left (with the orange rectangle)
4. The blue selection rectangle is offset vertically. You can't drag it without it changing the position of the map in strange ways (related to the selection rectangle).

**Expected behavior**
I would expect the selection rectangle to line up with the map and when dragging it for them to stay aligned and allow for small movements that don't break the world map.

**Video Showing Bug**
Here is a video that demonstrates the problem:
https://user-images.githubusercontent.com/1547800/165129478-a8bda9d8-c3e8-41bf-8107-a40e302aa95b.mp4

**Specifications:**
 - OS: Windows 11
 - Tiled Version: 1.8.4

**Comment by bjorn** [comment]
This bug only affects infinite maps, for which the code placing the selection rectangle does not correctly handle the map rectangle going into negative coordinate space. Since worlds define position + size for each map in the world, it's a little tricky how to handle infinite maps, which would need to essentially change position when they are expanded at the left or top sides.

One fix could be to add `boundsTop` and `boundsLeft` values to each map in the world, which define the point relative to `x` and `y` from which the `width` and `height` should be interpreted, so that expanding the map would not affect the `x` and `y` values, which would get very confusing.

The only purpose of storing these new values is actually to make the hidden `onlyShowAdjacentMaps` option work, since at runtime they can be derived from the loaded map. Some worlds are so large that we can't just load all maps, but this option does not play nicely with the World Tool currently.

**Comment by Arlorean** [comment]
Infinite Maps are the only way to go for us. When we start a map we're never completely sure how big it's going to be or in what direction it might sprawl. It would be really nice to get this working with the World maps too. Thanks for all the hard work @bjorn.

**Comment by Arlorean** [comment]
I've just tested the Windows x64 build and it all seems to work well now. Thanks for the quick fix @bjorn.
