### ISSUE TITLE
Changing a instanced Object's class' values should only affect the changed values.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3344]
**Describe the bug**
I know it's not a bug, but it definitely FEELS likes one :)
(Maybe someone can phrase a more precise / more correct headline for this thread?)

Example with two Objects Alpha and Beta:
- Alpha and Beta have both OrangeAmount and AppleAmount as two properties.
- Alpha has for both properties the value 3 and 4
- Beta has for both properties the value 55 and 66
- When I now select both Alpha and Beta and change their Oranges to 777, then I expect that both have this value only for Oranges which work fine. BUT the strange thing is, their AppleAmount also changed! And it changed both to either 3 and 4.
Nevertheless, this really feels buggy for me because when I only want to change Oranges to become the same value, Apple should not change? This issue doesn't occur when not using Classes / Enums.

**Expected behavior**
When I select two Objects sharing one Class, then I expect to only change the desired value without all other properties' value becoming the same.

**Comment by bjorn** [comment]
It is important to note that this only happens, when OrangeAmount and AppleAmount are _nested values_. If both are top-level properties of Alpha and Beta (which can still be based on the class of these objects), then the change happens only to the edited property. I do agree, that this is unintuitive and dangerous behavior (due to being unexpected and quite hidden).

Unfortunately it will be hard to address, since all the change events are currently applying only to top-level properties. When you change a nested property, this change is bubbling up towards the affected top-level property, and the resulting compound value is then applied to all selected objects.

To fix it, we will need to use the information about where this property is nested while applying the change to all selected objects. And in this, we'll also need to deal with the fact that some of the selected objects may not actually have the affected property (currently it would cause the compound value to get added at the top-level, but the new behavior should probably be to ignore that specific object then).

**Comment by bjorn** [comment]
While working on this I noticed that overridden values in nested classes were not displayed correctly, so I fixed that as well in 449f333accdf111a28130b417d22b49f7c003e97. I will aim for a Tiled 1.9.2 release soon.

**Comment by UliAbo** [comment]
@bjorn That's great! I'm looking forward to 1.9.2 :)
