### ISSUE TITLE
Stamp View Controls Broken in 1.8.4?

### ISSUE THREAD

**Issue by Graagh** [mapeditor/tiled#3362]
Stamp  View controls seems to be  broken in this version.  Add Variation is completely unresponsive from any context menu, by any means.  If you have a stamp selected and choose Add Stamp, it opens the current stamp name for renaming instead of creating a new one.  If the focus in in the Tileset View with multiple tiles selected, it will properly add a new stamp, but it will be a stamp map of the relative tile positions in the tileset, as if it were a map, rather than a list of selected tiles as variations.  If a single tile is selected, the stamp is created properly.

Currently this makes it impossible to add variations to a stamp or create a stamp with variations.  Unless I'm missing something that has changed - the last time I used it was 1.1.6, I think.

**To Reproduce**
1. Open an existing map with existing stamps and existing external tilesets.
2. Select multiple tiles in the Tileset View and then click Add Stamp in the Stamp View.  Stamp will receive the default name or can be renamed. 
3. In the map window with the stamp tool notice that the preview shows the stamp created as a region of the tileset image containing only the selected tiles, in their relative positions to each other
4. Select any stamp in Stamp View and click Add Stamp, or select Add Stamp from the right-click context menu.  Current stamp name is opened for editing rather than a new stamp being created.
5. Select any stamp in Stamp View and click Add Variation, or select Add Variation from the right-click context menu.  Nothing happens.

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.8.4
 - This is also the first version I've downloaded via itch.io, so it's the system installer from there.

**Comment by bjorn** [comment]
Hmm, it seems the context menu action "Add Variation" doesn't work, because apparently the right-click is already handled by the view and causes the clicked stamp to get selected, and it can't add itself as a variation. The "Add Variation" button on the toolbar does work, as long as you don't first click one of the existing stamps.

Since stamps are selected when clicked, and new stamps or stamp variations are saved based on the currently active stamp on the Stamp Brush, the workflow to add a variation is as follows:

* Select the stamp to which you'd like to add a variation.
* Capture the stamp you'd like to add, either from the map or the tileset.
* Click 'Add Variation'.

I'll have a look into the problem with the context menu, which currently doesn't work because opening it triggers the stamp selection.

**Comment by bjorn** [comment]
This may have been broken since d87100c7070756e7d2e4f1b88389789a6b29283f (Tiled 1.1.2), since `QAbstractItemView::pressed` appears to get submitted also for right-clicks, with unfortunately no obvious way to distinguish it from a left-click.
