### ISSUE TITLE
Save As Template not available for tile objects (macOS)

### ISSUE THREAD

**Issue by hotdogsoup-nl** [mapeditor/tiled#3371]
**Describe the bug**
Right click on a Tile object (in an object layer) should allow "Save As Template".

**To Reproduce**
1. add a tile object to any object group. 
2. right click on the tile. 

**Expected behavior**
The "Save As Template" option should be enabled.

**Tried to solve**
Even after relaunching the app or trying it on another map with a different tileset, in no way I can save a tile as a template. Other object types can be correctly saved as a template.

**Specifications:**
 - OS: macOS 12.3.1
 - Tiled Version: 1.8.5

**Comment by bjorn** [comment]
It's not enabled for tile objects that refer to a tile from an _embedded_ tileset, since template files are only allowed to refer to external tileset files. This is mentioned [in the documentation](https://doc.mapeditor.org/en/stable/manual/using-templates/#creating-templates).

Of course, it could be supported by embedding the tileset in the template file, but this is likely not what you want since a tileset can come with a large amount of meta-information, which would all get copied. Also, it would make it harder to share resources when multiple templates use the same tileset, but embedded in each of them.

**Comment by hotdogsoup-nl** [comment]
Thanks, sorry I missed that. With an external tileset it works correctly
