### ISSUE TITLE
UI is locked when a type name is already used

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3380]
**Describe the bug**

**To Reproduce**
1. edit property value
2. set the name of property 
3. if the name is used , there are 2 warning dialogs, but can't be closed
4. the TIled is lock , I can't do anything.

**Expected behavior**

**Media**
<img width="661" alt="image" src="https://user-images.githubusercontent.com/288367/172317334-89fb9a26-4e4e-4717-b986-981fe725a500.png">

**Specifications:**
 - OS: macOS 12.4
 - Tiled Version:  1.8.5

**Comment by bjorn** [comment]
Hmm, I can't reproduce this on Linux, so it might be a macOS-specific issue.

**Comment by bjorn** [comment]
Ah, I couldn't immediately reproduce this on macOS either, since it does not happen when renaming the type in the list nor when renaming using the name entry field and letting it lose focus. The only way I could trigger it, is by:

* changing the name in the entry field
* pressing Enter to apply the rename

There's probably two events happening in this case, I'll need to look into it.

Btw, if this happens it's not needed to restart Tiled. It seems the UI is only locked for mouse interaction, but you can still press Escape to close the dialogs.

**Comment by bjorn** [comment]
Workaround pushed as 3d17a66d378b87eb5d6349f6c93c3f8ed53d9522. Thanks for the report!
