### ISSUE TITLE
Tiled installed via snap on Ubuntu 22.04 fails with dependency error

### ISSUE THREAD

**Issue by ezacharyk** [mapeditor/tiled#3408]
**Describe the bug**
After installing Tiled via snap using 
`sudo snap install tiled`

And then trying to run tiled, I receive the following error:
`/snap/tiled/3991/usr/bin/tiled: error while loading shared libraries: libQt5Concurrent.so.5: cannot open shared object file: No such file or directory`

LibQT5Concurrent is already up to date:
`libqt5concurrent5 is already the newest version (5.15.3+dfsg-2).`

Running Tiled from the AppImage works after installing Fuse. Installing Tiled via Flatpak runs as expected.

**To Reproduce**
1. Install Tiled on Ubuntu 22.04 via snap
2. Run tiled via terminal
3. See error

**Expected behavior**
I expect Tiled to Run. 

**Specifications:**
 - OS: Ubuntu 22.04
 - Tiled Version: 1.9.0

**Comment by koehlf** [comment]
+1, same error here (Ubuntu 20.04.4 LTS)

**Comment by HollowedEmpire** [comment]
Likewise. Same problem, same situation and details.

**Comment by natethor** [comment]
+1.  Same issue for me, on PopOS 22.04, same details as original post.

**Comment by bjorn** [comment]
Well, I'm sorry for causing such a critical issue before leaving on holiday! The above change should fix it, but unfortunately the "edge" builds are current broken, so a working build will only be available once I get to fixing that, or at the upcoming 1.9.1 release.

**Comment by electronmage** [comment]
After installing Tiled, I can get the following by running

 snap info tiled

showing that it is installed.

`name: tiled
summary: Your free, easy to use and flexible tile map editor.
publisher: Thorbjørn Lindeijer (bjorn)
store-url: https://snapcraft.io/tiled
contact: https://discourse.mapeditor.org/
license: GPL-2.0
description: |
Tiled is a free software level editor. It supports editing tile maps in
various projections (orthogonal, isometric, hexagonal) and also supports
building levels with freely positioned, rotated or scaled images or
annotating them with objects of various shapes.
commands:

    tiled.terraingenerator

    tiled

    tiled.tmxrasterizer

    tiled.tmxviewer
    snap-id: r*******v5SuaJ
    tracking: latest/stable
    refresh-date: 2 days ago, at 15:09 EDT
    channels:
    latest/stable: 1.9.2 2022-10-17 (3993) 113MB -
    latest/candidate: 1.9.2 2022-09-16 (3993) 113MB -
    latest/beta: 1.9.2 2022-10-17 (3993) 113MB -
    latest/edge: 1.9.2 2022-10-17 (3993) 113MB -
    installed: 1.9.2 (3993) 113MB -
    `
    But when running:

    tiled

from the terminal or clicking on the Tiled icon or running tiled --version, I get the following:

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
`
Any ideas?

**Comment by bjorn** [comment]
@electronmage Answered at #3503.
