### ISSUE TITLE
Can't send object to another layer when only 2 object layers are present in the map

### ISSUE THREAD

**Issue by user72356** [mapeditor/tiled#3417]
The option to select an object, right click and send it to another layer only appears when 3 object layers are present in map. I would expect to start seeing the option when 2 layers are present. 

Thank you!

**Comment by eishiya** [comment]
The culprit seems to be this double check for `objectGroupsIterator.next()` - it wants two `next`s, i.e. a second layer and a third layer.
https://github.com/mapeditor/tiled/blob/master/src/tiled/abstractobjecttool.cpp#L702
Was this perhaps meant to be `if (objectGroupsIterator && objectGroupsIterator.next())`?

**Comment by bjorn** [comment]
> Was this perhaps meant to be `if (objectGroupsIterator && objectGroupsIterator.next())`?

Yeah, actually the `begin` function already calls the first `next`, so there should be only one additional call. Good catch!
