### ISSUE TITLE
Render issue combining tiles from collection and single-image tilesets on same layer

### ISSUE THREAD

**Issue by nerochiaro** [mapeditor/tiled#3420]
Tiled renders tiles incorrectly when a layer of a tilemap uses tiles from both a tileset that is a collection of images and tiles from a tileset that is based on a single image. This only happens when the tile from the collection tileset is bigger than the grid size of the map.

**To Reproduce**
- Create a tilemap (say 32x32 grid size)
- Create a tileset that is based on a single image, with some tiles in it
- Create a tileset that is based on a collection of images. Add an image to it that is bigger than the grid size of the map (say 64x64)
- Cover an area with tiles from the single-image tileset that is 64x64 wide.
- Now place the tile from the collection tileset so that it completely covers the other tiles you placed before.

I would expect the entire 64x64 area to be occupied by the tile from the collection tileset.
Instead some tiles still display the graphics from the single-image tileset.

**Media**
Here's a short capture that illustrates the problem (the single-image tileset is called "Atlas" here).
After placing the tile from the "Collection" tileset I would expect the whole are to display as purple, without the green tile from the "Atlas" tileset bottom-right corner.

![tile-paint-problem](https://user-images.githubusercontent.com/24157/180323553-e9388b20-4c4e-419b-9f33-889c69c3dd4d.gif)

Here's a zipfile of the project from which the above capture was generated.

[tilepaint-bug.zip](https://github.com/mapeditor/tiled/files/9163091/tilepaint-bug.zip)

**Specifications:**
 - OS: Ubuntu 20.04
 - Tiled Version: 1.9.0

**Comment by eishiya** [comment]
This is not a bug, this is correct behaviour. The 64x64 tile occupies *one* tile cell, and which tiles are drawn on top is determined by the map's render order. By default, tiles below and to the right will be drawn on top.

To understand this more clearly, consider the situation that your larger tiles aren't a multiple of your smaller tiles, e.g. if they were 48x48 or 36x36 instead of 32x32. You would expect them to occupy the cell they're placed it and not overwrite surrounding tiles.

**Comment by nerochiaro** [comment]
Ok, I think I understand why this is the correct behavior. Thanks for taking the time to explain it.
