### ISSUE TITLE
No way to set a float prop to 0.0 in tiled extension

### ISSUE THREAD

**Issue by fmoo** [mapeditor/tiled#3423]
**Describe the bug**
Tiled extensions are unable to set map, layer properties to a float value of 0.0.

**To Reproduce**

1. use the following JS in a tiled extension:
```
tiled.assetOpened.connect((asset) => {
  if (asset.isTileMap) {
    asset.setProperty("autoscrollX", 1.0);
    asset.setProperty("autoscrollX", 0.0);
  }
});
```
2. open a map.

**Expected behavior**
The map contains an "autoscrollX" property set to 0.0 (a float).  Level designer can easily set the property to 0.1 or 0.3 without any additional steps.

**Actual behavior**
The map contains an "autoscrollX" property set to 0 (an integer).  Level designer must right click and "convert to float" before they can  use this property with decimal values.

**Media**
N/A

**Specifications:**
 - OS: Windows 11
 - Tiled Version: 1.9.0

**Comment by eishiya** [comment]
This isn't limited to 0.0, it happens to *any* whole number, including 1.0, 34987.0, etc.

This is a known issue mentioned in the API docs, it is a limitation of JavaScript, which does not distinguish ints and floats. Tiled guesses the property type based on the type of the value you give it, but integers and whole-number floats are ambiguous.

Possible solutions I mentioned when we discussed this issue on Discord:
1. `convertProperty(name, type)` method that converts the current value to the desired type as well as it can. This is probably overkill, since this is only a problem with (a subset of) floats, and most conversions make no sense.
2. Optional third parameter to `setProperty()`, something like a `forceFloat` bool which is used when the value is a number, and ignored otherwise.
3. `setFloatProperty(name, floatValue)` method that works like `setProperty`, but the type is always float.

Option 2 is probably the cleanest one, from a script developer's perspective.

**Comment by bjorn** [comment]
I think I'll try adding `setFloatProperty`, since then we can naturally also have `setColorProperty`, since we have a similar problem with colors not being distinguishable from strings.

**Comment by bjorn** [comment]
I've pushed this change to a new `1.9` branch, since there was a localized string added on `master` so that would eventually become Tiled 1.10 now.
