### ISSUE TITLE
Other maps in a World show misaligned Object outlines

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3429]
With "Show World" enabled, the shadows on Objects on other maps in the world are off by some amount that increases with the zoom level, only Objects on the current map have correct shadows. This screenshot is at 800% zoom.
![image](https://user-images.githubusercontent.com/70545646/182845045-78053e86-b47f-4188-a4a4-e35516954f45.png)

This is on Tiled 1.9, but it's been a while since I looked at projects with Worlds and Objects, so I can't be sure whether this problem was introduced in 1.9 or earlier.

Steps to reproduce:
1. Create two maps and place a shape Object in each.
2. Add the maps to a World.
3. Make sure View > Show World is enabled to see both maps.
4. Zoom in on the map that's *not* the active map to observe misaligned object borders.

For your convenience, here's a World with two maps and every shape Object type.
[ObjectTest.zip](https://github.com/mapeditor/tiled/files/9259664/ObjectTest.zip)
Looks like Points display fine, while the other types have misaligned outlines, so perhaps this is a regression from the change to make Points scale with zoom level?

**Comment by bjorn** [comment]
I'm afraid it's a regression since v1.8.91 (the 1.9 RC), coming in as part of the change to no longer scale point objects (b81264e66a3712827d4a6d8a6e0412761b43a1ca). The `MapView::paintEvent` only sets the "painter scale" on the renderer of the current map, while it would need to set it on all the maps displayed in the view (unless we find another way of communicating the scale).
