### ISSUE TITLE
Marking rectangle stays when making object layer invisible

### ISSUE THREAD

**Issue by ChristianPervoelz** [mapeditor/tiled#3441]
**Describe the bug**
When making an object layer invisible, where a selection is shown, the selection is not becoming invisible.

**To Reproduce**
1. Create a new map (default) values
2. Create a new object layer
3. Insert a point -> creates a new marker and surrounds it with a selection rectangle
4. Make the object layer invisible using the layers window

**Expected behavior**
Not only the marker should disappear, but also the selection rectangle.

**Media**
![tiled_staying_Selection](https://user-images.githubusercontent.com/24943047/184142122-166c3d28-8a56-4572-bb0e-c288c75c4794.png)

**Specifications:**
 - OS: 11
 - Tiled Version: 1.9.0

**Comment by eishiya** [comment]
I don't think this is a bug. It would be confusing if the selection indicator disappeared if the selected objects weren't visible - you'd think you no longer have anything selected, even though you do, and you could move, delete, etc objects without intending to. The selection remaining visible makes it clear that you still have objects selected.

Automatically *de*selecting objects that are hidden would be a bad idea because temporarily hiding layers is a common way to make it easier to add more objects to your selection.

**Comment by bjorn** [comment]
Yes, objects remain selected even if invisible, which is important for reason explained by @eishiya. Showing the selection marker even for invisible objects is intentional.

**Comment by ChristianPervoelz** [comment]
Hm, I'm not sure, I've understood the explanation.
When a layer is invisible I cannot do anything on it: no moving, no adding, deleting or whatever else, so I cannot 'destroy' anything accidentally.
The indicator just looks like an artifact. :(

But anyway, I believe developers have good reasons to add certain features and behaviors to their applications, so I'm totally fine with it.
May there is a chance to have a settings option?

**Comment by bjorn** [comment]
> When a layer is invisible I cannot do anything on it: no moving, no adding, deleting or whatever else, so I cannot 'destroy' anything accidentally.
> The indicator just looks like an artifact. :(

Hmm, in fact you can still delete, move or resize an object even if it is hidden but selected (for moving you can use arrow keys or hold Alt when using left mouse button). You can also select hidden objects, for example by clicking them in the Objects view or through the scripting API, so it's useful to "see" these hidden objects by their selection marker.

> May there is a chance to have a settings option?

Since there remain good reasons for keeping the selection marker visible, I think this option would not be very useful.

**Comment by ChristianPervoelz** [comment]
Yes! Totally missed that point. Thanks. :)
