### ISSUE TITLE
Can't add Map to Image Collection tileset

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3447]
When adding images to an Image Collection, Tiled offers the option of several Map formats (TMX, TMJ, JS), so presumably it's an intended feature that Image Collections can use Maps as images, just like "Based on Tileset Image" tilesets.
![image](https://user-images.githubusercontent.com/70545646/184248658-cdc3f0b0-0b2d-4918-89ae-95e357daff87.png)
However, actually choosing a map to load always fails with the message `Could not load "{FILEPATH}"!` I suspect Tiled tries to open the file as an image, and doesn't try to open it as a map.
![image](https://user-images.githubusercontent.com/70545646/184248790-15f88104-2e2e-43f9-a9aa-534fd3d737bd.png)
Also, both the "Ignore" and "Cancel" options in that dialog seem to do the same thing: nothing.

Being able to add maps as tiles to Image Collections would open up some interesting workflows, and I'd love to see this apparently intended feature working!

Tested on Tiled 1.9.1 on Windows 10, but issue must be older, I just never tried it before today.

**Comment by bjorn** [comment]
> However, actually choosing a map to load always fails with the message `Could not load "{FILEPATH}"!` I suspect Tiled tries to open the file as an image, and doesn't try to open it as a map.

Hmm, indeed it does. It seems maps are supported already in image collection tilesets, it's just not possible to add them through the UI because it tries to make sure you're adding only loadable images.

> Also, both the "Ignore" and "Cancel" options in that dialog seem to do the same thing: nothing.

They only differ when you try to add multiple files at once. Then, Ignore will only skip one file, whereas Cancel will stop the entire operation. I guess selecting only one file is common enough to check for this case and show only an OK button.
