### ISSUE TITLE
Copy and paste of AutoMap Rules add that tileset a second time

### ISSUE THREAD

**Issue by Seanba** [mapeditor/tiled#3462]
**Describe the bug**
When copying and pasting regions of tiles that include a tile from the `Automap Rules` tileset I've noticed that the `Automap Rules` tileset is added to the list of tilesets a second time.

**To Reproduce**
1. Open or create a map
2. Use the `Map/Add Automapping Rules Tileset` menu item to include that tileset
3. Place some of these tiles in a layer in your map
4. Use the `Rectangular Select` tool to select some of these tiles on your layer
5. Copy the selection
6. Paste the selection into your layer
7. See that you now have `AutoMap Rules` in your list of tilesets twice

**Expected behavior**
If the `Automap Rules` is already included then don't add it again.

**Media**
![image](https://user-images.githubusercontent.com/6980630/187039665-a3a2e864-731d-4046-86be-0f7d8038eb9b.png)

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.9.1

**Comment by bjorn** [comment]
This appears to be caused by a slight difference in the path of the Automapping Rules Tileset. The one added by the action is loaded from `://automap-tiles.tsx`, whereas the one that gets added after copy/paste is loaded from `:/automap-tiles.tsx`.

This also survives into the saved file:
```xml
 <tileset firstgid="22" source="://automap-tiles.tsx"/>
 <tileset firstgid="27" source=":/automap-tiles.tsx"/>
```
However, when loading this file the tilesets are "unduplicated", so some code somewhere realizes they are the same tileset, heh.
