### ISSUE TITLE
Some object types files from older versions don't import correctly?

### ISSUE THREAD

**Issue by YourBuddyBill** [mapeditor/tiled#3472]
**Describe the bug**
Importing an Object (now Class) Types Editor file that worked fine in 1.8.6 only imports the names in 1.9, none of the custom properties themselves appear to be importing correctly.

**To Reproduce**
1. Create a project
2. Import the attached object types file
3. Open Custom Types Editor
4. Select a custom type
5. See that there's no properties
6. Get confused

**Expected behavior**
I expected the object types to have their custom properties imported as they were defined in the file, and each be individually visible in that big empty space, and for them to then be usable to reference in maps and stuff.

**Media**
Importing the attached object_types.json file in 1.8.6:
![tiled_1_8_6_objecttypes](https://user-images.githubusercontent.com/4391382/190302195-30fbd36b-b960-4f08-9578-c9a58e420b72.png)
Importing that same file in 1.9.1:
![tiled_1_9_1_customtypes](https://user-images.githubusercontent.com/4391382/190302391-b6c87481-0274-4d32-a571-268f030f0246.png)

Here's the file in question (Github doesn't let me upload json files, so rename this file from .txt to .json and try it)
[object_types.txt](https://github.com/mapeditor/tiled/files/9571317/object_types.txt)

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.9.1 (worked fine in 1.8.6)

**Comment by bjorn** [comment]
Ah, this isn't really a bug but unfortunately quite bad usability. The JSON format changed in Tiled 1.8, and when importing types, it expects you to select the right file type:

![image](https://user-images.githubusercontent.com/531764/190575575-69708bf0-f528-4499-a8a3-b9164cd05c07.png)

Importing of "Object Types JSON" files does not work when you select "Custom Types files" (the default).

I will have a look at auto-detecting the old format in the Import dialog, but I'm afraid the distinction will remain relevant for the Export dialog, since the extension is the same.
