### ISSUE TITLE
Automapping: "Other" doesn't behave as described/expected

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3474]
The "Other" automapping rule tile doesn't seem to behave as described in the documentation:
- Unless the rule contains Empty inputs elsewhere, Other matches Empty.
- Other seems to be overridden by the Empty tile if it's present
- When combined with explicit tiles, it seems to break the rule entirely, never matching even when either the explicit tile or the Other should match

I am using 1.9.1, but AFAIK 1.9.2 doesn't have any changes to Other tiles and probably works the same.

For example, this rule looks for a grass tile surrounded by Empty or Other tiles, and outputs a small dark green tile on another layer:
![image](https://user-images.githubusercontent.com/70545646/190921252-5ebd11a4-2ec6-4a27-9299-ddd040d1021f.png)
I expect this rule to match all of these scenarios:
![image](https://user-images.githubusercontent.com/70545646/190921304-598cbefb-11fe-4241-a0ab-72df0fa59721.png)
However, the rule only matches the tile that's surrounded by empty tiles:
![image](https://user-images.githubusercontent.com/70545646/190921398-aba6f682-de7b-4854-9042-fb924538b696.png)

If I remove the Empty input tiles so that only Other tiles are left, then the rule matches all three scenarios, which is *also* unexpected behaviour, as the documentation says Other only matches *non-empty* tiles.
![image](https://user-images.githubusercontent.com/70545646/190921890-19ae4fb7-c754-4ad3-b863-df36a9fa5f2c.png)
![image](https://user-images.githubusercontent.com/70545646/190921898-c818e27c-f16b-49c9-994f-acfbbf431b08.png)

If I make a rule that looks for a grass tile surrounded by cliffs or Other, then the rule doesn't match *any* of the above scenarios or even the extra scenario where the grass tile is surrounded by yet another tile, even though I'd expect it to match the 2nd and 4th scenarios, or at least the 4th scenario:
![image](https://user-images.githubusercontent.com/70545646/190922634-83560271-310b-4321-aa22-962ef98c00e8.png)
![image](https://user-images.githubusercontent.com/70545646/190922642-95bc7cec-8445-4b3b-9e07-d6963b62ca35.png)

**Comment by bjorn** [comment]
> For example, this rule looks for a grass tile surrounded by Empty or Other tiles, and outputs a small dark green tile on another layer:

Here, you effectively created a rule that says "no grass tile AND empty", not "no grass tile OR empty". This is because the "Other" tile is like a "none of these", and multiple input layers only combine into an "OR" when they are specifying tiles that do match, as opposed to tiles that don't match.

> If I remove the Empty input tiles so that only Other tiles are left, then the rule matches all three scenarios, which is _also_ unexpected behaviour, as the documentation says Other only matches _non-empty_ tiles.

The code isn't matching the docs. According to the code, Other will always also match Empty tiles.

> If I make a rule that looks for a grass tile surrounded by cliffs or Other, then the rule doesn't match _any_ of the above scenarios or even the extra scenario where the grass tile is surrounded by yet another tile, even though I'd expect it to match the 2nd and 4th scenarios, or at least the 4th scenario:

In this case, the Other tile is saying "any other tile than grass and cliffs" (because both are part of the input), and the other input layer is only matching "cliff", effectively making a rule that can't match anything.

**Comment by eishiya** [comment]
Thanks for the clarification! I see what went wrong.

As discussed on Discord, I think all that's needed is:
1. Make it so that whether Other matches Empty depends on whether the input uses Empty or not. If an input contains Empty, it doesn't really make sense for Other to match Empty.
2. Update the documentation to remove the mention that it only matches non-empty cells.

I've updated my Automapping documentation draft accordingly:
> This tile matches any cell which contains a tile that is <em>different</em> from all the tiles used on the current input layer in the current rule.

**Comment by bjorn** [comment]
@eishiya I've included these changes in PR #3602. 

Note that I've tried to tweak the documentation on another point, which is that the "MatchType: Other" case actually collects input tiles from all input layers sharing the same index and target layer. I think "current input layer" is a little ambiguous, since it makes it sound like if you had two "input_foo" layers, the "Other" would only exclude tiles from the same layer, whereas it excludes tiles used in either.
