### ISSUE TITLE
[JSON export] Avoid use of reserved words in property fields (eg "class")

### ISSUE THREAD

**Issue by nspitko** [mapeditor/tiled#3492]
**Is your feature request related to a problem? Please describe.**
In Haxe (and I presume other languages as well), parsing JSON files is often done by mapping them to static types. This produces a nice, compile time typed interface to access data through. However, it comes with a few caveats; one of which being that reserved keywords come into play. 

Specifically, "class" is a reserved word (as it is in most languages), meaning the "class" property can't be defined this way. There are ways to work around this issue (through `Dynamic`, as an example) but it creates convoluted code.

**Describe the solution you'd like**
It's possibly too late to change the default behavior here, but an export option would probably be enough. I realize that every new option here clutters up the UI; but I would presume this affects more than just Haxe.

**Describe alternatives you've considered**
This could be solvable with some kind of pre or post process export feature, which would give a lot more control over the output without potentially creating a matrix of language workarounds. I could also simply write my own format using the API.

The main reason I'm suggesting this as a tiled level feature is that "class" is a reserved keyword in a significant number of languages, and this kind of data mapping isn't an uncommon pattern.

I did a quick scan of other libraries, but found that most of them appear to operate on tmx files directly instead of json, and the json ones I did find are still referencing the old "type" field; so it's not clear how many others are actually affected.

**Comment by eishiya** [comment]
Python has this issue even worse: you can't even access `myObj.class` because Python reserves the `class` keyword so hard xP You have to use string-based access to get the class after parsing JSON.

There is already an option for this though, and I don't think Tiled needs *another* one: the 1.8 compatibility mode in the Project settings, which uses "type" instead of "class". It affects not only exports, but your main file as well.

**Comment by Yanrishatum** [comment]
@eishiya 1.8 compat toggle did not make it clear in any way. And it's a project-based toggle, meaning you can't even use it for project-less maps (for example when you do a game jam game, in which case you don't really want to bother with project setup). Is there any reason to renaming `type` into `class` in the first place other than vague reason of them resembling classes after object types rework? Because that looks like a breaking change for the sake of breaking change to me. Usage of such an obviously reserved keyword for an important field seems odd. And many libraries would just stick to using `type` for sheer reason of people already being used to it and `class` being a keyword, creating field naming disparity between Tiled and libraries.

**Comment by gslance** [comment]
This change broke my custom importer and now it's become a problematic situation to keep older projects updated versus new projects. This change a welcome update, in my opinion.

**Comment by bjorn** [comment]
Thanks for the feedback! It seems like this has been a bad call, not just because it is a reserved keyword, but mostly because it broke stuff in a lot of people's projects. I'm looking into switching it back to `type` in a small Tiled 1.10 release.

The big learning for me is mostly to make sure compatibility breakages are opt-in. Tiled 1.5 also broke compatibility, but it was in a much less frequently used area and one that wasn't relevant to most games (terrain sets). For the change from `type` to `class` I knew it was going to affect more people, which is why I had added the compatibility option. It is clear that this wasn't enough. This option could have been enabled by default, but actually this was a change better not made at all.

**Comment by WickedSmoke** [comment]
I just updated to 1.9.2 and ran into this issue with my TMX loader.  In my case this was only a minor annoyance as the loader works by filtering the attributes, so I was simply able to add a "class=" to "type=" filter.

**Comment by bjorn** [comment]
> Specifically, "class" is a reserved word (as it is in most languages), meaning the "class" property can't be defined this way. There are ways to work around this issue (through `Dynamic`, as an example) but it creates convoluted code.

@nspitko Just wondering, but does Haxe not provide any annotation, in order to use a different name in the JSON than for the Haxe class, for example [like `JsonPropertyName` in C#](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-7-0)?

@eishiya Since you mentioned Python, I guess the solution there is just to write `object['class']` instead of `object.class`.

I've been looking into restoring compatibility with Tiled 1.8, but there are three cases making it hard to switch to using "type" everywhere:

* The `wangset` element already has a `type` attribute, telling us the type of Wang set.
* The Lua and JSON formats already use a `type` property for layers, telling us the type of layer.

The Wang set type could be renamed without much fuss, but renaming the layer `type` property in JSON would cause unwelcome breakage.

Hence, I'm now considering to take the approach used in the current Tiled 1.8 compatibility mode (see #3560). That is to use "class" wherever I've added the ability to assign a class, but store the class as "type" in the existing data structures that had this feature: map objects and tiles. It's a nasty inconsistency, but a consistent attribute would mean breaking compatibility.

**Comment by Yanrishatum** [comment]
@bjorn No, Haxe does not explicitly have that feature, you can access it via `Reflect.field(json, fieldName)`. The generic mapping of json data in Haxe (via `typedef`) does not allow custom methods and such as they just describe the data layout and internally (depending on target) are some sort of `Dynamic` wrapper. It does allow to do that via `abstract` and macro, however, but it requires extra manual legwork to achieve and would still rely on `Reflect`.

If `type` is not feasible, why not use `kind`? It's more or less never a keyword in any language I'm aware of and is often used to determine "what kind" of the object it is. In Haxe it's often used when `type` is already occupied.

> but renaming the layer type property in JSON would cause unwelcome breakage.

Didn't renaming `type` into `class` already introduced said unwelcome breakage? :)

**Comment by bjorn** [comment]
> Didn't renaming `type` into `class` already introduced said unwelcome breakage? :)

It did, and I'm trying to undo it, without doing it again. :-)

Renaming to "kind" is not really what I'm looking for. I don't think it's a very fitting name and it would be yet another breakage.

The easiest solution that comes to mind, is to just do a search & replace string operation before the call to `haxe.Json.parse`, replacing `"class"` with `"className"` (or `"kind"`) for example. Of course it adds a little overhead, but it should avoid all the business with `Dynamic` or `Reflect`.

**Comment by bjorn** [comment]
So for Tiled 1.10, we're now back to using `type` for objects and tiles, but for other types of objects we're still using `class` in order to not break compatibility again.

I'm closing this issue since it seems to be limited to Haxe, so I would suggest using any of the above suggested workarounds there (and ideally the Haxe compiler could be improved by adding an member attribute that allows to map one name to another).

**Comment by Yanrishatum** [comment]
So, just to get this straight:
* Tiled 1.9 introduced massive breaking change with renaming `type` into `class`, causing libraries in a number of languages (not only Haxe, any language where you can't just access `.class`) to develop a naming mismatch due to usage of reserved keyword. And each library would have to manually sidestep the issue in some way or another.
* In 1.10 it will rename it back only for _2 types_, introducing general API inconsistency (and break libraries that already adapted to 1.9), and libraries that had to sidestep `class` keyword now have to... Sidestep `class` keyword but for 2 things less (the way it's being sidestepped is irrelevant, the sole fact that it has to be done, even if with relatively simple way of C#, is what matters).

I'm not against breaking changes per se, it's just this particular breaking change made use of an extremely common reserved keyword. I think having 2 breaking changes in a row but retaining consistent API and adapting to new features of Tiled is much better than dealing with that inconsistency for years to come and then have more moss grow on it causing to be pretty much impossible to patch out. Yeah, sure, it now will work with older libraries, but supporting Tiled newer features will be that much more inconvenient in languages that have said keyword (and that's a lot of languages).

I also don't think this issue is resolved, as it's about avoiding usage of a reserved keyword. It still uses said reserved keyword, just not for 2 particular things.

**Comment by bjorn** [comment]
I can only add that the inconsistency bothers me as well, but I do not see a way to keep compatibility and consistency. I've broken compatibility in 1.9, saw how that broke things for many people and kept being a problem even half a year after the breakage. So restoring compatibility was more important to me than the consistency.

Regarding consistency, I tried calling it "type" everywhere, but failed because it also was not possible while keeping compatibility. In the TMX format, it would only break the existing `wangset.type` attribute, which is a minor issue, but for JSON the `type` property was already used by layer objects, and changing that would be a bigger breakage.

As for "class" being a reversed word and hence problematic, as far as I could see this problem is really limited to Haxe's current support for mapping JSON data to anonymous structures, and not a problem in any other popular programming language. I don't think it's right to compromise on the most fitting attribute name because of the limitations of one language's support for JSON (for which I've also described a workaround above). Hence I have closed this issue. In case I'm wrong and the use of this name does present a wider issue, please do let me know.
