### ISSUE TITLE
Get path to current project with Tiled API

### ISSUE THREAD

**Issue by solerante** [mapeditor/tiled#3527]
**Is your feature request related to a problem? Please describe.**
I would like to fetch the current project's path using the Tiled API.

**Describe the solution you'd like**
Something like `tiled.activeProject` which returns the path of the current open project.

**Describe alternatives you've considered**
- Asking the user the path of the current project.
- Putting the path in `tiled.activeProject.path` if there is some reason to make it an object. Maybe to dynamically make projects?

**Comment by eishiya** [comment]
I think this would be better as a comment on #2902 - Projects aren't accessible to the scripting API at all, and it would be better to have the available as part of a proper API rather than just as a file path. The Project API should, of course, have a way to get the base path of the project, as well as the paths of directories added to it.

**Comment by bjorn** [comment]
I recently added this actually (462986cb144fe5c139119eb6b482cdbac7275892). I thought I might not get around to finishing the project API for 1.10 but at least wanted to provide access to the path, since it's most commonly needed.
