### ISSUE TITLE
Stamps with different sizes make trouble when using Shape Fill Tool

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3533]
**Describe the bug**
When combining Stamps of different sizes like 3x2, 4x2, 6x2 (see screenshot below), and then using the Shape Fill Tool causes gaps like shown in the GIF below.

**Expected behavior**
One consistent stream of stamps with no gaps.

**Media**
![SHift](https://user-images.githubusercontent.com/1249266/204090890-9851162b-0a00-4e4d-a39c-a1a9330ac708.gif)

![grafik](https://user-images.githubusercontent.com/1249266/204090903-42cba9e6-ae11-455f-aad9-0a9715448097.png)

**Specifications:**
 - Tiled Version: v1.92

**Comment by bjorn** [comment]
I think the shape fill tool currently just fills the area with a grid based on the largest variation of the stamp.

Since you're using it to draw lines in this case, could you try whether line drawing with the Stamp Brush works better (Shift modifier)? That one should not leave gaps, even with there are variations of different size.

**Comment by UliAbo** [comment]
Thanks @bjorn for your quick reply. 
Yes I also tried using Stamp Brush + Shift, but on my end the behavior / effect is the same as with Shape Fill Tool. Just tried it again.

**Comment by bjorn** [comment]
Ah, I think what's happening is, it iterates along the line you want to draw, and each time it tries to place a variation, it does an overlap check first. If the variation overlaps with previously placed tiles, it will skip the current location, and try again at the next location. This way, it can happen that a location gets skipped because of a larger variation, after which it can end up choosing a smaller variation at the next location.

I think for line drawing the fix is simple. Just don't choose a new variation at each point, but only after actually placing a variation.

**Comment by bjorn** [comment]
Both the line drawing and filling should work much nicer now when variations have different sizes. There may still be gaps in some cases, as outlined in c4c165f1c8de12db6c2333ac6607049a6a31bc38.
