### ISSUE TITLE
Automapping output should be ignored if the output layer is locked

### ISSUE THREAD

**Issue by dustinaux** [mapeditor/tiled#3544]
There could be a boolean added to the map or layer properties of a rule file that would override this, but I think the default should be locked layers are ignored, the opposite of what currently happens.

The current workaround is to duplicate the layer I don't want altered, run the automap, then delete the new output layer that was changed and rename my copy back to the correct layer name.

**Comment by bjorn** [comment]
I fear some people may be using the layer locking feature in order to prevent themselves from editing layers that their automapping rules are taking care of. As such I'm a bit weary of this change, even though I agree it makes a lot of sense.

At the very least an option to ignore layer locked status should indeed be provided when implementing this change.

**Comment by eishiya** [comment]
+1 for an option for this! I often need both - I have some rules that I want to prevent by locking the output layer, and some rules that I want to run regardless of locked state. I currently have to rename layers to achieve what I need.

**Comment by bjorn** [comment]
I've opened a PR for this feature at #3562. Feedback is welcome!
