### ISSUE TITLE
Drag and drop image directly to Object Layer

### ISSUE THREAD

**Issue by drschwabe** [mapeditor/tiled#3580]
Tiled has excellent performance when dealing with huge number of images including high resolution images.     This makes it useful as a flowchart/storyboarding tool (similar to another program called Pureref) 

However, getting an image on to a map requires first the image be in a tileset. 

This feature request suggests making it possible to skip the tileset so we can drag and drop images directly to an object layer and have it auto-insert as a quasi 'Tile' 

Extra points if clipboard support was available so that we could similarly just paste an image from the clibpoard to an Object layer as a Tile

This would rapidly speed up the process and make Tiled a viable storyboarding/flowcharting/ideation tool.   Thanks!

**Comment by eishiya** [comment]
Supporting non-tiles would make Tile Objects needlessly more complicated, or would require a new and redundant Image Object type. Tiled is not intended to be a storyboarding/flowcharting tool, and I don't think it's a good idea to add features to enable such uses, especially when those features would complicate the tasks that Tiled is meant for.

#3107 is about making it easier to create tilesets by dragging images into Tiled and to allow more context-sensitive drag-and-drop, a more commonly useful behaviour than creating specifically Tile Objects with them. I think the suggestion there that dragging an image into an Image Collection in the Tilesets panel would add it to that Image Collection, combined with also selecting that newly added Tile for use would be a good compromise - it would save you time in adding images to an Image Collection as needed, but would allow Tiled to remain, well, ***Tile***d.

If dragging images into the Tilesets panel like this also gives you the option to select an existing tile already using that image instead of *always* creating a new tile, it would make dragging an image into Tiled a viable way to select the relevant tile in an unwieldy tileset. That said, I think it would still be a poor way to select tiles, and tile search (#873) combined with a way to sync an Image Collection with a directory or several would be a better solution.

**Comment by drschwabe** [comment]
> Tiled is not intended to be a storyboarding/flowcharting tool, and I don't think it's a good idea to add features to enable such uses, especially when those features would complicate the tasks that Tiled is meant for.

Great point, agreed - probably best then if this specific feature was needed it could be made as a plugin (tentatively added to my own todo list ie- explore creating a Tiled plugin) 

> I think the suggestion there that dragging an image into an Image Collection in the Tilesets panel would add it to that Image Collection, combined with also selecting that newly added Tile for use would be a good compromise - it would save you time in adding images to an Image Collection as needed, but would allow Tiled to remain, well, Tiled.

totally - wow those features proposed in that thread would be as you say a good compromise.   Simply being able to drag and drop new images into the Tilesets panel > Image Collection tileset would save a ton of back and forth between map and tileset tabs.   I particularly like your idea of selecting the newly added image afterwards which would be icing on the cake.  

> I do like the idea of copy+pasting image data directly into tilesets though. AFAIK Tiled already supports using image data instead of a file reference to some degree, it would be cool to enable this via the GUI.

Yeah basically if you have an Image Collection open in a Tileset tab, if you simply CTL+V and it adds a new tile from clipboard that would be super great too.   Likewise if we had the aformentioend drag drop directly to Tilsets panel I think if we had this paste feature for Tilesets tab then the panel likewise could have the same behavior ie- if the user has a tile selected and in Tile insert mode a paste would create a new tile and select that new one immediately.  

> If dragging images into the Tilesets panel like this also gives you the option to select an existing tile already using that image instead of always creating a new tile, it would make dragging an image into Tiled a viable way to select the relevant tile in an unwieldy tileset. That said, I think it would still be a poor way to select tiles, and tile search (https://github.com/mapeditor/tiled/issues/873) combined with a way to sync an Image Collection with a directory or several (https://github.com/mapeditor/tiled/issues/3083) would be a better solution.

Indeed the sync solution would be great too!   This way we could just use the filesystem to add new tiles.    Thus then the only need to drag and drop a new image directly to the GUI would be for the 'insta select' feature we're talking about above.   

And as you say, it could be a form of search in a huge tileset; ie- maybe the user already knows what image tile they want to select and they have it selected on their filesystem - so they can simply drag and drop and Tiled would select the tile but not add an extra image cause it would detect the existing file.     If a filename based search was in place that would be of course more common method of finding a tile but personally I'd love both options cause I tend to  have my OS file browser open at all times in relevant directory already; which aslo has its own search feature that may be better/more convenient than Tiled's for example. 

Anwyay, great discussion - I'll close this issue in the interest of keeping the focus on those existing related requests and perhaps thereafter we could revive some of these ideas here too in some shape or another.
