### ISSUE TITLE
Godot 4 Export in 1.10

### ISSUE THREAD

**Issue by feendrache** [mapeditor/tiled#3612]
**Describe the bug**
I tried to export a map into godot4 format

**To Reproduce**
open an existing tiled map inside a godot project, try to save it as godot 4 scene

**Expected behavior**
saving

**Media**
![Unbenannt](https://user-images.githubusercontent.com/33016907/224350801-49ee64b0-9816-4f7b-81ae-d4d853b2c889.PNG)

**Specifications:**
 - Windows 10
 - Tiled 1.10

**Comment by bjorn** [comment]
I think this is because currently the plugin only searches up 3 parent directories when trying to find the `.godot` project file:

https://github.com/mapeditor/tiled/blob/eed11a2e67d90c997e6d8e3321f06f74f92a9ccb/src/plugins/tscn/tscnplugin.cpp#L76-L98

Whereas I see your `muddy cave v1.png` file is nested much deeper.

I think we could probably just remove the limit and always search up to the root of the file system.
