### ISSUE TITLE
Unable to read image data in 1.10 for big images

### ISSUE THREAD

**Issue by patchuby** [mapeditor/tiled#3616]
**Describe the bug**
Some images from a collection of image tilesets are suddenly missing after updating from 1.9. Trying to reimport them brings up this :
<img width="131" alt="image" src="https://user-images.githubusercontent.com/9586594/224749952-d4e47217-0642-45ea-977b-0adca13f37ad.png">

I've noticed all the missing images are big background images. The larger one that is still there is 5197 x 6412 (0_Background_01.png) whereas one with 5196 x 6557(0_Background_02) didn't pass. They are included below, can send more if needed.

**Media**
![0_Background_01](https://user-images.githubusercontent.com/9586594/224751303-41245c06-ba53-4aa8-b75f-90f44a902f93.png)
![0_Background_02](https://user-images.githubusercontent.com/9586594/224751308-99e748ce-6fcc-40df-ad77-062aa2388bbc.png)

**Specifications:**
 - OS:  Windows 11
 - Tiled Version: 1.10 64 bit

**Comment by patchuby** [comment]
64 bit !

**Comment by bjorn** [comment]
Hmm, I tried this on Linux and while the first image indeed loaded fine, the second one failed with the following message printed to the console:
```
qt.gui.imageio: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 128 megabytes
```
Turns out Qt 6 introduced [`QImageReader::setAllocationLimit`](https://doc.qt.io/qt-6/qimagereader.html#setAllocationLimit), along with a default limit "large enough for all commonly used image sizes" (128 MB). So we'll either need to disable or increase the limit, or provide a user setting for this.

@patchuby As a workaround, you can set the environment variable `QT_IMAGEIO_MAXALLOC` to either 0 (to disable the limit) or whatever limit you deem suitable for your project.

**Comment by patchuby** [comment]
I've reverted back to 1.9 for the time being, but thanks for the workaround !

**Comment by bjorn** [comment]
@patchuby When you have some time, you could try whether the builds at #3621 have fixed this issue. They now have an allocation limit of 1 GB instead of 128 MB per image.

**Comment by filiph** [comment]
Hmm, I just installed Tile 1.10.1, which includes this fix, but the problem persists. Maybe my file is still too large for Qt?

My original issue: https://github.com/mapeditor/tiled/issues/3631. My image is 19200x19200 pixels.

<img width="792" alt="Screenshot 2023-04-04 at 19 30 23" src="https://user-images.githubusercontent.com/919717/229871517-98769d83-f173-40ec-861a-e09f7cfe7532.png">

**Comment by patchuby** [comment]
Yes that would make it 1.4GB  whereas the limit is 1GB.
If this image is destined to be in a game as is, I would advise to cut it into smaller pieces, as the max texture page size I've seen is 16 384 x 16 384, and even that makes it uncompatible with older gpus and consoles (I think the switch is 4096 x 4096 for example).

**Comment by bjorn** [comment]
@filiph I think for permanently setting this variable, you can add that export line to your `~/.bash_profile`.
