### ISSUE TITLE
The shortcut [Space + Left Mouse Button] have a bug. How to use [Ctrl + Left Mouse Button] instead of [Space + Left Mouse Button] to drag map?

### ISSUE THREAD

**Issue by ankisme** [mapeditor/tiled#3672]
**Is your feature request related to a problem? Please describe.**
Current shorcut of dragging map [Space + Left Mouse Button] is hardly to use for me, because when I pressed the space key, it always do the wrong thing, such as toggle the visible of current layer, then I have to mouse click on the map to change focus.

The way to reproduce it:
1. mouse click on label of other layer, for example, the layer name is [layer ABC]
2. pressing [Space + Left Mouse Button]
3. then you will toggle the visible of [layer ABC]

And the space key is not easy to press for me, because it’s a big and long key on the keyboard. For me, the space key is convient to click once, but is not convient for pressing.

And I also don't want [middle mouse button], because the [middle mouse button] is convient for scroll, but is not convient for click.

**Describe the solution you'd like**
So I want to use [Ctrl + Left Mouse Button] instead of [Space + Left Mouse Button].

And I could not found any way to do this.

Here is my .ts extension script.

```ts
/// <reference types="@mapeditor/tiled-api" />

/* global tiled */

const dragLayer = tiled.registerAction("DragLayer", function (/* action */) {
	tiled.alert(`My desired shortcut is pressing [Ctrl + Left Mounse Button] to drag map,

	but current shortcut is pressing [Space + Left Mouse Button], and how to do it?`)
})
dragLayer.text = "DragLayer"
dragLayer.shortcut = "Space"

tiled.extendMenu("Layer", [
	{ action: "DragLayer", before: "SelectPreviousLayer" },
])
```

**Describe alternatives you've considered**

**Comment by ankisme** [comment]
I use autohotkey and mapping alt key to space key, now it's more convient.

**Comment by bjorn** [comment]
In general it would be nice to make mouse interaction customizable, but it is a lot more tricky than keyboard interaction due to the potential for conflicts. The Ctrl modifier is used by several tools in combination with Left Click, for example:

- Ctrl toggles wheel behavior between zooming or scrolling
- Ctrl+Shift with Left Click is used by Stamp Brush to draw circles
- Ctrl with Left Click is used by tile selection tools to choose "Subtract" from current selection
- Ctrl or Shift can be used with Left Click by object selection tool to add to selected objects, instead of replace
- Ctrl with Left Click is used by Terrain Brush to toggle the mode (change corner / change tile)
- Ctrl with Left Click is used by object selection tool when resizing and when rotating, for keeping aspect ratio and snap angle

So when making Ctrl + Left Click perform panning, care would need to be taken not to break any of the existing interactions. Using a different key, like Space, or a different mouse button, like Middle Mouse Button, avoids all these conflicts.

I do see the issue with toggling layer visibility, and I think maybe this could be improved by making the currently focused area more visible. As part of writing a new style (see #3597), I would like to make sure the focus is always clearly visible also for the views like layer list, tileset and map views.

**Comment by ankisme** [comment]
Now I know [Ctrl] is used by many tools, and [Ctrl+Left Click] may conflict other tools in some mode.

Now it seems that the more clearly way is to forbid the functionality of toggle visible by [Space] key, because the [Space] key will conflict with [Space + Left Click] when focus on layer label.

Maybe [V] key is better than [Space] key for toggle visible of current layer, because [V] is the first character of [Visible].

**Comment by bjorn** [comment]
> There still a little inconvient of [Space], because toggle visible by [Space] should be triggered only when [Space] be pressed up, and now it will be triggerred when [Space] pressed down.

Why do you think it's preferable to toggle visibility on release rather than press? Usually shortcuts work on press. Although, in this particular case, the checkbox didn't actually toggle until space had been released.

> And if it's triggered when [Space] be pressed up, perhaps [Space] will not conflict with [Space + Left Click].

If the space press is not handled, then the press will trigger the panning mode, and then the release is expected to end the panning mode, rather than (also) toggling layer visibility, I think.

In any case, I've suggested the removal of this shortcut entirely in PR #3673.

**Comment by ankisme** [comment]
You are right, many key and shortcut key of OS is triggered on press, not release, such as [Win + R] [Alt + Tab] in windows, I forget it.
