### ISSUE TITLE
Embed in map not working

### ISSUE THREAD

**Issue by CaojiamingAlan** [mapeditor/tiled#3685]
**Describe the bug**
I've tried everything to embed the tileset into the map and export it to json, but it is not working. I've tried:
1. Enable the Embed in Map option when creating a tileset
2. Click the Embed tileset button under the tileset window
3. Enable the Embed tilesets option in Export Options in Preferences
However, the json files I've got so far still have no information of the tileset embedded.

**To Reproduce**
1. Do the above steps and try File -> Export As

**Expected behavior**
Array named "tiles" should present in the exported json file.

**Media**
No embedded tile information:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/35325198/236702853-9b481824-19aa-48d0-aebe-85756f574500.png">

**Specifications:**
 - OS: MacOS Big Sur 11.2 Apple M1
 - Tiled Version: 1.10.1

**Comment by eishiya** [comment]
What you've shown is a correctly embedded tileset as far as I can tell.

For "based on tileset image" tilesets like this one, individual tile data is only written out for tiles that have any data associated with them - terrains, custom properties, etc. If there is no data associated with a tile, writing it out would only be a waste of space.

Since your tiles don't appear to have any data associated with them, all you need to know about each tile is where it is in the tileset image, which you can calculate from the tile's ID and the properties that *are* included in the tileset.

**Comment by CaojiamingAlan** [comment]
Got it, seems like the tutorial I am following uses an older version. Thanks for the reply.

**Comment by eishiya** [comment]
Glad you got it sorted out.

I don't think this has changed at all though; AFAIK Tiled has always only written out individual tile data only when there's something to write out. It's possible that the tutorial you were looking at was for Image Collections (where individual tile data is necessary to define a tile), or had custom properties or other data for the tiles.
