### ISSUE TITLE
Add mention about SignPath Foundation and free code certificate in Readme.md

### ISSUE THREAD

**Issue by SabotageAndi** [mapeditor/tiled#3691]
Hi
I am the Developer Evangelist from SignPath.

I noticed that there is no mention of us in the readme. 
Could you please add this to your Readme:

```
## Code Signing
This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=tiled), and a free code signing certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=tiled)
```

If you want, I can send a Pull Request.

Thanks!

**Comment by bjorn** [comment]
I have no problem mentioning SignPath in the `README.md`, but I think there is no appropriate place in that file right now, since it does not really mention the binary packages available for various platforms at all and is entirely focused on developers wanting to compile Tiled themselves.

But as such it is a little outdated and it would be nice to add a section about installing Tiled as a user, where the link to SighPath Foundation would make sense. I'll have a look at adding such a section.

**Comment by SabotageAndi** [comment]
Thanks for the adjustments!
