### ISSUE TITLE
MacOS: opengl very slow

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3716]
**Describe the bug**
When opengl is enabled, zooming or scrolling the map is very slow, slower then without opengl

**Expected behavior**
It should be faster.
Can you add vulkan? https://www.vulkan.org

**Specifications:**
 - OS: MacOS Monterey on Mac Pro
 - Tiled Version: 1.10.1

**Comment by bjorn** [comment]
This will require a total rewrite of the way the rendering is implemented. It is often slow because currently it goes through the same rendering API that Tiled uses to render the map in software mode, so it is not specialized for hardware rendering.

I don't think it's useful to keep an issue open for this at the moment so I'll close this for now. You can read more about the plans for a new renderer at https://github.com/mapeditor/tiled/wiki/New-Hardware-Renderer, if you're interested.
