### ISSUE TITLE
Inconsistencies between .tmx and .tmj files when saving / exporting.

### ISSUE THREAD

**Issue by kerrjnr** [mapeditor/tiled#3839]
**Describe the bug**
Object properties name, rotation, type and visible are missing from default .tmx when saved, until an explicit xml export is performed.

**To Reproduce**
1. Starting anew.
2. Add a tileset with a single tile.
3. Add a custom enum with at least 1 string value.
4. Add a custom class of types tile and object and  uncheck "use as property".
5. Add a property member (any name) of enum from Step 3 and close window.
6. Edit tileset, configure tile as the new class type from Step 4.
7. Add a new map, 2 by 1.
8. Add the tile to cell 0,0.
9. Add an object layer.
10. Add the tile object to cell 1,0.
11. From the Tiled menu choose File..Save As "Tiled map files" using a unique filename, then export as "Tiled map files" to a unique filename and finally export as "JSON map files" to another unique filename.
12. Open the 3 files from Step 11 and compare.

**Expected behavior**
Object layer elements to be consistent across all three files.

Note : Instead of Step 11, if you perform a regular File..Save, then export as Tiled map files over the top of the existing .tmx, each subsequent File..Save (Ctl + S) contains the same content as the Tiled map files export, though still less than the JSON export.

**Media**
My preferences are listed at the bottom of this bug report.
Object snippets from my testing:

- Default Save As
Missing key elements: properties, name and type.
Also missing visible and rotation (unchanged from default values).
Closed and reopened Tiled app and everything seemed accurate so
I assume the app logic gathers data from multiple sources.
```
	<object id="1" gid="1" x="32" y="32" width="32" height="32"/>
```
- Tiled map files export
More content than TMX, less than JSON, including key elements: object.name and object.properties.property.type
```
	<object id="1" type="Wall" gid="1" x="32" y="32" width="32" height="32">
		<properties>
			<property name="WallType" propertytype="eWallType" value="Real"/>
		</properties>
	</object>
```
- JSON map files export
Seems to contain full details by default.
```
	"objects":[
		{
		 "gid":1,
		 "height":32,
		 "id":1,
		 "name":"",
		 "properties":[
				{
				 "name":"WallType",
				 "propertytype":"eWallType",
				 "type":"string",
				 "value":"Real"
				}],
		 "rotation":0,
		 "type":"Wall",
		 "visible":true,
		 "width":32,
		 "x":32,
		 "y":32
		}],
```

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.10.2
 - Preferences
 -- General / Saving and Loading : All checked except "Repeat last export on save".
 -- General / Export Options : All unchecked except "Resolve object types and properties".

**Comment by eishiya** [comment]
Since you have the Resolve Object Types and Properties export option enabled, the custom properties are exported explicitly, which accounts for the difference between saving and exporting - the export preferences are only applied to exports, not saving. The other difference is that in TMX, values with defaults are optional and Tiled does not write them out, which is stated in [the docs](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/):
> All optional attributes are either marked as optional, or have a default value to imply that they are optional.

I think this difference is just due to the fact that Tiled "hand-writes" the TMX files and can thus leave out the defaults, while more generic JSON writing code is used for TMJ. But also I think this is a difference in usage between XML and JSON - since XML is more verbose and is often accompanied by a DTD, XML files are more likely to leave out default values than JSON files, where including defaults doesn't bloat the files quite as much. That said, I do think it would be nice to have the option to skip writing defaults even on JSON.

**Comment by kerrjnr** [comment]
Thanks Eishiya, I appreciate the time you took to respond. I'll have a refresher read of all the docs, I haven't started a new Tiled hobby project in years and I've clearly forgotten a few things since my last read-through.  In saying that, I'd expect a TMX Save to match a TMX Export when the pref settings are as they are and what if the default value is the value you want to be ingesting?  That's one of the benefits of default values, saving the user from having to explicitly set a field value :)

Also, any thoughts on my observation : "Note : Instead of Step 11, if you perform a regular File..Save, then export as Tiled map files over the top of the existing .tmx, each subsequent File..Save (Ctl + S) contains the same content as the Tiled map files export, though still less than the JSON export.", especially considering my preference settings?

**Comment by eishiya** [comment]
(I apologise in advance if these answers don't entirely make sense - I have a hard time understanding your questions, so I may be answering different questions from what you meant to ask.)

Exporting is not the same as saving, there is no reason the output should be the same between the two. The reason the export options exist is precisely that the expectation is generally that exported production files are different from the saved work files. The exports generally *are* identical to saving when all export options are *disabled*, however. It would be a bad idea for saving to resolve class/tile properties, as it would destroy the ability to inherit default values from the class/tile when the file is saved, because, as you said, the explicit value is treated as non-default.

Are your exports overwriting your saves, is that the problem? If so, you may want to fix that, e.g. by exporting to a different location or filename. The idea is generally that you export **to a different destination**, because exports are intended to be for e.g. production files, when you need them to be different from the work files. It is usually a bad idea to overwrite your work files with exports.

The TMX defaults for **Tiled** values (that is, **not** class/tile properties) are all sensible defaults and even people writing their own TMX parsers should generally not actually need to worry about most of them. And I've already written about the differences between TMX and TMJ.

Class/tile property values are a different thing from Tiled values in that the defaults are set by users, and that is why the option to resolve them (explicitly include them) is available. However, it's common to not need to resolve them, as normally people set their class property value defaults to match engine/game defaults, and tile properties are available in the tileset.

**Comment by kerrjnr** [comment]
Fair comments, though I don't normally overwrite my project file but I wanted to test how that might affect things because the default tmx export filename is identical to the project tmx and humans being humans, there's bound to be a Tiled user that's done it unintentionally :)
For my game situation, I'll be refactoring to expect the JSON export format as input, instead of XML, because I'd rather ignore fields I'm not interested in than have to cater for missing fields just because the default value wasn't changed.
Thanks again for taking the time to respond so promptly, as one of the chocolatey-tiled package maintainers, it's fantastic to see such great support in this key Tiled support area ❤️
