### ISSUE TITLE
Setting object.polygon in script makes all points (0,0)

### ISSUE THREAD

**Issue by IoriBranford** [mapeditor/tiled#3845]
**Describe the bug**
When a script assigns a new polygon to a MapObject, all the polygon points will end up as (0,0).

**To Reproduce**
1. Install the test script
```javascript
/// <reference types="@mapeditor/tiled-api" />

const TouchPolygon = tiled.registerAction("Touch Polygon", (action) => {
    let asset = tiled.activeAsset
    let selected = asset.selectedObjects
    if (!selected) {
        return
    }
    
    for (let object of selected) {
        let polygon = object.polygon
        if (!polygon)
            continue
        asset.macro("Touch Polygon", () => {
            // Doc says: "To modify the polygon of a MapObject, change or set up the polygon array and then assign it to MapObject.polygon"
            object.polygon = polygon.map((p) => ({ x: p.x, y: p.y }))
            tiled.log(polygon)
            tiled.log(object.polygon)
        })
    }
})
TouchPolygon.text = "Touch Polygon"

tiled.extendMenu("MapView.Objects", [
    { action: "Touch Polygon" }
])
```
4. Create a polygon or polyline object
5. Right-click on the object and select "Touch Polygon"
6. See console output

**Expected behavior**
The polygon is unchanged and two identical point arrays are output to console.

**Actual behavior**
The polygon collapses as all its points are zeroed. This is confirmed by console output, in which the second array has the same number of points but they are all QPointF(0,0).

**Specifications:**
 - OS: Linux Mint Vera
 - Tiled Version: 1.10.2

**Comment by eishiya** [comment]
`{ x: p.x, y: p.y }` is not a Point, it's a JS object that *looks* like a Point, so the assignment probably just doesn't work, and each point gets set to a default value. Try creating the Polygon points with `Qt.point(p.x, p.y)` instead.

**Comment by IoriBranford** [comment]
Qt.point does work, but I remember JS object points working in previous Tiled versions. (Don't have time to find which version ATM.) Thanks

**Comment by eishiya** [comment]
I think it was the change from Qt5 to Qt6 that made typing more strict.

**Comment by bjorn** [comment]
While Qt 6 has become more strict for functions called from JS, this is likely also the result of change 4a0f569ef848ff5647381704df705c192f234905 made for Tiled 1.10.2, where I changed the `QJSValue polygonValue` argument it took previously to a `const QPolygonF &polygon`, since that appeared to work just as well and avoids a bunch of annoying glue code.

However, I wasn't aware this would then only work for objects created using `Qt.point` as opposed to arbitrary objects having an `x` and `y` property, as previously supported. So now I wonder if I shouldn't just re-enable the annoying glue code also for Qt 6 builds for the setter function or whether there is any advantage of the `const QPolygonF &polygon` version (other than performance, which is likely better but unlikely to matter).

I'd stick with the more strictly typed one if it resulted in proper type errors, but as it stands there is apparently a silent failure to do what would be expected, which is worse.

**Comment by IoriBranford** [comment]
> So now I wonder if I shouldn't just re-enable the annoying glue code also for Qt 6 builds for the setter function

I agree with this on the principle of least surprise, since JavaScript isn't normally expected to be strict on types.
