### ISSUE TITLE
Why Y coord have decrease as this go up (offset, objects position) ?

### ISSUE THREAD

**Issue by webrobot1** [mapeditor/tiled#3869]
A lot of system have:

as Y go up it will be increase, but tiled have another reaction. As example look how MYSQL see polygon from example map (Unity engine have a same coord's system)
![image](https://github.com/mapeditor/tiled/assets/20768848/75018798-fd09-43fd-930e-799239f865bd)

If start poin is 0, 0 all what will be lower foк Y  must be decrease, not increase as in Tiled 

![image](https://github.com/mapeditor/tiled/assets/20768848/74b3ee05-7a6b-4fe8-bb05-681796ade858)

And like example is standart coord grill (up is increase, tiled have decrease)

![image](https://github.com/mapeditor/tiled/assets/20768848/e4d6f71e-5bfb-48ea-aef8-ea1e2d18368e)

**Comment by bjorn** [comment]
> A lot of system have:

While that's true, a lot of other systems (especially GUI applications and 2D rendering APIs) use a downwards Y axis with 0,0 in the top-left. See for example the [coordinate system used by QPainter](https://doc.qt.io/qt-6/coordsys.html), [GTK](https://docs.gtk.org/gtk4/coordinates.html), Java Swing and [2D API](https://docs.oracle.com/javase/tutorial/2d/overview/coordinate.html), [LÖVE's coordinate system](https://love2d.org/wiki/love.graphics), [SDL's rects](https://wiki.libsdl.org/SDL2/SDL_Rect), Allegro, [CSS object model](https://developer.mozilla.org/en-US/docs/Web/CSS/CSSOM_View/Coordinate_systems), etc.

The Y axis going down means Tiled uses a left-handed coordinate system. It's not right or wrong, it just needs to be taken into account when rendering Tiled maps using a framework with a right-handed coordinate system.

There is an issue open about supporting an inverted Y axis in Tiled (https://github.com/mapeditor/tiled/issues/249), however its most recent implementation (#2040) is a little stuck because inverting the Y axis is not just a display change, but also affects object origins and should possibly even affect the direction of the rotation. It's unclear to me whether it is really worth supporting.
