### ISSUE TITLE
Cropping map by selection leaves Tiled to think that tilesets are still in use

### ISSUE THREAD

**Issue by Ablu** [mapeditor/tiled#3884]
**Describe the bug**

**To Reproduce**
1. Crop map by a selection
2. Try to delete an now unused tileset
3. Warning occurs about tileset still being in use
4. Close file
5. Reopen file
6. Tileset can now be removed without warning

**Expected behavior**
Removing works without notification after the tileset is no longer used, without needing to reload

**Specifications:**
 - Tiled Version: 1.10.2

**Comment by eishiya** [comment]
Not a bug. Tiled does not automatically remove unused tilesets from maps, since that can be rather annoying. If you want to remove an unused tileset, you need to do it yourself. There is a script available to automate this: https://github.com/mapeditor/tiled-extensions/blob/master/remove-unused-tilesets.js

**Comment by Ablu** [comment]
I am not complaining about it not getting removed automatically.

I just noted that Tiled still warns you when manually removing the tileset even if it is no longer used after the resize :).

**Comment by bjorn** [comment]
Right, this is likely due to "used tilesets" being cached for performance reasons. Seems like the cache is not getting invalidated in this case.
