### ISSUE TITLE
World Map chunks getting loaded twice.

### ISSUE THREAD

**Issue by grumpygamer** [mapeditor/tiled#3927]
I have notice some odd behavior when editing world maps. A map chuck gets opened twice (2 tabs) and one of them is a old version, it seems these come from a chuck loaded due to it being next to an active chunk and it's showing an old in-memory copy, not the current. I have lost work with this due to the outdated chucking being saved.  Closing Tiled and restarting always fixes it.

 - Mac 14.2.1
 - Tiled Version: 1.10.2

**Comment by grumpygamer** [comment]
By chunk I mean the sub-maps that make up a world in Tiled.

**Comment by eishiya** [comment]
Those are all separate, wholly independent maps, they're just displayed together as part of a World.

However, it *is* possible that a map being opened as part of restoring the session *and* as part of a World could be part of the issue. It shouldn't happen, and normally doesn't, but I suspect there's something weird happening specifically when automatically restoring the last session.

**Comment by bjorn** [comment]
I was able to reproduce this issue today. The problem happens because the implementation of reload-on-change only replaces the map in its own editor tab and not the instances of the same map within the world in other tabs. So after the reload, we have both the old and the new version loaded. When you then click an old version of the map, it will get its own tab alongside the new version. :-/

I will look for ways to make sure no old versions of maps will stay around in a world. This also means they need to be watched for changes even when no editor is currently open for them.

**Comment by bjorn** [comment]
PR #3939 basically fixes this issue, since it should prevent multiple versions of the same map being loaded or even opened side-by-side. However, I'm keeping this issue open until I've also implemented reloading for world maps that aren't currently open for editing, since otherwise you can still end up with an unexpected old version.
