### ISSUE TITLE
Switch keyboard shortcuts for "Save As" and "Save All"

### ISSUE THREAD

**Issue by differenceclouds** [mapeditor/tiled#3933]
(I'm on MacOS) With most other programs, Save As is command+shift+s, not command+alt+s. It's frustrating to inadvertently destroy the last saved copy of something by accident by hitting "Save All" when "Save As" was intended.

**Comment by eishiya** [comment]
You can customise the shortcuts in Edit > Preferences > Keyboard.

**Comment by bjorn** [comment]
While it is true that it can be reconfigured, I wonder if it would make sense to change this shortcut. However, it would of course cause issues for some existing users.

While there must have been some applications using Ctrl+Shift+S as "Save All" (one example is Qt Creator, the IDE I  use to develop Tiled), it does appear much more commonly used for "Save As" (checked Sublime Text, VS Code, Mousepad, GIMP, Inkscape, Krita and LibreOffice).

**Comment by eishiya** [comment]
There was actually a bit of foscussion about this last year on Discord, someone else complained about this exact thing, and at the time I checked the software I have:
> Notepad++ has Shift for Save All and Alt for Save As, same as Tiled.
Aseprite, Photoshop, Pyxel Edit, and Krita don't have Save All, and use Shift for Save As.
Code::Blocks has Alt for Save Everything and no shortcut for Save As, how odd!
>
> Looks like Save All isn't as common as one might expect, so it's not surprising there isn't a widely-agreed upon shortcut for it.
I guess programs go for Ctrl+Shift+S for the thing that's likely to be more commonly used in them specifically and Ctrl+Alt+S for the other thing, if they have another thing at all.

If a change is to be made, I think I'd go for Shift+Ctrl/Cmd+S for Save As, and have Save All unassigned by default. Save All seems pretty rarely needed in level-editing, and can always be assigned by those who do need it, and leaving it unassigned should avoid accidental saves (Save As is unlikely to cause problems when triggered accidentally because it pops up a dialog).
