### ISSUE TITLE
Tile metadata

### ISSUE THREAD

**Issue by AJLProjects** [mapeditor/tiled#3959]
I would like to be able to decorate a tile with data.
For a single tile I would like to specify data.
For example I have a side scroller. There is a swing block. You can swing using the rope. I would like to be able to specify on the tile how long the rope should be. Or maybe I have a door tile. I would like to specify if the door is locked or not. without having a separate tile for each state locked/unlocked.

**Comment by eishiya** [comment]
For properties specific to an instance of tile (rather than to all instances of that tile), this can be done with Tile Objects. Tile Objects are usually the way to go for dynamic elements such as doors, collectibles, etc.

Things like ropes might be more conveniently represented with a Polyline (with two points representing start and end; more complex rope scenarios can be represented using polylines with more points), or with a Tile Object or rectangle that is stretched to the length of the rope. Represented this way, the length is visible while editing the map instead of having to be typed into a custom property. The downside is you'll need to parse this while loading the map, since it won't be a ready-made custom property.

**Comment by AJLProjects** [comment]
@eishiya Maybe I gave a bad example. Here is a better one. I have a chest tile. This is a grid tile because it needs to conform to the grid. 

The chest can contain items. It would be nice to have a JSON popup so that I can edit the contents of the chest.

**Comment by eishiya** [comment]
Again, Tile Objects are the way to go there. You can make sure they're aligned to the grid by using the Snap to Grid option, and a custom String property can contain your JSON (if you click the "..." button in the string property, you'll get a pop-up multi-line string editor).

**Comment by AJLProjects** [comment]
@eishiya  its not a a correct in the purest way and is more a hacky work around. But I will close, since I can round the position to the nearest tile(integer) on my game logic.

**Comment by eishiya** [comment]
I should also mention: There's already an issue open for per-cell custom properties, so if you'd like that to be added, please read and possible add to the discussion there: #31
