### ISSUE TITLE
Make Stamp Brush right-click cut instead of copying when Shift is held

### ISSUE THREAD

**Issue by kdx2a** [mapeditor/tiled#3961]
**Is your feature request related to a problem? Please describe.**
Moving a group of tiles on a tile layer is too convoluted for such a common operation. Unless I miss something, here's the fastest way to do so (with default keybindings):
* [press R] switch to Rectangular Select
* [left click] select area
* [C-x] cut selection
* [b] switch to Stamp Brush
* [left click] paste area

**Describe the solution you'd like**
Allow to cut a rectangular area in Stamp Brush mode by holding Shift and right-clicking (in addition to the current copying behavior).

**Describe alternatives you've considered**
* Add a binding to quickly delete the last area copied with the Stamp Brush.
* Allow moving a selection directly (ie. by holding right click).

**Comment by eishiya** [comment]
Displacing tiles within a layer is a common operation for some users, but is never needed for others, so overall, it's a rarely-needed feature, which is why it's not gotten much attention.

I think your proposed expansion of the current copying behaviour sounds great! Way more elegant than the more complex behaviour I was thinking of. Shift+right-click seems to be free, it currently causes the Brush Stamp to just not do anything.

Big fat +1 to **making Stamp Brush right-click cut instead of copying when Shift is held**.
(For clarity, consider changing your issue title to something that describes your proposed change, as your title makes it sound like you want something more complicated.)

I'd previously scripted a Move Tiles Tool that allows moving tiles in multiple drags and via the arrow keys, and while a more complex style of operation like that can be desirable, in practice, a quicker way to just cut and paste would be way faster, even in scenarios where small, precise movements of large groups of tiles are desired.

**Comment by kdx2a** [comment]
Thank you for your feedback @eishiya! I had time off today, so I looked into the codebase to see how possible it would be and I ended up implementing the feature myself. It wasn't as straightforward as I would have expected, but it works very well now and is very convenient in terms of workflow.

**Comment by bjorn** [comment]
Implemented by #3963.
