### ISSUE TITLE
Tiles have `class` in properties in case in .tmx file is always `type`.

### ISSUE THREAD

**Issue by ManPython** [mapeditor/tiled#4027]
Tiles have `class` in properties in case in .tmx file is always `type`.
Should by `type` not `class`.

**Comment by joereynolds** [comment]
Depends what version of Tiled you are using. 
Upgrade to the latest version and use `type`.

There was a bit of back/forth a few release ago around this:
https://www.mapeditor.org/2023/03/10/tiled-1-10-released.html

This isn't a bug. Please can you close this and the other issues that others have answered for you?

**Comment by ManPython** [comment]
I'm using 1.11 and not have type but class.

**Comment by bjorn** [comment]
Right, while the file format change was reverted in 1.10 for compatibility, the UI change has not since "Class" provides a more consistent naming to the user.

It's unfortunate to have inconsistency between the GUI and the file format, but it's not the only case (for example "objectgroup" in TMX is "object layer" in UI, and "wangset" in TMX is "Terrain Set" in UI). It's trying to strike a balance between keeping compatibility but providing an easier to understand naming in UI and manual.
