### ISSUE TITLE
Mixing sprites as 32x32 with 64x64 not working correctly 

### ISSUE THREAD

**Issue by ManPython** [mapeditor/tiled#4036]
**Describe the bug**
Mixing sprites as 32x32 with 64x64 not working correctly.

**To Reproduce**
 Prepare sprites 64x64

**Expected behavior**
Allocate 64x64 tiles as 4x 32x32 not one 32x32.

**Media**
 
![Tile_64x64](https://github.com/user-attachments/assets/7c939118-d062-4a19-bf5f-53096103e66c)

**Specifications:**
 - OS: [e.g. Windows 10]
 - Tiled Version: 1.11

**Comment by eishiya** [comment]
Can you describe what you did, and what you expected? What I'm seeing in your screenshot is the more useful behaviour of a single tile taking up a single cell no matter how large it is.

In Tiled, the map's grid size determines how tiles are placed. An oversized tile is still just a tile that takes up a single slot. This allows effects like having tall trees that stick up out of their cells, overlapping other trees, and other workflows relying on oversized tiles. It's also possible to set the tiles to shrink to fit the cell instead of sticking out of it.

If you want 64x64 tiles to be placed as four 32x32 tiles, then you should make the tileset with 32x32 tiles, so that each "tile" is actually four tiles, with four separate identifiers that can be placed in four separate cells.

**Comment by ManPython** [comment]
It's not good idea to enhance functionality around 64x64 to place on 4 tiles as option?
It can be more easy to painting world by 64x64 sometimes than build from 4x 32x32, even when pastern can be taken with 4.

**Comment by bjorn** [comment]
> It's not good idea to enhance functionality around 64x64 to place on 4 tiles as option?

Yes, it would be a good idea. That's covered by issue #3436 though.
