### ISSUE TITLE
`console.log` not working in scripts

### ISSUE THREAD

**Issue by bendmorris** [mapeditor/tiled#4037]
I recently updated from a pretty old version of Tiled to the latest, and `console.log` used to show up in the editor console, but no longer does. This is really convenient and often the most practical way to debug a script, and currently I'm using throwing an error as a substitute :sweat_smile: which obviously is not nearly as convenient. I checked some old versions and this seems to have not worked for a while, but does work way back in 1.4.0:

![Screenshot from 2024-08-18 17-04-38](https://github.com/user-attachments/assets/8550e0a0-70a1-4ee7-8386-5f82e6a0c189)

vs. latest:

![Screenshot from 2024-08-18 17-04-52](https://github.com/user-attachments/assets/d3f35602-69e3-4382-8ec0-bed96e84f67e)

(I didn't bisect this and don't know exactly when it stopped working.)

**Comment by eishiya** [comment]
This is a known issue. You should use `tiled.log` instead.

**Comment by bjorn** [comment]
Yeah, I think the problem was that I couldn't find a way to route `console.log` to the Console view without also routing all other console output there, and it was causing confusing or irrelevant warnings to be shown in some cases (see 04a64700a3d6ed850ad21a17f77cbcc6768e647c).

So, `console.log` works, but only for printing to the actual console (standard out), not to Tiled's Console view.
