### ISSUE TITLE
request: nes workflow

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#4088]
**Is your feature request related to a problem? Please describe.**
Tiled does not support nes specific workflow I think
https://discourse.mapeditor.org/t/nes-style-8x8-to-16x16-tile-workflows/4054

**Describe the solution you'd like**
I would like to request this workflow as seen in the forum

**Comment by eishiya** [comment]
Metatiles are already supported, and it was this sort of workflow that the feature was added to support. You would create your 8x8 tileset, then create a map where you build your 16x16 metatiles out of the 8x8 tiles. Create a new tileset using that map as the source "image", and you can use the 16x16 tiles in your levels, instead of using the 8x8 tiles directly.

In your Tiled map -> NES converter, you'd probably use the metatile IDs, but also the metatile source map to create your metatile -> subtile mapping.

**Comment by circl-lastname** [comment]
Can be closed

**Comment by bjorn** [comment]
Yeah, this is covered by the issue about documenting metatiles.

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
