### ISSUE TITLE
copy tile not working

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#4113]
**Describe the bug**
If you select a tile, choose copy, move to another position and choose paste, nothing happens.

**To Reproduce**
1. Select a tile
2. Choose copy
3. Move to another position
4. Choose paste

**Expected behavior**
The tile should be copied to the new position

**Specifications:**
 - OS: Windows 11
 - Tiled Version: 1.11

**Comment by bjorn** [comment]
Pasting a copied tile selection makes it the active tile stamp rather than directly placing it on the map. This has a number of advantages:

- It is easier to place it in the correct location, based on the brush preview.
- It is possible to paste a tile selection and place is using a different tool, or to place it with a modifier (for drawing lines or circles, for example).

A disadvantage might be that if you're pasting just a single tile and this is already the currently selected one, you won't notice anything happening. It's also just not very standard behavior.

When we eventually implement a "move selection" feature (#650), we could revisit the paste behavior to see if it makes sense to integrate with that by default, though then we'd need a separate "Paste to Current Tile Stamp" action since it would still have its use.
