### ISSUE TITLE
64 Bit Version for Windows available?

### ISSUE THREAD

**Issue by Kaffibecher** [mapeditor/tiled#443]
As mentioned in the title I want to know if there is a 64 Bit available?

Regards

CD

**Comment by bjorn** [comment]
For completeness sake, I'll just note here that 64-bit builds have been available since a while now and can be compiled using Visual Studio versions of Qt.

As of right now though, there is still a problem when using Qt 5.6.0, since it removed the zlib headers that were usually shipped with Qt (and it seems the exported symbols are gone as well). So for now the Tiled binaries are still using Qt 5.5.1. I hope to resolve this sometime soon.
