### ISSUE TITLE
Add support for other types of plugins

### ISSUE THREAD

**Issue by leiradel** [mapeditor/tiled#454]
Right now Tiled only supports plugins for reading/writing map files. It would be great if there was an option to add more functionality to Tiled via other types of plugins.

Some examples:
- A maze plugin which generates a random maze as a new layer in the current map, maybe using a terrain or user-chosen tiles.
- A forest plugin which generates a new layer with a forest, where the user specifies the tree density and maybe a constraint that the forest should be walkable from a point to another. The tiles that form the tree(s) should be selected by the user.
- A house plugin that would generate random houses from a tileset (this plugin would be tied to a specific tileset.)

**Comment by rae** [comment]
+1 for adding scripting to Tiled. I'd like to use it to validate maps using game-specific logic.

**Comment by s-m-k** [comment]
This is the feature Tiled needs to become a really good production-tier multi-purpose editor. Now it's good for limited cases, but if I want to add some custom features, the workflow becomes not that good and it's clear that I will have to write my own specialized editor from scratch.

For example, I want to encode some logic in a visual way. I have to either write/use some external tool or mess with objects (which isn't a good workflow). With plugins, I could just code my own node system on top of the rest and edit everything in Tiled.

**Comment by eishiya** [comment]
Since Tiled supports JavaScript scripting now and allows scripts to implement not only new map and tileset formats, but also arbitrary actions, signal handers, and entire custom tools and GUI windows, perhaps this issue can be closed?

There are some features that are still not present and which can still only be added via forking Tiled, such as previewing objects (#3383), but I think those are best off having their own specific issues.

**Comment by bjorn** [comment]
Thanks for bring this up, @eishiya. The addition of scripting definitely addressed this need and already allows for a broad range of extensions, including those initially suggested here.
