### ISSUE TITLE
Mac version sometimes can't render anything in GUI editor

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#529]
See the image : 

![tiled mac](https://f.cloud.github.com/assets/288367/1228514/a0471fec-27a5-11e3-963f-0d4b78e954de.jpeg)

**Comment by rainman110** [comment]
We had a similar issue in our OpenGL based application (https://github.com/DLR-SC/tigl/issues/143).  It all comes down using the unified toolbar and native windows (which is the case with opengl widgets).

The Qt issue is reported here: https://bugreports.qt.io/browse/QTBUG-41257

In our case it helped, to set the `Qt::AA_DontCreateNativeWidgetSiblings` application attribute. This workaround is described in the last section of the Qt bug report. Thus, you might reenable OpenGL again ;-)

**Comment by bjorn** [comment]
@rainman110 I'll certainly give that a try, thanks!

I had missed the last 0 in my URL and fixed it now. I've commented on your issue that it is a duplicate, because it's really about the same problem. QTBUG-39210 seems to have a much higher priority and has more votes, yet the bug remains unfixed. :-/

**Comment by bjorn** [comment]
@rainman110 Well, I tried setting that option and while it indeed fixed the issue of the black tool bar and the ability to exit full screen, I still noticed a strange broken area of the window where I couldn't click through (which I could not reliably reproduce though). Also, the "accelerated" mode is a lot slower than the software rendering mode, at least on the old Mac Mini I'm testing on. Apart from that, the UI starts flickering and shifting about during resize due to the need for a native widget destroying the double buffering mechanism.

So, I think it's probably just not worth it. Proper accelerated rendering will hopefully come in a QtQuick-based version of Tiled eventually. Initial tests on the `wip/qtquick` branch were quite promising, but it'll be a big project.
