### ISSUE TITLE
Animated Tiles

### ISSUE THREAD

**Issue by stefanbeller** [mapeditor/tiled#57]
Tiles should easily be animated.
Either by using an animated gif or other animated format.
The other option would be to cycle through some tiles within one tileset.

**Comment by Rialgar** [comment]
I would really like to have multiple (named) animations on one tile, this is especially useful for objects, since these might change their animation during the game.
Some examples:
* Collectibles that make a little splosh when collected
* Enemies that can walk, stand, die, ...
* A Goal that shows a nice animation when reached

It would be great to have all these animation specifications in a single place, and I think the Tiled file would be an excellent location.

For the time being I will probably create each animation on the starting tile and add the names as custom properties.

**Comment by bjorn** [comment]
@Rialgar Yes, it's a feature that could be added. Maybe you could open a separate issue about it?

**Comment by hoangbv15** [comment]
hello, apologies on commenting on a very old and closed issue, but I am genuinely wondering if there's a more efficient way of defining tile animations, other than selecting a tile, choosing "tile animation editor" menu option, drag and drop tiles, repeat. 

My tile set has above 100 tiles, with each tile has its own animation. It does become a bit tedious going through the GUI to do the animation for all tiles. 

The frames are put vertically on top of each other in a sprite sheet, so potentially could I manually edit the .tmx file with a text editor to add the animation myself? Or is there a better way to do it?
