### ISSUE TITLE
 Remember export location on a per map basis

### ISSUE THREAD

**Issue by cluke009** [mapeditor/tiled#604]
Currently tiled doesn't remember the last export location on a per map basis. 

My map folder looks like this:
- maps/
  - map1/
    - map1.lua
    - map1.tmx
  - map2
  - etc ....

Its incredibly tedious moving back and forth to export maps.

**Comment by thomasgoldstein** [comment]
Are Tiled issues groomed or maintained at all?
This issue is 6 years old, and it's been a while now that Tiled has this feature through the `<export target />` element. I believe this should be closed.

**Comment by bjorn** [comment]
@thomasgoldstein Of course I spend time going over old issues sometimes, but any help with this is really appreciated so thank you for bringing this one to my attention! Such a thing usually happens when a kind of duplicate issue was opened and I didn't notice it, and then I closed only the duplicate.

In this case, this was implemented as part of closing #1610.
