### ISSUE TITLE
Incorrect gid for tileproperties JSON output

### ISSUE THREAD

**Issue by kittykatattack** [mapeditor/tiled#605]
The JSON output for gid tile properties of off by one.
You can see in this tileset that the skull tile should have a gid of 5
![f03001](https://f.cloud.github.com/assets/2936104/2060660/08bbc51e-8c28-11e3-95c7-1cc80ed44d5a.png)
This is correct in the "data" array:

```
"data":[0, 0, 0, 5, 0, 0 ... ]
```

However, it's off by one in the tileproperties  

```
"tileproperties":
{
 "4":
    {
     "name":"skull"
    },
},
```

As you can see, this should be "5"

This is true of all 9.1 versions, up to the current: v0.9.1-223-gb0e29e8

**Comment by quoji** [comment]
"You can use the "firstgid" property of your tilesets to figure out from which tileset the global ID must be and to map it to a local ID in that tileset (by subtracting the "firstgid"). In the case of a single tileset, you can always just subtract 1 since that's the "firstgid" of the first tileset."

Could someone explain how this is done programatically? Changing firstgid in the JSON doesn't do anything. No mention of this issue in https://github.com/bjorn/tiled/wiki/JSON-Map-Format either
Are we supposed to use terrains since it uses local ID? Or do I need to write a script to edit the data field?
