### ISSUE TITLE
mouse wheel horizontal scrolling

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#785]
Someone already suggested an autoscroll feature (#451). I'm not sure about that.

But I really would appreciate, if there would be horizontal scrolling with the mouse wheel, as many other applications do it.

Suggestion: when pressing shift and moving the mouse wheel, the map would scroll left or right.

**Comment by ssokolow** [comment]
For anyone who wanders in here off Google, I can confirm that it's almost certainly your WM that's the problem if a Qt widget isn't treating <kbd>Alt</kbd>+<kbd>Scroll</kbd> as horizontal scrolling.

That said, there may be no simple end-user fix.

In KDE, for example, all your <kbd>Modifier</kbd>+<kbd>Button</kbd> mouse actions for Kwin must share the same modifier key, which means that, if your muscle memory expects the standard <kbd>Alt</kbd>+<kbd>LeftClick</kbd> that has become a *de facto* standard for "move window without grabbing the titlebar", then it's going to be <kbd>Alt</kbd>+<kbd>Scroll</kbd> that the WM wants... which leads to some odd interactions in KDE 5.x, since Kwin 5.x lets the events through if it feels nothing needs to be done. (eg. If you set <kbd>Alt</kbd>+<kbd>Scroll</kbd> to be Shade Up/Down, whichever direction has no effect *will* result in the underlying widget scrolling horizontally.)

As a programmer, that's why I override `wheelEvent` in my PyQt apps and, if `event.modifiers() & Qt.ShiftModifier`, I synthesize a new `QWheelEvent` with `Qt.NoModifier` from the one received (to prevent "page per detent" scrolling), send it to `self.horizontalScrollbar().event`, and then call `event.accept()` to prevent it from also scrolling vertically.

(ie. I forcibly implement the <kbd>Shift</kbd>+<kbd>Scroll</kbd> binding that Chrome has used by default for ages and Firefox picked up some time within the last few years.)
